### ISSUE TITLE
ttnn.reshape fails for float32 tensors

### ISSUE THREAD

**Issue by pilkicTT** [tenstorrent/tt-metal#14885] opened 2024-11-08 09:42 UTC
Necessary conditions for repro:
1. Tensor is not in bfloat16 or uint32 data format
2. Tensor is in `TILE_LAYOUT`
3. Reshape of the tensor goes through `convert_tensor_to_rm_reshape_convert_back_to_orig_layout()`

In this case, the following `TT_FATAL` gets triggered:
```
TT_FATAL @ /localdev/pilkic/tt-metal/ttnn/cpp/ttnn/operations/data_movement/tilize_with_val_padding/device/tilize_with_val_padding_op.cpp:19: input_tensor_a.get_dtype() == DataType::BFLOAT16 or input_tensor_a.get_dtype() == DataType::UINT32
info:
Can only tilize bfloat16 or uint32 tensors
```

The weird thing is that the tensors of the same shape (and data format) can be created via `ttnn.from_torch()` in tile layout.

We've hit this on `tt-forge-fe` on newer version of `tt-metal`, when the above assertion was changed from `TT_ASSERT` to `TT_FATAL`. Previously, the assertion was not being check (since we run tests with non-debug builds of `tt-metal`) and the tests were passing.

Related to issue #14570

Repro:
```python
with ttnn.manage_device(device_id=0) as device:
    # Creating tensors from torch tensors of the same shape
    # (as input to reshape and output of the reshape) works as expected
    in_a = torch.randn(1, 1, 756, 128)
    in_a = ttnn.from_torch(in_a, dtype=ttnn.float32, layout=ttnn.TILE_LAYOUT, device=device, memory_config=ttnn.DRAM_MEMORY_CONFIG)
    print(in_a.shape)

    desired_shape = [1, 27, 28, 128]
    in_b = torch.randn(*desired_shape)
    in_b = ttnn.from_torch(in_b, dtype=ttnn.float32, layout=ttnn.TILE_LAYOUT, device=device, memory_config=ttnn.DRAM_MEMORY_CONFIG)
    print(in_b.shape)

    # Reshape the original input tensor to the desired shape
    # - fails with `Can only tilize bfloat16 or uint32 tensors`
    output_device = ttnn.reshape(in_a, desired_shape)
    output_tensor = ttnn.to_torch(output_device)
    print(output_tensor.shape)
```

**Comment by tt-mpantic** [comment] 2024-11-08 09:50
P0 because this is regression in latest metal to Forge version uplift.

**Comment by jvasilje** [comment] 2024-11-12 16:13
@ntarafdar is this an actual regression or an improvement in error msgs?

Reshape is being actively worked on. Want to make sure we're not tracking reshape improvements as P0-bugs.

**Comment by ntarafdar** [comment] 2024-11-12 16:16
this is a bug in untilize, tilize
@yugi957 has a fix for this coming within the next day or two

**Comment by pilkicTT** [comment] 2024-11-13 10:55
> can you confirm that this is a regression., because float32/int32 untilize and tilize never really worked before.

previously the `TT_ASSERT` didn't trigger because we are running release builds of `tt-metal` (now it is `TT_FATAL` so it gets triggered)

**Comment by yugi957** [comment] 2024-11-13 19:01
fp32 is merged into main now btw, Should be able to close this issue!

**Comment by jvasilje** [comment] 2024-11-14 17:03
@pilkicTT @yugaoTT can you close this issue now?

**Comment by kmabeeTT** [comment] 2024-11-15 15:57
Hi, we see similiar issue in other assert when doing another tt-metal uplift based on yesterday commit. @pilkicTT says it passes when updating this assert to allow FLOAT32, can you make fix?

> they've fixed that case in latest main, but not this one... it seems that this TT_FATAL is outdated and can be updated to include FLOAT32 tensors...

error we see:

https://github.com/tenstorrent/tt-mlir/actions/runs/11843742210/job/33007136624#step:14:4921

```
2024-11-14 19:43:24,687 - DEBUG - starting loop=1/1 for binary=/__w/tt-mlir/tt-mlir/build/test/ttmlir/Silicon/TTNN/Output/operand_broadcasts.mlir.tmp.ttnn
                 Always | FATAL    | Error
2024-11-14 19:43:25,514 - ERROR - ERROR: test=/__w/tt-mlir/tt-mlir/build/test/ttmlir/Silicon/TTNN/Output/operand_broadcasts.mlir.tmp.ttnn experienced an error with exception=TT_FATAL @ /__w/tt-mlir/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/data_movement/tilize/device/tilize_op.cpp:21: input_tensor_a.get_dtype() == DataType::BFLOAT16
```

**Comment by ntarafdar** [comment] 2024-11-15 21:18
@yugi957

**Comment by zzigler-tt** [comment] 2024-11-18 18:54
@yugi957 Can you please update this issue? Thanks

**Comment by yugi957** [comment] 2024-11-18 18:59
@kmabeeTT @ntarafdar @zzigler-tt https://github.com/tenstorrent/tt-metal/pull/15115
This PR is just failing on one grayskull 150 perf regression for some reason, that's the only thing holding back the tilize_op issue, otherwise it's fixed.

**Comment by kmabeeTT** [comment] 2024-11-18 19:14
@yugi957 , should be safe to ignore (noise) gs 150 perf test,  since change is only modifying an assertion I'd think, right?

**Comment by yugi957** [comment] 2024-11-18 19:19
@kmabeeTT I agree, it is just an assertion modification. Just merged! Tilize op now has access to fp32. Can you rerun that job and if it passes we can close this issue?

**Closed** 2024-11-18 19:20 UTC
Labels: bug, P0, forge
