### ISSUE TITLE
ND PCC with TG Llama3-70b on CI

### ISSUE THREAD

**Issue by mikevin920** [tenstorrent/tt-metal#10946] opened 2024-07-31 14:54 UTC
**Describe the bug**
ND behaviour for TG Llama Decoder and Model on CI possibly due to old firmware

Passing run:https://github.com/tenstorrent/tt-metal/actions/runs/10153695333
Failing run on Llama Decoder: https://github.com/tenstorrent/tt-metal/actions/runs/10176375557/job/28146147653
Failing run on Llama Model: https://github.com/tenstorrent/tt-metal/actions/runs/10165761756/job/28115090004

**Comment by uaydonat** [comment] 2024-07-31 15:01
I think we confirmed that the ci machines have older fw? @tt-rkim

**Comment by tt-rkim** [comment] 2024-07-31 15:07
You can read the set up runner logs and check yourself.

I see from my FW date get script:

```
ok: [g14cs03] => {
    "msg": "2024-07-17"
}
```

I've already told @mikevin920 to test and qualify the new firmware releases, as there have been quite a few for galaxy, including one this week to lower clock frequency.

We are not planning to do an upgrade until this work is done and someone writes a ticket that's not us, as we've made clear to the team.

**Comment by tt-rkim** [comment] 2024-07-31 15:09
We now output the full SMI information as a courtesy so you can check things like coordinates, FW, driver etc.

**Comment by kpaigwar** [comment] 2024-07-31 16:11
<img width="1805" alt="Screenshot 2024-07-31 at 11 27 58 AM" src="https://github.com/user-attachments/assets/50449723-abe7-4ff9-b9ab-0c3cd8b26923">
<img width="1805" alt="Screenshot 2024-07-31 at 11 29 15 AM" src="https://github.com/user-attachments/assets/a50a6ddf-b66c-4d25-821f-e72804840ad1">

**Comment by tt-rkim** [comment] 2024-07-31 16:16
Your FW is quite out of date, and your driver N150s FW are out of sync with the on-board Galaxy FW.

Do you want devinfra to update your ? If so, you should file a ticket with them for now, or if your team can upgrade yourself, you should upgrade yourself.

**Comment by mikevin920** [comment] 2024-07-31 17:45
<img width="1519" alt="image" src="https://github.com/user-attachments/assets/bb7ab3a0-e8bf-4145-b921-7bd74328a1b7">
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/de7a76be-7732-422a-85b9-f0732d17bd13">
Flashed latest n150 firmware + galaxy FW on aus-glx-01

**Comment by tt-rkim** [comment] 2024-08-06 14:53
N150s still look a little out of date...

**Comment by kpaigwar** [comment] 2024-08-09 15:30
Update: We are still seeing the ND PCC behavior on galaxy CI even after FW update. Also, to add on our local machines also discovered the same behavior upon more stress testing.

Is there any new galaxy FW we can test? 
Currently, devices are initialized at 800 MHz. What are the ways to test at 500 MHz to determine if it's a di/dt issue?

**Comment by kpaigwar** [comment] 2024-08-09 15:32
fyi @skhorasganiTT

**Comment by tt-rkim** [comment] 2024-08-09 20:17
You should catch up with @tcolacoTT. Tyler, please comment on:

- any upcoming Galaxy experimental patches
- simpler ways that Models team can downclock their devices.

Kartik, note that the current patch should be setting AICLK max to 900MHz.

**Comment by prajaramanTT** [comment] 2024-12-05 22:49
@cglagovichTT is this issue truly done ? The status says, Done but the ticket is still Open.

**Comment by cglagovichTT** [comment] 2024-12-06 15:02
This could be a duplicate of https://github.com/tenstorrent/tt-metal/issues/10673.
@kpaigwar when you saw ND PCC were you running DRAM sharded MMs?

**Comment by kpaigwar** [comment] 2024-12-06 15:44
We have a demo nightly pipeline in CI which doesn't run DRAM sharded MMs.
Earlier we were seeing ND outputs for count in binary prompt
But upon checking a bunch of latest pipelines, we are pretty stable on output side.
We may close this issue.

**Closed** 2024-12-31 17:30 UTC
Labels: bug, LLM_bug, LLMs on Metal, llama2-70b, llama3
