### ISSUE TITLE
Fix output error on Llama 3.1 on single-card demos

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#12445] opened 2024-09-10 13:33 UTC
https://github.com/tenstorrent/tt-metal/actions/runs/10783314904/attempts/1

Looks like an output error that's been dogging us for a while.

**Comment by mtairum** [comment] 2024-09-10 13:36
This issue seems to be a duplicate of this one: https://github.com/tenstorrent/tt-metal/issues/12215

**Closed** 2024-09-10 13:38 UTC
Labels: bug, P1_critical, LLM_bug, ci-bug
