### ISSUE TITLE
[Feature Request - From Grayskull UXR] Create find_metalium.cmake

### ISSUE THREAD

**Issue by adifrancescoTT** [tenstorrent/tt-metal#9574] opened 2024-06-20 15:08 UTC
**Is your feature request related to a problem? Please describe.**

Now Metalium builds on CMake, great! But when I try to link to Metalium from CMake I have to specify all the variables, the object files, specify those manually. 

**Describe the solution you'd like**
Find_Metalium.cmake would normally locate the metalium libraries for you, can we do that?

**Describe alternatives you've considered**
Manually linking everything

**Comment by tt-rkim** [comment] 2024-06-21 12:44
We would like need to expose `tt_metal` and `ttnn` libraries for this.

cc: @vtangTT @TT-billteng How can we triage priority here?

**Comment by marty1885** [comment] 2024-06-25 17:25
The original reasoning for `FindMetalium.cmake` is because on Linux systems, it is common for vendors to provide a `*.deb|rpm` package or someone straight up building from the AUR. Both CUDA and ROCm have taken this approach. And in my experience maintaining AUR packages (I'm a maintainer of [drogon](https://github.com/drogonframework/drogon), it's usually a upstream bug if downstream crashed due to a different build configuration).

I don't expect people using metalium as a submodule as the repo, along with it's dependencies and the LFS is GBs large. 

Conan does sound like a solution. But I find it tricky to integrate Conan packages into projects that don't support conan as a 1st class citize. I'm working on GGML integration, for example. I might be wrong though.

**Comment by TT-billteng** [comment] 2024-06-25 21:47
> The original reasoning for `FindMetalium.cmake` is because on Linux systems, it is common for vendors to provide a `*.deb|rpm` package or someone straight up building from the AUR. Both CUDA and ROCm have taken this approach. And in my experience maintaining AUR packages (I'm a maintainer of [drogon](https://github.com/drogonframework/drogon), it's usually a upstream bug if downstream crashed due to a different build configuration).
> 
> I don't expect people using metalium as a submodule as the repo, along with it's dependencies and the LFS is GBs large.
> 
> Conan does sound like a solution. But I find it tricky to integrate Conan packages into projects that don't support conan as a 1st class citize. I'm working on GGML integration, for example. I might be wrong though. System packages have been a good common denominator for me.

We'll queue it up as I have found this to be the best way to pull in a CMake project. I've also had bad experiences with vanilla conan as a package manager.

**Comment by ayerofieiev-tt** [comment] 2024-06-26 01:02
Got it. Perfect! Thank you!

**Comment by dmakoviichuk-tt** [comment] 2024-10-01 04:24
Bumping it up! Would be nice to get a current status.

**Comment by tt-rkim** [comment] 2024-10-01 13:40
will bring it up in infra team planning meeting today

cc: @blozano-tt @bkeith-TT

**Comment by blozano-tt** [comment] 2024-10-01 18:34
Open question here...

Why are we talking about `FindMetallium.cmake` which by convention implies `module mode` find_package, and requires more manual work?

When I think we could do `config mode` which would be implied by the convention `Metallium-config.cmake`.

In modern CMake, config mode is preferred for the following reasons:
```
Automatic Packaging: CMake can automatically generate *-config.cmake files when you build and install your project. This makes it easier for others to consume your library, as they don’t have to rely on a manually written FindPackage script.

More Control: With a *-config.cmake file, you can define exported targets, versioning, and other properties more explicitly. This provides better integration with modern CMake practices like target-based dependencies (e.g., target_link_libraries with imported targets).

Widely Used: Many modern CMake projects, including popular libraries, use *-config.cmake files because they offer better flexibility and easier integration.

Built-in Support: CMake offers built-in commands like install(EXPORT ...), export(...), and configure_package_config_file(...) to help generate and install package configuration files with minimal effort.
```

Official doc:
https://cmake.org/cmake/help/latest/command/find_package.html

**Comment by ayerofieiev-tt** [comment] 2024-10-01 19:28
Absolutely, we focus on the problem. 
Here, the demand is "we want to be able to consume metal / ttnn as simple as one line in cmake".
Instead, today one has to do lots of things to just get things running. See @dmakoviichuk-tt 's cpp sample, specially things like this:
https://github.com/tenstorrent/cpp-ttnn-project-template/blob/849c5be927f60d435afe24cc6acddbdd887331e0/sources/sample_lib/CMakeLists.txt#L26-L44

We can go any route which removes this complexity from consumer's shoulders.

**Comment by blozano-tt** [comment] 2024-10-03 18:26
Duplicate of https://github.com/tenstorrent/tt-metal/issues/7914

Although useful discussion in both places.

**Closed by blozano-tt** 2024-10-03 18:26 UTC
Labels: infra-ci, feature-request, P2_should_have, cppbuild, dependencies
