### ISSUE TITLE
Multi-chip Unit Tests - Falcon40b decoder/end-to-end hangs on T3000

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#8080] opened 2024-05-02 21:55 UTC
`pytest models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]`

Result is a hang, seeing the same thing on end to end as well: `pytest models/demos/falcon40b/tests/test_falcon_end_to_end.py::test_FalconCausalLM_end_to_end_with_program_cache[BFLOAT8_B-SHARDED-falcon_40b-layers_1-decode_batch32-4chips-enable_program_cache]`

**Comment by tt-dma** [comment] 2024-05-02 23:02
Passed once on CI, but hangs on my local: https://github.com/tenstorrent/tt-metal/actions/runs/8930996280

Will run a bunch more times to see if it's a machine issue

**Comment by tt-dma** [comment] 2024-05-03 08:39
Did a bunch of runs here: 
https://github.com/tenstorrent/tt-metal/actions/runs/8930996280
https://github.com/tenstorrent/tt-metal/actions/runs/8935451529
https://github.com/tenstorrent/tt-metal/actions/runs/8935452562
https://github.com/tenstorrent/tt-metal/actions/runs/8935453798
https://github.com/tenstorrent/tt-metal/actions/runs/8935454512
https://github.com/tenstorrent/tt-metal/actions/runs/8935455753

Seeing some weird nondeterminate behaviour, maybe machine dependent:
Run 11, f10cs07 - hangs on models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]
Run 10, f10cs08 - models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]
Run 9, f10cs06 - test fail on CommandQueueSingleCardFixture.TestLargeBuffer4096BPageSize
Run 8, f12cs02 - pass
Run 7, f10cs07 - test fail on CommandQueueSingleCardFixture.TestWrapCompletionQOnInsufficientSpace2
Run 6, f10cs07 - hangs on models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache] 
Run 5, f10cs08 - hangs on models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache] 
Run 4, f10cs06 - hangs on models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]
Run 3, f10cs06 - hangs on models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]
Run 2, f10cs07 - hangs on models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]
Run 1, f12cs02 - pass

On my local T3000, I consistently get a hang on models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]

**Comment by tt-dma** [comment] 2024-05-03 17:57
It's debuggable using watcher, here's a sample from the log:
```
Device 3 worker core(x= 0,y= 0) phys(x= 1,y= 1):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 1,y= 0) phys(x= 2,y= 1):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 2,y= 0) phys(x= 3,y= 1):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 3,y= 0) phys(x= 4,y= 1):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 4,y= 0) phys(x= 6,y= 1):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 5,y= 0) phys(x= 7,y= 1):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 6,y= 0) phys(x= 8,y= 1):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 7,y= 0) phys(x= 9,y= 1):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 0,y= 1) phys(x= 1,y= 2):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 1,y= 1) phys(x= 2,y= 2):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 2,y= 1) phys(x= 3,y= 2):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 3,y= 1) phys(x= 4,y= 2):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 4,y= 1) phys(x= 6,y= 2):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 5,y= 1) phys(x= 7,y= 2):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 6,y= 1) phys(x= 8,y= 2):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 7,y= 1) phys(x= 9,y= 2):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 0,y= 2) phys(x= 1,y= 4):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 1,y= 2) phys(x= 2,y= 4):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 2,y= 2) phys(x= 3,y= 4):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 3,y= 2) phys(x= 4,y= 4):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 4,y= 2) phys(x= 6,y= 4):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 5,y= 2) phys(x= 7,y= 4):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 6,y= 2) phys(x= 8,y= 4):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 7,y= 2) phys(x= 9,y= 4):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 0,y= 3) phys(x= 1,y= 5):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 1,y= 3) phys(x= 2,y= 5):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 2,y= 3) phys(x= 3,y= 5):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 3,y= 3) phys(x= 4,y= 5):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 4,y= 3) phys(x= 6,y= 5):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 5,y= 3) phys(x= 7,y= 5):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 6,y= 3) phys(x= 8,y= 5):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 7,y= 3) phys(x= 9,y= 5):   GW,   W,   W,   W,   W  rmsg:D1D|BNt smsg:DDDD k_ids:272|271|0
Device 3 worker core(x= 0,y= 4) phys(x= 1,y= 7):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 1,y= 4) phys(x= 2,y= 7):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 2,y= 4) phys(x= 3,y= 7):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 3,y= 4) phys(x= 4,y= 7):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 4,y= 4) phys(x= 6,y= 7):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 5,y= 4) phys(x= 7,y= 7):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 6,y= 4) phys(x= 8,y= 7):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 7,y= 4) phys(x= 9,y= 7):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 0,y= 5) phys(x= 1,y= 8):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 1,y= 5) phys(x= 2,y= 8):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 2,y= 5) phys(x= 3,y= 8):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 3,y= 5) phys(x= 4,y= 8):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 4,y= 5) phys(x= 6,y= 8):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 5,y= 5) phys(x= 7,y= 8):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 6,y= 5) phys(x= 8,y= 8):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 7,y= 5) phys(x= 9,y= 8):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 0,y= 6) phys(x= 1,y= 9):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 1,y= 6) phys(x= 2,y= 9):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 2,y= 6) phys(x= 3,y= 9):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 3,y= 6) phys(x= 4,y= 9):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 4,y= 6) phys(x= 6,y= 9):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 5,y= 6) phys(x= 7,y= 9):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 6,y= 6) phys(x= 8,y= 9):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 7,y= 6) phys(x= 9,y= 9):   GW,   W,   W,   W,   W  rmsg:D1D|BNT smsg:DDDD k_ids:443|442|444
Device 3 worker core(x= 0,y= 7) phys(x= 1,y=10):  NTW,UAPW,   W,   W,   W  rmsg:H1G|bNt smsg:GDDD k_ids:0|38|0
Device 3 worker core(x= 1,y= 7) phys(x= 2,y=10):  NTW, HQW,   W,   W,   W  rmsg:H1G|bNt smsg:GDDD k_ids:0|37|0
Device 3 worker core(x= 2,y= 7) phys(x= 3,y=10):  NTW, HQW,   W,   W,   W  rmsg:H1G|bNt smsg:GDDD k_ids:0|39|0
Device 3 worker core(x= 3,y= 7) phys(x= 4,y=10):  NTW,UAPW,   W,   W,   W  rmsg:H1G|bNt smsg:GDDD k_ids:0|43|0
Device 3 worker core(x= 4,y= 7) phys(x= 6,y=10): NSIW,   W,   W,   W,   W  rmsg:H0G|Bnt smsg:DDDD k_ids:40|0|0
Device 3 worker core(x= 5,y= 7) phys(x= 7,y=10): NSIW,   W,   W,   W,   W  rmsg:H0G|Bnt smsg:DDDD k_ids:42|0|0
Device 3 worker core(x= 6,y= 7) phys(x= 8,y=10):   GW,   W,   W,   W,   W  rmsg:H0D|bnt smsg:DDDD k_ids:0|0|0
Device 3 worker core(x= 7,y= 7) phys(x= 9,y=10):   GW,   W,   W,   W,   W  rmsg:H0D|bnt smsg:DDDD k_ids:0|0|0
Device 3 ethnet core(x= 0,y= 0) phys(x= 9,y= 0): NSID,   X,   X,   X,   X  k_id:199
Device 3 ethnet core(x= 0,y= 1) phys(x= 1,y= 0): NSID,   X,   X,   X,   X  k_id:197
Device 3 ethnet core(x= 0,y= 4) phys(x= 7,y= 0):   GW,   X,   X,   X,   X  k_id:0
Device 3 ethnet core(x= 0,y= 5) phys(x= 3,y= 0):   GW,   X,   X,   X,   X  k_id:0
Device 3 ethnet core(x= 0,y= 6) phys(x= 6,y= 0):   GW,   X,   X,   X,   X  k_id:0
Device 3 ethnet core(x= 0,y= 7) phys(x= 4,y= 0):   GW,   X,   X,   X,   X  k_id:0
Device 3 ethnet core(x= 0,y= 8) phys(x= 9,y= 6):  RED,   X,   X,   X,   X  k_id:0
Device 3 ethnet core(x= 0,y= 9) phys(x= 1,y= 6): NWID,   X,   X,   X,   X  k_id:41
Device 3 ethnet core(x= 0,y=10) phys(x= 8,y= 6):   GW,   X,   X,   X,   X  k_id:0
Device 3 ethnet core(x= 0,y=11) phys(x= 2,y= 6):   GW,   X,   X,   X,   X  k_id:0
Device 3 ethnet core(x= 0,y=12) phys(x= 7,y= 6):   GW,   X,   X,   X,   X  k_id:0
Device 3 ethnet core(x= 0,y=13) phys(x= 3,y= 6):   GW,   X,   X,   X,   X  k_id:0
Device 3 ethnet core(x= 0,y=14) phys(x= 6,y= 6): NSID,   X,   X,   X,   X  k_id:200
Device 3 ethnet core(x= 0,y=15) phys(x= 4,y= 6): NSID,   X,   X,   X,   X  k_id:198
k_id[0]: blank
k_id[37]: tt_metal/impl/dispatch/kernels/cq_prefetch.cpp
k_id[38]: tt_metal/impl/dispatch/kernels/cq_dispatch.cpp
k_id[39]: tt_metal/impl/dispatch/kernels/cq_prefetch.cpp
k_id[40]: tt_metal/impl/dispatch/kernels/packet_mux.cpp
k_id[41]: tt_metal/impl/dispatch/kernels/eth_tunneler.cpp
k_id[42]: tt_metal/impl/dispatch/kernels/packet_demux.cpp
k_id[43]: tt_metal/impl/dispatch/kernels/cq_dispatch.cpp
k_id[197]: tt_eager/tt_dnn/op_library/ccl/edm/erisc_datamover.cpp
k_id[198]: tt_eager/tt_dnn/op_library/ccl/edm/erisc_datamover.cpp
k_id[199]: tt_eager/tt_dnn/op_library/ccl/edm/erisc_datamover.cpp
k_id[200]: tt_eager/tt_dnn/op_library/ccl/edm/erisc_datamover.cpp
k_id[271]: tt_eager/tt_dnn/op_library/sharded/kernels/dataflow/reader_unary_sharded.cpp
k_id[272]: tt_eager/tt_dnn/op_library/sharded/kernels/dataflow/writer_unary_sharded_blocks_interleaved_start_id.cpp
k_id[442]: tt_eager/tt_dnn/op_library/eltwise_binary/kernels/dataflow/reader_binary_interleaved_start_id.cpp
k_id[443]: tt_eager/tt_dnn/kernels/dataflow/writer_unary_interleaved_start_id.cpp
k_id[444]: tt_metal/kernels/compute/eltwise_binary.cpp
```

**Comment by johanna-rock-tt** [comment] 2024-05-06 08:35
hey @tt-dma I just saw a reference to this issue in the multi chip tests script. I have some questions/comments:
(1) You are you referencing the `path models/demos/falcon40b/` in the earlier comments (as in `pytest models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]`). We moved everything to `models/demos/t3000/falcon40b`. Is this just a typo or was that the test you were running? Just want to make sure there's no old local copy of that code and you're using the wrong test/model implementation?
(2) We disabled the 4 chip tests, so pytest should actually skip those in tip of main now because we've been seeing this hang on ci ~2 weeks back. But there's already a PR that removes all the 4 chip code+tests because we don't want to support it anymore for simplicity and there's no use case for 4 chips now that 8 chip decode+prefill is functional or being optimized.

**Comment by davorchap** [comment] 2024-05-06 15:19
> hey [@tt-dma](https://github.com/tt-dma) I just saw a reference to this issue in the multi chip tests script. I have some questions/comments: (1) You are you referencing the `path models/demos/falcon40b/` in the earlier comments (as in `pytest models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]`). We moved everything to `models/demos/t3000/falcon40b`. Is this just a typo or was that the test you were running? Just want to make sure there's no old local copy of that code and you're using the wrong test/model implementation? (2) We disabled the 4 chip tests, so pytest should actually skip those in tip of main now because we've been seeing this hang on ci ~2 weeks back. But there's already a PR that removes all the 4 chip code+tests because we don't want to support it anymore for simplicity and there's no use case for 4 chips now that 8 chip decode+prefill is functional or being optimized.

@johanna-rock-tt the 2 specific test cases below should be working now, fixed by @ubcheema. Are you seeing another issue?

```
pytest models/demos/t3000/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-decode_batch32-4chips-enable_program_cache]

pytest models/demos/t3000/falcon40b/tests/test_falcon_end_to_end.py::test_FalconCausalLM_end_to_end_with_program_cache[BFLOAT8_B-SHARDED-falcon_40b-layers_1-decode_batch32-4chips-enable_program_cache]
```

**Comment by johanna-rock-tt** [comment] 2024-05-06 15:40
@davorchap so this issue is fixed then?

I was asking here, because all decode tests are commented in main with this issue id in a comment, so I'm a bit confused why/ what the current status is now:
https://github.com/tenstorrent/tt-metal/blob/674b5588dc0a3a65ff39d1c71cd898f055255b3a/tests/scripts/multi_chip/run_pre_post_commit_regressions_multi_device.sh#L29

But if the issue is fixed we can re-enable the tests in ci again, right?

**Comment by tt-dma** [comment] 2024-05-06 15:43
They should be fixed, but I guess we never re-enabled since it was fixed while FD2 was merging. I will re-enable and re-test now

**Comment by johanna-rock-tt** [comment] 2024-05-06 15:45
Also, in the commit disabling the tests some tests were removed rather than commented.
https://github.com/tenstorrent/tt-metal/commit/eeb8e0bc011514196f4291ab545273600d76cc30

Ultimately we'd like to have both 8 chip tests in there but not the 4 chip tests (they are skipped in the test files already anyway and will be removed in a PR soon).

**Comment by tt-dma** [comment] 2024-05-06 15:51
Looks like a merge conflict, I'll fix that on my branch

**Comment by tt-dma** [comment] 2024-05-06 15:55
PR here, waiting for test results: https://github.com/tenstorrent/tt-metal/pull/8167

**Comment by ubcheema** [comment] 2024-05-06 16:06
4-chip version of the model runs on mmio devices. 8 chip version pulls in the remote chips as well.
Do we have other test coverage to make sure 4 chip is working?
If there are issues on 8 chip, its a good fall back to check if it works on 4 chips.
But if it does not provide any coverage benefit or is hard to maintain, we can remove 4-chip version from the test list.

**Comment by johanna-rock-tt** [comment] 2024-05-06 16:14
We wanted to remove the 4 chip configs all together since there's no use case where we would actually run on 4 chips and not 8, especially since we have only decode working on 4 chips and not prefill - and it's extra effort to maintain and test every change also for the 4 chip version. So my tendency would be to keep it clean and easy to maintain. Let me know however if you see a clear benefit in the 4 chip version and think we should keep it anyway, or if pulling in the remote chips in addition to the pcie chips is causing issues sometimes.

**Comment by davorchap** [comment] 2024-05-06 18:24
the issue is fixed, both 4/8 chip variants are passing

**Closed by davorchap** 2024-05-06 18:24 UTC
Labels: P1_critical
