### ISSUE TITLE
incremental ci build processes

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#10878] opened 2024-07-30 03:42 UTC

**Comment by tt-rkim** [comment] 2024-08-14 13:28
Important issue where we can explore this on CI: https://github.com/tenstorrent/tt-metal/issues/11442

**Comment by TT-billteng** [comment] 2024-08-20 00:45
Is this a duplicate of #11442 ?

**Comment by tt-rkim** [comment] 2024-08-20 14:09
YA I guess so

**Closed by tt-rkim** 2024-08-20 14:09 UTC
Labels: infra-ci, feature-request, P2_should_have, cppbuild
