### ISSUE TITLE
Interleaved to sharded does not work correctly on BH when input sticks are 16 in ROW_MAJOR_LAYOUT

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#12184] opened 2024-09-03 20:38 UTC
Isolated the issue to `padded_offset_bytes = align(input_unit_size, input.buffer()->alignment());` in interleaved_to_sharded.

When input width is `16` (BFLOAT16, so 32b), in ROW_MAJOR_LAYOUT, the generated sharded output has alternating rows of 0s with the data, e.g.:
```
0: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
1: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
2: 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
3: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
4: 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
5: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
...
```

In this use case, the input unit size is 32b, and DRAM alignment on BH is 64b, so `padded_offset_bytes` is also 64, which is the increment value for the write ptr.

Branch: `asarje/debug-halo-bh`
Test: `pytest "tests/ttnn/unit_tests/operations/test_maxpool2d.py::test_run_max_pool[dtype=DataType.BFLOAT16-dilation=(1, 1)-stride=(2, 2)-padding=(1, 1)-kernel_size=(3, 3)-act_shape=[1, 16, 1056, 160]-device_params={'l1_small_size': 24576}]"`

**Comment by mywoodstock** [comment] 2024-09-26 22:19
@sjameelTT @tarafdarTT Hey guys, any update on the ETA for this?

**Comment by tarafdarTT** [comment] 2024-09-26 22:24
Mid next week

**Comment by mywoodstock** [comment] 2024-10-03 18:49
heya, any updates on this side? @ntarafdar

**Comment by ntarafdar** [comment] 2024-10-07 18:46
I think @jaykru-tt  has a fix for this

**Comment by mywoodstock** [comment] 2024-10-08 18:21
@jaykru-tt could you please point me to your fix commit? thanks

**Comment by ntarafdar** [comment] 2024-10-08 19:39
it was in a branch @jaykru-tt was working on but @yugaoTT has taken over. I have moved this issue to him for now. 
It's the same root cause where the ALIGNMENT is hardcoded.

**Comment by jaykru-tt** [comment] 2024-10-08 19:51
Here's the hash with the change @mywoodstock, but I didn't actually have much success using it for my case: 08c058d936cb135a0979129f5c94535f7a2252a6. Look for the change to `buffer.hpp`. YMMV, no warranties, etc.

**Comment by yugaoTT** [comment] 2024-10-08 22:54
this can be fixed from this issue:
https://github.com/tenstorrent/tt-metal/issues/13609

**Comment by yugaoTT** [comment] 2024-10-22 16:49
it seems using different alignment for L1 and DRAM will not work.
When DRAM addr is 32B aligned and L1 is 16B aligned, the NoC will ignore the first 16B datums, and only write the rest of datums. From watcher it also assert out invalid address alignment in NOC transaction.
We'll have to do re-align within the ops.
@mywoodstock could you try modify maxpool to use buffer.alignment(), and leave extra gaps between sticks

**Comment by mywoodstock** [comment] 2024-10-22 18:59
@yugaoTT Maxpool is just calling interleaved2sharded, so this needs to be updated in that op. cc: @ntarafdar

**Comment by mywoodstock** [comment] 2024-10-31 18:13
@ntarafdar is this issue assignment to @yugaoTT correct?

**Comment by yugaoTT** [comment] 2024-10-31 18:53
I believe @ntarafdar (pls correct me if I'm wrong) will take over the alignment related issues.

**Comment by ntarafdar** [comment] 2024-11-01 16:54
will need to sync with @mywoodstock how to recreate this because I see it working on my end :(

**Comment by ntarafdar** [comment] 2024-11-03 17:22
I have it working in my branch

```
expected_pytorch_result = tensor([[[[     1.461,      1.594,      0.574,      2.375,      1.492,      1.367,      1.586,      2.031,      1.094,....000, 48103633715200.000, 422785843
0, 1635778560.000, -1429622665712490250240.000]]]],
       dtype=torch.bfloat16)
actual_pytorch_result = tensor([[[[     1.461,      1.570,      1.594,      1.594,      0.574,      1.883,      2.375,      2.375,      1.492,...   2.516,      1.344,      1.336,    
531,      1.531,      1.383,      1.383,      0.898]]]], dtype=torch.bfloat16)
pcc = 0.9999

```


I have to add support to the sharded_to_interleaved side as currently sharded to interleaved is expecting the 0 padding , which is why in loopback tests it was "working" as both wrongs hid each other.

If you need this now you can cherry pick my commit for max pool otherwise I should have this by eod Monday

**Comment by ntarafdar** [comment] 2024-11-18 16:56
@llongTT I pushed a change that I thought would fix this, @mywoodstock says it does not. He is going to help us narrow it down, but after this we will have to look at this.
This is the top priority issue so after he gets more info on this we'll have to fix it. 

We will talk about this issue, and you can even help @mywoodstock narrow it down as he is also in the Santa Clara office as well

**Comment by mywoodstock** [comment] 2024-11-22 17:09
We can close this ticket, we are tracking the remainder issue here: https://github.com/tenstorrent/tt-metal/issues/15238

**Closed** 2024-11-27 19:36 UTC
Labels: P0, blackhole
