### ISSUE TITLE
Llama2-70B Prefill on 2K sequence Length Non-deterministic Hang on Decoder Unit Test

### ISSUE THREAD

**Issue by avoraTT** [tenstorrent/tt-metal#8959] opened 2024-05-29 21:42 UTC
**Describe the bug**
We experience a non-deterministic hang when running llama2-70B with 1 prefill iteration, 1 decoder layer, and 2k sequence length on the following unit test: `models/experimental/llama2_70b/tests/test_llama_decoder.py::test_LlamaDecoder_inference[wormhole_b0-True-prefill_2k-8chip-T3000]` on device `sjc-snva-t3010`.

We followed the watcher guide provided here: https://github.com/tenstorrent/tt-metal/blob/main/CONTRIBUTING.md#debugging-guide . The results from the watcher log are attached.

```
k_id[0]: blank
k_id[44]: tt_metal/impl/dispatch/kernels/eth_tunneler.cpp
k_id[45]: tt_metal/impl/dispatch/kernels/packet_demux.cpp
k_id[46]: tt_metal/impl/dispatch/kernels/cq_prefetch.cpp
k_id[47]: tt_metal/impl/dispatch/kernels/cq_dispatch.cpp
k_id[48]: tt_metal/impl/dispatch/kernels/packet_mux.cpp
k_id[301]: tt_eager/tt_dnn/op_library/ccl/edm/erisc_datamover.cpp
k_id[302]: tt_eager/tt_dnn/op_library/ccl/edm/erisc_datamover.cpp
k_id[995]: tt_eager/tt_dnn/op_library/eltwise_binary/kernels/dataflow/reader_binary_interleaved_start_id.cpp
k_id[996]: tt_eager/tt_dnn/kernels/dataflow/writer_unary_interleaved_start_id.cpp
k_id[997]: tt_metal/kernels/compute/eltwise_binary.cpp
```
Log files: 

[0529_main_prefill2k_noSDPA_kernel_names.txt](https://github.com/tenstorrent/tt-metal/files/15491085/0529_main_prefill2k_noSDPA_kernel_names.txt)
[0529_main_prefill2k_noSDPA_watcher.log](https://github.com/tenstorrent/tt-metal/files/15491086/0529_main_prefill2k_noSDPA_watcher.log)

**To Reproduce**
1. Device: T3000
2. Pull from latest main (https://github.com/tenstorrent/tt-metal/tree/aaade6845d0dd107d24602a4c3a64831ef083069)
3. build tt_metal
4. run 
```
pytest -svv models/experimental/llama2_70b/tests/test_llama_decoder.py::test_LlamaDecoder_inference[wormhole_b0-True-prefill_2k-8chip-T3000]
```

**Comment by pavlepopovic** [comment] 2024-05-30 08:01
This could potentially be di/dt issue. Hence adding the appropriate label. @ttmtrajkovic fyi in case this gets confirmed.
We've had a bunch of those on falcon7b/40b prefills, especially on T3000 and N300.
Here's a bunch of those issues:
https://github.com/tenstorrent/tt-metal/issues/8665
https://github.com/tenstorrent/tt-metal/issues/8644
https://github.com/tenstorrent/tt-metal/issues/7560

What usually happens is we have matmuls running over entire grid, those tend to cause ND hangs/seg faults on WH.
We've had those in attention, MLP and LM head matmuls.
What we usually do is find the module where the hang is happening, and isolate problematic matmuls in a unit test, so they can be debugged further.
Workaround for these problematic matmuls seems to be the following:

1. Set the subblock_h/w on them to 1, 1. This usually gets rid of the problem.
2. If that doesn't work, reduce the grid size of the matmul to 56 (instead of 64).

So far we were able to workaround our issues by using 1) and 2) where necessary

**Comment by caixunshiren** [comment] 2024-05-30 16:30
> This could potentially be di/dt issue. Hence adding the appropriate label. @ttmtrajkovic fyi in case this gets confirmed. We've had a bunch of those on falcon7b/40b prefills, especially on T3000 and N300. Here's a bunch of those issues: #8665 #8644 #7560
> 
> What usually happens is we have matmuls running over entire grid, those tend to cause ND hangs/seg faults on WH. We've had those in attention, MLP and LM head matmuls. What we usually do is find the module where the hang is happening, and isolate problematic matmuls in a unit test, so they can be debugged further. Workaround for these problematic matmuls seems to be the following:
> 
> 1. Set the subblock_h/w on them to 1, 1. This usually gets rid of the problem.
> 2. If that doesn't work, reduce the grid size of the matmul to 56 (instead of 64).
> 
> So far we were able to workaround our issues by using 1) and 2) where necessary

Can confirm no hang observed after applying both 1 and 2 on a branch with sdpa on one machine. Trying on the other machine

**Comment by avoraTT** [comment] 2024-05-30 21:45
Tried to repro this issue on a new machine (`sjc-snva-t3002`). Takeaways
- With watcher turned off, after running the test continuously for >100 iterations (~40 min), there were **no hangs**
- With watcher turned on, tester always hangs on `ring_gather`

Tried to repro again on `sjc-snva-t3010` and issue **still persists** with and without watcher.

**Comment by uaydonat** [comment] 2024-06-05 01:38
to clarify, we still get a hang without the watcher even if we reduce subblock size and grid size?

**Comment by uaydonat** [comment] 2024-06-05 14:31
Amar: "So on the t3010, even with small grid/block size we would get a hang on prefill tests when creating layers. The workaround was to just reset the boards until the test would pass. This hang was only found on this machine so colman has put in a request to swap out the boards on it"

**Comment by cglagovichTT** [comment] 2024-07-10 15:34
Closing - after replacing the N300s in sjc-snva-t3010, we cannot repro hangs in stress tests.

**Closed by cglagovichTT** 2024-07-10 15:34 UTC
Labels: bug, P1_critical, LLM_bug, LLMs on Metal, llama2-70b, prefill, didt_suspected
