### ISSUE TITLE
segformer_b0: Runtime error: ttnn.permute fails for input with odd number at last dimension

### ISSUE THREAD

**Issue by HariniMohan0102** [tenstorrent/tt-metal#9009] opened 2024-05-31 13:47 UTC
**Describe the bug**
The runtime error in the permute operation occurs when the tensor, initially with a shape of [256, 32, 1], is permuted with following dimensions (0, 2, 1). The Permute operation expects the last dimension to be divisible by 2. 

**To Reproduce**
Copy paste the following code and run it.
```
import ttnn
import pytest
import torch
@pytest.mark.parametrize("device_params", [{"l1_small_size": 24576}], indirect=True)
def test_permute(device):
    a=torch.randn(256,32,1)
    ttnn_a=ttnn.from_torch(a,device=device,layout=ttnn.TILE_LAYOUT,dtype=ttnn.bfloat16)
    output=ttnn.permute(ttnn_a,(0,2,1))
```

**Expected behavior**
Expected to permute without any error.

**Screenshots**
We face the following error when we run the above code snippet.
`>       output=ttnn.permute(ttnn_a,(0,2,1))
E       RuntimeError: TT_FATAL @ ../tt_metal/impl/buffers/buffer.cpp:42: page_size % sizeof(uint32_t) == 0
E       info:
E       Page size must be divisible by sizeof(uint32_t) because buffers hold uint32_t values
E       backtrace:
E        --- tt::tt_metal::validate_buffer_size_and_page_size(unsigned long, unsigned long, tt::tt_metal::BufferType const&, tt::tt_metal::TensorMemoryLayout const&, std::optional<tt::tt_metal::ShardSpecBuffer> const&)
E        --- tt::tt_metal::Buffer::Buffer(tt::tt_metal::Device*, unsigned long, unsigned long, tt::tt_metal::BufferType, tt::tt_metal::TensorMemoryLayout, std::optional<tt::tt_metal::ShardSpecBuffer> const&, bool)
E        --- tt::tt_metal::tensor_impl::detail::allocate_interleaved_buffer_on_device(unsigned int, tt::tt_metal::Device*, tt::tt_metal::Shape const&, tt::tt_metal::DataType, tt::tt_metal::Layout, tt::tt_metal::MemoryConfig const&)
E        --- tt::tt_metal::tensor_impl::allocate_buffer_on_device(unsigned int, tt::tt_metal::Device*, tt::tt_metal::Shape const&, tt::tt_metal::DataType, tt::tt_metal::Layout, tt::tt_metal::MemoryConfig const&, std::optional<tt::tt_metal::ShardSpecBuffer> const&)`

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: GS, WH-n150

**Comment by mywoodstock** [comment] 2024-07-24 18:34
@dvartaniansTT @HariniMohan0102  This is not a bug, it is a hard requirement that the last dim be multiple of 2 as displayed in the error message.

**Comment by dvartaniansTT** [comment] 2024-07-25 00:20
yah, that's right. @mywoodstock . so should we pad with zeros then permute?

**Comment by mywoodstock** [comment] 2024-07-25 00:21
Correct, pad and then permute.

**Comment by dvartaniansTT** [comment] 2024-07-25 00:28
@HariniMohan0102 please see the comments, try to pad and then permute. then unpad the zeros. update the issues once you get it working and we can close this.

**Comment by punithsekar** [comment] 2024-07-25 11:34
Sure @dvartaniansTT , I will check and update here. 
cc: @HariniMohan0102

**Comment by punithsekar** [comment] 2024-08-08 09:01
Will check this while porting the model to n150 device.

**Comment by mywoodstock** [comment] 2024-08-15 23:54
@HariniMohan0102 @punithsekar Assigning back to you

**Comment by mbahnasTT** [comment] 2024-08-28 05:49
@punithsekar @saichandax can you give updates on this issue?

**Comment by saichandax** [comment] 2024-08-28 16:16
We need to try this. We'll check and update you on this @mbahnasTT

**Closed** 2024-08-30 10:26 UTC
Labels: bug, P1_critical, op_cat: misc, Customer_Bug, segformer_b0
