### ISSUE TITLE
Falcon40b decode hang if prefill on device

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent/tt-metal#7836] opened 2024-04-25 15:34 UTC
[Updated] 

Here is what I am observing on the latest main (8f3e70e2830b817cde040adef6417921e205d765):
- prefill on device with Bfp8 -> hang in the decode
- prefill on device with Float16 -> RuntimeError: Problem getting initial line from hexfile stream. It may be reading a file that doesn't exist or ulimit -n too low. (this might be a regression after the attention changes since demo worked with FP16 yesterday)

Prefill on host gives normal output.

**Comment by s-jovic** [comment] 2024-04-26 18:29
cc @skhorasganiTT @johanna-rock-tt @pavlejosipovic I will be off next week, so tagging you guys to be aware of the current status

**Comment by skhorasganiTT** [comment] 2024-04-30 20:32
Results from investigating this hang with different [Falcon40b commits from April 26](https://github.com/tenstorrent/tt-metal/commits/main/models/demos/falcon40b):
On [commit fbf8aae](https://github.com/tenstorrent/tt-metal/commit/fbf8aae463145d161dd7d7489783eb6f2475c6f9): Demo did not hang after 50 runs
On [commit 6d1ba2b](https://github.com/tenstorrent/tt-metal/commit/6d1ba2b9242ebfa097a69e913c17a142293ddef0): Demo hung after 32 runs
On [commit 793d842](https://github.com/tenstorrent/tt-metal/commit/793d842a31d876fef233a39f2137ce8cf4a02be9): Demo hang after 6 runs

Since the last two of these commits modified compute kernel configs, it is possible that this is timing related and could overlap with #7066 and #6795.

**Comment by skhorasganiTT** [comment] 2024-05-01 18:15
I am longer seeing this hang (ran demo 100 times) after updating to the new firmware (bundle version 80.4.0.0 - details: https://github.com/tenstorrent/tt-metal/issues/4968#issuecomment-2087318566) running at 1GHz (made available in 13193c1247a8713b9bd77e4856fe97cf14d89202).

**Comment by skhorasganiTT** [comment] 2024-05-06 19:23
Closing this issue as I have not seen any more demo hangs since the last update (last commit checked: 12ad5a528)
Command tested:
`WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest --disable-warnings -q -s --input-method=cli --cli-input="How do I get better at piano"  models/demos/t3000/falcon40b/demo/demo.py`

**Comment by uaydonat** [comment] 2024-05-06 20:47
@johanna-rock-tt is this hanging with FD2 on main?

**Comment by johanna-rock-tt** [comment] 2024-05-07 08:05
Yes, I've been a hang for the demo yesterday. @skhorasganiTT how often did you run it? Unfortunately I can't test it now because my machine is still in a bad state. Will update once I have it back.

**Comment by johanna-rock-tt** [comment] 2024-05-07 13:48
That's the ci ran from yesterday where the demo hung at the first token decode iteration: https://github.com/tenstorrent/tt-metal/actions/runs/8967693679/job/24625680892#step:7:11266

**Comment by johanna-rock-tt** [comment] 2024-05-08 14:53
I deterministically hang with this test/input:
`pytest --disable-warnings -q -s --input-method=cli --cli-input="Tell me a joke." models/demos/t3000/falcon40b/demo/demo.py`

**Comment by johanna-rock-tt** [comment] 2024-05-08 15:08
Unlike the original bug description this also hangs with prefill on host. So it seems to be a decode only hang. However dependent on the input prompt.

**Comment by jliangTT** [comment] 2024-05-08 16:15
Re-opening based on the issue comment that this still repro. Are we able to follow these steps to narrow things down: 

  1. try op by op by blocking ops (try to make a op-only repro) 
  2. try to enable the watcher (navigate with watcher setting)

**Comment by johanna-rock-tt** [comment] 2024-05-08 16:49
@skhorasganiTT and I are working on reproducing this. I might have had a bad machine/build state. We'll comment here as soon as we confirmed whether the hang is still there or not.

**Comment by skhorasganiTT** [comment] 2024-05-09 17:20
The local deterministic hang that Johanna was seeing was due to a bad `built` (compiled kernels) state (removing that directory made the hang go away), and the CI failure that was posted was due to using an older commit than the one I last posted as passing. Johanna and I re-ran the demo tests on CI (passed 15 times) and we are no longer able to reproduce so I am closing this issue.

**Closed by skhorasganiTT** 2024-05-09 17:20 UTC
Labels: bug, P1_critical, falcon_40b, LLM_bug, LLMs on Metal

**Comment by johanna-rock-tt** [comment] 2024-05-22 15:14
I just checked, it was on. I'm gonna disable it for all our tests.

**Comment by skhorasganiTT** [comment] 2024-05-22 15:57
Persistent cache is required for inference perf, we shouldn't disable it. Also, I believe the metal team is considering removing the option to disable it as it should always be on.

**Comment by johanna-rock-tt** [comment] 2024-05-22 16:02
Are you talking about the _program cache_? It's two different types of caches.
Apparently the _persistent kernel cache_ caches the compiled kernels over multiple runs and stores that in the built directory, the suspicion is that that's the reason why we sometimes need to remove the built directory after rebasing to get rid of hangs. Perf after the first iteration should not be impacted by this as far as I understood.

**Comment by skhorasganiTT** [comment] 2024-05-22 16:29
I was talking about the persistent kernel cache (which is independent of program cache). Previously, it was my understanding that if the persistent kernel cache is disabled, the kernel binaries would need to be recompiled every time. However, I just spoke to @aliuTT and I think that is now no longer the case. Disabling it will result in not saving to disk (to `built`), but still save to RAM, and increase the time for the compile run each time the test is run (but not for the subsequent inference run in the same test). So I believe you're right, it should be okay to disable if the increase in compile run time is acceptable.

**Comment by aliuTT** [comment] 2024-05-22 16:32
Both correct

**Comment by uaydonat** [comment] 2024-05-22 21:31
@skhorasganiTT points out that the `built` directory is specific to persistent_cache and the fact that the hang does not occur when we delete it means that the hang was due to the persistent_cache. No action to take for now.
