### ISSUE TITLE
[Bug Report] TTNN Embedding op (ttnn.embedding) fails when configured as tile layout

### ISSUE THREAD

**Issue by nvukobratTT** [tenstorrent/tt-metal#12644] opened 2024-09-13 14:42 UTC
**Describe the bug**
Embedding op (ttnn.embedding) fails on implicit reshape when TILE_LAYOUT is used. 

For more context, here is the exact error message:
```
Unable to reshape a tensor in TILE_LAYOUT to non-tile height and width! Please convert the tensor to ROW_MAJOR_LAYOUT first.
```

**To Reproduce**
For full repro, you can use the following code:
```py
import pytest
import torch
import ttnn
from tests.ttnn.utils_for_testing import assert_with_pcc
from models.utility_functions import torch_random


def test_embedding_llama3_tile(device):
    torch.manual_seed(1234)

    # Create Torch Input tensor(1, 12) and weight tensor(32000, 3200) and Run the torch.nn.functional.embedding op inference
    torch_input_tensor = torch.randint(0, 32000, (1, 12)).to(torch.int32)
    torch_weights = torch_random((32000, 3200), -0.1, 0.1, dtype=torch.bfloat16)
    torch_output_tensor = torch.nn.functional.embedding(torch_input_tensor, torch_weights)

    # Create Torch Input tensor(1, 12) and weight tensor(32000, 3200) and Run the ttnn.embedding op inference
    input_tensor = ttnn.to_device(
        ttnn.from_torch(torch_input_tensor, dtype=ttnn.uint32, layout=ttnn.TILE_LAYOUT),
        device,
        memory_config=ttnn.DRAM_MEMORY_CONFIG,
    )
    weights = ttnn.to_device(
        ttnn.from_torch(torch_weights, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT),
        device,
        memory_config=ttnn.DRAM_MEMORY_CONFIG,
    )
    output_tensor = ttnn.embedding(input_tensor, weights, memory_config=ttnn.DRAM_MEMORY_CONFIG)

    # Convert ttnn to torch tensor
    output_tensor = ttnn.to_torch(output_tensor)

    assert_with_pcc(torch_output_tensor, output_tensor)

```

Note: ROW_MAJOR_LAYOUT will pass successfully. E.g.
```py
import pytest
import torch
import ttnn
from tests.ttnn.utils_for_testing import assert_with_pcc
from models.utility_functions import torch_random


def test_embedding_llama3_row_major(device):
    torch.manual_seed(1234)

    # Create Torch Input tensor(1, 12) and weight tensor(32000, 3200) and Run the torch.nn.functional.embedding op inference
    torch_input_tensor = torch.randint(0, 32000, (1, 12)).to(torch.int32)
    torch_weights = torch_random((32000, 3200), -0.1, 0.1, dtype=torch.bfloat16)
    torch_output_tensor = torch.nn.functional.embedding(torch_input_tensor, torch_weights)

    # Create Torch Input tensor(1, 12) and weight tensor(32000, 3200) and Run the ttnn.embedding op inference
    input_tensor = ttnn.to_device(
        ttnn.from_torch(torch_input_tensor, dtype=ttnn.uint32, layout=ttnn.ROW_MAJOR_LAYOUT),
        device,
        memory_config=ttnn.DRAM_MEMORY_CONFIG,
    )
    weights = ttnn.to_device(
        ttnn.from_torch(torch_weights, dtype=ttnn.bfloat16, layout=ttnn.ROW_MAJOR_LAYOUT),
        device,
        memory_config=ttnn.DRAM_MEMORY_CONFIG,
    )
    output_tensor = ttnn.embedding(input_tensor, weights, memory_config=ttnn.DRAM_MEMORY_CONFIG)

    # Convert ttnn to torch tensor
    output_tensor = ttnn.to_torch(output_tensor)

    # PCC check
    assert_with_pcc(torch_output_tensor, output_tensor)
```

**Expected behavior**
The embedding op is passed on to the tile layout as well.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 22.04]
- Version of the software, commit SHA: e51f5f77a302ea061b3cf7376f5bec148d82b922

**Comment by tt-mpantic** [comment] 2024-09-19 17:22
Seems to be duplicate of [12866](https://github.com/tenstorrent/tt-metal/issues/12866)

**Comment by nvukobratTT** [comment] 2024-09-20 08:28
> Seems to be duplicate of [12866](https://github.com/tenstorrent/tt-metal/issues/12866)

Should be the same issue due to the implicit reshaping that is happening as part of the ttnn.embedding op. 

@tarafdarTT if you agree and there aren't any other specificities of embedding next to this reshape, we can close this one and track mainly this issue https://github.com/tenstorrent/tt-metal/issues/12866 :))

**Comment by ntarafdar** [comment] 2024-09-27 18:38
solved here: https://github.com/tenstorrent/tt-metal/pull/13022
will merge soon

**Comment by nvukobratTT** [comment] 2024-09-27 18:52
> solved here: https://github.com/tenstorrent/tt-metal/pull/13022
> will merge soon

Thanks for the quick push! :))

**Comment by ntarafdar** [comment] 2024-10-07 15:53
should be merged in. Let me know if main isn't working for your case.

**Closed by ntarafdar** 2024-10-07 15:53 UTC
Labels: bug, P0_Showstopper, forge
