### ISSUE TITLE
ttnn.lerp operation does not work with mixed precision

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent/tt-metal#13625] opened 2024-10-09 08:05 UTC
(Ternary) operation ttnn.lerp does not work when input tensors are in different precessions. Eg. When first input tensor is bfloat16 and second tensor is bfloat8_b.

We are getting messages similar to:

```
expected dtype c10::BFloat16 for `weight` but got dtype float
expected dtype c10::BFloat16 for `end` but got dtype float
```

Steps to reproduce

On branch `ngrujic/unit-tests-1` (soon to be merged into main), there is unit test `tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_eltwise_lerp.py`, which can be run with:

```
pytest  tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_eltwise_lerp.py
```

You can reproduce this error with sweep test `tests/sweep_framework/sweeps/eltwise/ternary/lerp/lerp.py`. To run:

```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.ternary.lerp.lerp
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.ternary.lerp.lerp
```

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

**Comment by umadevimcw** [comment] 2024-11-13 10:01
@nemanjagrujic @amalbasaTT Please provide a unit test for this issue

**Comment by nemanjagrujic** [comment] 2024-11-13 13:27
@umadevimcw , I updated instructions.

**Comment by umadevimcw** [comment] 2024-11-15 10:00
@eyonland  @nemanjagrujic The issue is in the dtype of tensors passed to torch.lerp call. 

Torch lerp op needs end and weight tensors to be of same dtype as input dtype. An error was thrown from torch call. Hence updated the golden function accordingly. Please find the image below. 

![Image](https://github.com/user-attachments/assets/59d996e6-8dc6-4328-9bd6-1f8d9e16eee4)


PR: #15085

**Comment by umadevimcw** [comment] 2024-11-19 08:36
Merged to main

**Closed** 2024-11-19 08:36 UTC
Labels: bug, op_cat: eltwise
