### ISSUE TITLE
ttnn.deallocate causes bad PCC / L1 overwrites during subsequent sharded_to_interleaved

### ISSUE THREAD

**Issue by yieldthought** [tenstorrent/tt-metal#14902] opened 2024-11-08 16:49 UTC
**Describe the bug**
Our accuracy test of llama 3.1 8b on T3K has 0.0 accuracy when a tensor that is no longer used is deallocated. The proximate cause of the bad accuracy is the corruption of other tensors in L1 (in our case the residual tensor `h`) during the MLP module, which does not normally even get passed the `h` tensor. This corruption occurs during a `sharded_to_interleaved` call following the DRAM-sharded matmuls.

**To Reproduce**
1. Get a T3k
2. Copy the Llama 3.1 8B weights from `sjc-snva-t3002:/proj_sw/user_dev/llama31-8b-data/Meta-Llama-3.1-8B-Instruct/`
3. Check out `yieldthought/memory-corruption` branch and build
4. `LLAMA_DIR=/proj_sw/user_dev/llama31-8b-data/Meta-Llama-3.1-8B-Instruct pytest models/demos/llama3/tests/test_llama_accuracy.py`

Test asserts showing that h was corrupted during sharded_to_interleaved:

```
first_five_before=tensor([ 0.0106, -0.0006, -0.0012,  0.0080, -0.0243], dtype=torch.bfloat16)
first_five_after=tensor([0., 0., 0., 0., 0.], dtype=torch.bfloat16)
...
        if mode == "decode":
            if debug_tensor is not None:
                first_five_before = first_five(debug_tensor, self.mesh_device)
            w2_out = ttnn.sharded_to_interleaved(
                w2_out, ttnn.L1_MEMORY_CONFIG
            )  # NOTE: writing this out to DRAM interleaved avoids corrupting h!
            if debug_tensor is not None:
                first_five_after = first_five(debug_tensor, self.mesh_device)
                if not torch.allclose(first_five_before, first_five_after):
                    print(f'{first_five_before=}')
                    print(f'{first_five_after=}')
>                   assert False, "h was corrupted during sharded_to_interleaved"
E                   AssertionError: h was corrupted during sharded_to_interleaved
```

**Expected behavior**
Test passes with 88-90% top-1 accuracy. This can be obtained by commenting out the deallocate on line 114 of llama_decoder.py:
```
ttnn.deallocate(attn_out) # NOTE: Commenting out this deallocate avoids the bad output
```

**Please complete the following environment information:**
Internal ird t3k, I used sjc-snva-t3002

**Additional context**

**Comment by yieldthought** [comment] 2024-11-08 16:54
@mtairum for visibility - I think this is related to the ND issues we were seeing, but this one happens every time.

**Comment by yieldthought** [comment] 2024-11-11 10:24
FWIW using `ttnn.to_memory_config` has the same effect as `ttnn.sharded_to_interleaved` here.

**Comment by yieldthought** [comment] 2024-11-12 10:06
Escalating to P1, this is on the critical path to delivering llama 3.2 to the customer team; we need to use L1 to hit our performance targets.

**Comment by ntarafdar** [comment] 2024-11-12 16:20
@yieldthought , @jvegaTT is looking at this now.

**Comment by jvegaTT** [comment] 2024-11-12 20:24
There is a failure pattern to the output tensor. 1024 bytes of mostly 0s with some very large float numbers interleaved, then 1024 bytes of the correct output data, then this pattern repeats throughout entire output tensor. Currently debugging why that may be the case.

**Comment by yieldthought** [comment] 2024-11-13 16:31
I've confirmed that modifying the dram-sharded matmuls to shard over 8 cores in this example and thus avoiding any padding removes the error and allows the test to complete successfully. This seems to confirm that the dram-sharded matmul's missing padding implementation is the root cause here.

**Comment by jvegaTT** [comment] 2024-11-13 16:32
Immediately preceding the deallocate is a call to ttnn::Linear. The outputs from ttnn::Linear are the inputs to sharded_to_interleved and the inputs to ttnn::Linear are what are being deallocated. Function succeeds a few times before failing (it produces the correct results in the earlier runs) and the failure mode of alternating correct data and garbage both of consistent sizes in every test can definitely be caused by an upstream padding issue. I have confirmed for instance that when it fails all the buffers are allocated correctly, of the right sizes, and when it fails there isn't any overflow happening caused by this OP.

It is suspected that correcting #15004 will automatically fix this issue, re-assigning it to Yu Gao who is investigating #15004

As further confirmation if using an 8-core grid with no need for padding in the mammals the test passes

**Comment by yugaoTT** [comment] 2024-11-15 19:23
It turns out it's the s2i op causing L1 errors, fix is here https://github.com/tenstorrent/tt-metal/pull/15113

**Comment by yugaoTT** [comment] 2024-11-26 21:56
can we close if this is resolved?

**Closed** 2024-11-27 10:33 UTC
Labels: bug, ttnn, P1, LLM_bug, llama3
