### ISSUE TITLE
WH PCC error for `test_moreh_linear.py::test_moreh_linear_backward` w/ Watcher Enabled

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#5868] opened 2024-03-01 02:06 UTC
`TT_METAL_WATCHER=30 pytest tests/tt_eager/python_api_testing/unit_testing/test_moreh_linear.py::test_moreh_linear_backward`

Failure is a PCC error:

```
            passing, output_pcc = comp_allclose_and_pcc(torch_bias.grad, ttcpu_bias_grad, pcc=0.999, rtol=rtol, atol=atol)
            logger.info(f"bias_grad passing={passing} pcc={output_pcc}")
>           assert passing
E           assert False

tests/tt_eager/python_api_testing/unit_testing/test_moreh_linear.py:164: AssertionError
```

**Comment by jliangTT** [comment] 2024-03-02 01:04
@razorback3 , can you take a look?

**Comment by razorback3** [comment] 2024-03-02 01:48
@dongjin-na

**Comment by dongjin-na** [comment] 2024-03-02 07:50
The problem is not reproduced on my setup.

```bash
TT_METAL_WATCHER=30 pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_linear.py::test_moreh_linear_backward

......

PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_linear.py::test_moreh_linear_backward[False-requires_grads2-shapes11]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_linear.py::test_moreh_linear_backward[False-requires_grads2-shapes12]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_linear.py::test_moreh_linear_backward[False-requires_grads2-shapes13]
===================================================================================================================== 84 passed in 31.88s =====================================================================================================================
                 Device | INFO     | Closing user mode device drivers
^C
```

**Comment by razorback3** [comment] 2024-03-03 14:02
> The problem is not reproduced on my setup.
> 
> ```shell
> TT_METAL_WATCHER=30 pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_linear.py::test_moreh_linear_backward
> 
> ......
> 
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_linear.py::test_moreh_linear_backward[False-requires_grads2-shapes11]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_linear.py::test_moreh_linear_backward[False-requires_grads2-shapes12]
> PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_linear.py::test_moreh_linear_backward[False-requires_grads2-shapes13]
> ===================================================================================================================== 84 passed in 31.88s =====================================================================================================================
>                  Device | INFO     | Closing user mode device drivers
> ^C
> ```

@dongjin-na Is this result produced using WH B0 (n300) ?




> `TT_METAL_WATCHER=30 pytest tests/tt_eager/python_api_testing/unit_testing/test_moreh_linear.py::test_moreh_linear_backward`
> 
> Failure is a PCC error:
> 
> ```
>             passing, output_pcc = comp_allclose_and_pcc(torch_bias.grad, ttcpu_bias_grad, pcc=0.999, rtol=rtol, atol=atol)
>             logger.info(f"bias_grad passing={passing} pcc={output_pcc}")
> >           assert passing
> E           assert False
> 
> tests/tt_eager/python_api_testing/unit_testing/test_moreh_linear.py:164: AssertionError
> ```

@TT-billteng May I ask you to check it again? If it still happens, can you tell us your test environment?

**Comment by dongjin-na** [comment] 2024-03-03 14:13
> @dongjin-na Is this result produced using WH B0 (n300) ?

Yes, tested on the WH_B0 cloud VM (172.27.44.100).

**Comment by dongjin-na** [comment] 2024-03-06 14:17
@TT-billteng,
I reproduced that issue. 
The issue doesn't occur always but appears occasionally.
It can occur without Watcher mode, but the frequency of occurrence is shallow.

Based on the abnormal results when the issue occurs, it seems like the calculations are incorrect somewhere.
So I guess the issue appears to be related to timing, but when I enable debug prints for further investigation, the problem does not reproduce, making debugging challenging. 

Is it possible to get support to debug this issue?
https://github.com/tenstorrent-metal/tt-metal/blob/2804e099ef4bcc6b6e8d4d875f0aa1eba9f1fb63/tt_eager/tt_dnn/op_library/moreh_linear_backward/kernels/moreh_bias_backward_single_core_hw.cpp

**Comment by TT-billteng** [comment] 2024-03-06 14:43
Thanks for the investigation @dongjin-na @razorback3 . @jliangTT @jvasilje can you find someone that can help with debug?

**Comment by jliangTT** [comment] 2024-04-10 18:31
Hi @tt-dma , would you mind taking a look? it may not be watcher issue but might need input.

**Comment by jliangTT** [comment] 2024-04-23 17:52
hey @dongjin-na , can you please go to this page https://tenstorrent.github.io/tt-metal/latest/tt-metalium/tools/watcher.html#enabling and enable watcher piece-wise to see if you can still reproduce?

**Comment by dongjin-na** [comment] 2024-04-24 07:30
Dear @jliangTT , I can reproduce that issue.

It appears that a problem occurs when copy_tile is executed more than once in the ACQ and REL sections in WATCHER mode. 

https://github.com/tenstorrent/tt-metal/blob/5a81404b806644f6a4d9caa80b6d681ac0542bd4/tt_eager/tt_dnn/op_library/moreh_linear_backward/kernels/moreh_bias_backward_single_core_hw.cpp#L57-L80


Detailed examples will be added at https://github.com/tenstorrent/tt-metal/issues/7521 by @hschoi4448 .

**Comment by dongjin-na** [comment] 2024-04-24 14:02
When I modify the kernel to use `tile_regs_*` functions instead of` acquire_dst` and `release_dst`, the issue is not reproduced.

**Comment by jliangTT** [comment] 2024-04-24 14:48
@tt-dma , @pgkeller , want to get your feedback on the next step: need to be investigated by runtime team right? 

btw.. @dongjin-na , are there coverage for this test case w/o watcher enabled at the moment?

**Comment by jliangTT** [comment] 2024-04-24 15:03
Actually, @dongjin-na , if you can reproduce with watcher, i would expect it to produce better log. What does the watcher output when you can reproduce? maybe it will lead more actionable debug next step

**Comment by dongjin-na** [comment] 2024-04-25 01:25
> are there coverage for this test case w/o watcher enabled at the moment?

I looped over this failed case 1000 times in each case.
```
@pytest.mark.parametrize(
    "shapes",
    (
        # input, weight, bias(1d or scalar), output
        ([1, 1, 1, 31], [1, 1, 30, 31], [1, 1, 1, 30], [1, 1, 1, 30]),
        ([1, 1, 1, 31], [1, 1, 30, 31], [1, 1, 1, 1], [1, 1, 1, 30]),
        ([1, 1, 31, 31], [1, 1, 30, 31], [1, 1, 1, 30], [1, 1, 31, 30]),
        # ......
        ([1, 1, 32, 1023], [1, 1, 1536, 1023], [1, 1, 1, 1], [1, 1, 32, 1536]),
        ([2, 4, 4, 1024], [1, 1, 1536, 1024], [1, 1, 1, 1536], [2, 4, 4, 1536]),
        # TODO: Check this case with 1300 -> 1536
        ([2, 4, 4, 1024], [1, 1, 1300, 1024], [1, 1, 1, 1], [2, 4, 4, 1300]), # <-------- failed case
    ),
)
```

watcher mode | ACQ_REL(acquire_dst, release_dst) | TILE_REGS(tile_regs_*)
-- | -- | --
off | passed | passed
on | failed | passed

Here's the compute kernel code.
```
// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
//
// SPDX-License-Identifier: Apache-2.0

#include <cstdint>

#include "compute_kernel_api/eltwise_binary.h"
#include "compute_kernel_api/mask.h"
#include "compute_kernel_api/reduce.h"
#include "compute_kernel_api/tile_move_copy.h"

ALWI void ACQ() { acquire_dst(tt::DstMode::Full); }
ALWI void REL() { release_dst(tt::DstMode::Full); }

#define ACQ_REL 1
#define TILE_REGS 0


namespace NAMESPACE {
void MAIN {
    constexpr int onetile = 1;
    const uint32_t B1 = get_arg_val<uint32_t>(0);
    const uint32_t B2 = get_arg_val<uint32_t>(1);
    const uint32_t Ht = get_arg_val<uint32_t>(2);
    const uint32_t Wt = get_arg_val<uint32_t>(3);
    const bool do_mask_h = get_arg_val<uint32_t>(4) == 1;
    const bool do_mask_w = get_arg_val<uint32_t>(5) == 1;

    constexpr auto cb_in0 = tt::CB::c_in0;
    constexpr auto cb_scaler = tt::CB::c_in1;
    constexpr auto cb_mask_h_w = tt::CB::c_in2;
    constexpr auto cb_intermed0 = tt::CB::c_intermed0;
    constexpr auto cb_intermed1 = tt::CB::c_intermed1;
    constexpr auto cb_out = tt::CB::c_out0;
    constexpr uint32_t dst0 = 0;
    constexpr uint32_t dst1 = 1;

    binary_op_init_common(tt::CB::c_in0, tt::CB::c_in0);
    cb_wait_front(cb_scaler, onetile);

    if (do_mask_h || do_mask_w) {
        cb_wait_front(cb_mask_h_w, onetile * 2);
    }

    bool enable_reload = false;
    uint32_t num_tiles = B1 * B2 * Ht * Wt;
    uint32_t num_tile_done = 0;

    for (uint32_t b1 = 0; b1 < B1; ++b1) {
        for (uint32_t b2 = 0; b2 < B2; ++b2) {
            for (uint32_t ht = 0; ht < Ht; ++ht) {
                for (uint32_t wt = 0; wt < Wt; ++wt) {
                    bool last_row = (ht == Ht - 1);
                    bool last_col = (wt == Wt - 1);
                    bool last_out = (num_tile_done == num_tiles - 1);
                    bool do_mask = (do_mask_h && last_row) || (do_mask_w && last_col);

                    // get tile from reader
                    cb_wait_front(cb_in0, onetile);

                    if (do_mask) {
                        #if ACQ_REL
                        ACQ();
                        #endif

                        #if TILE_REGS
                        tile_regs_acquire();
                        #endif
                        copy_tile_init();
                        copy_tile(cb_in0, 0, dst0);

                        if (do_mask_h && last_row) {
                            copy_tile_init();
                            copy_tile(cb_mask_h_w, 0, dst1);
                            mask_tile_init();
                            mask_tile(dst0, dst1);
                        }

                        if (do_mask_w && last_col) {
                            copy_tile_init();
                            copy_tile(cb_mask_h_w, 1, dst1);
                            mask_tile_init();
                            mask_tile(dst0, dst1);
                        }
                        #if TILE_REGS
                        tile_regs_commit();
                        #endif

                        #if TILE_REGS
                        tile_regs_wait();
                        #endif
                        cb_reserve_back(cb_intermed0, onetile);
                        pack_tile(dst0, cb_intermed0);
                        cb_push_back(cb_intermed0, onetile);
                        #if TILE_REGS
                        tile_regs_release();
                        #endif
                        #if ACQ_REL
                        REL();
                        #endif
                    }

                    #if ACQ_REL
                    ACQ();
                    #endif
                    #if TILE_REGS
                    tile_regs_acquire();
                    #endif
                    if (enable_reload) {
                        cb_wait_front(cb_intermed1, onetile);
                        copy_tile_init();
                        copy_tile(cb_intermed1, 0, 0);
                        cb_pop_front(cb_intermed1, onetile);
                    }

                    if (do_mask)
                        cb_wait_front(cb_intermed0, onetile);

                    reduce_init_delta<false>(REDUCE_OP, REDUCE_DIM);
                    reduce_tile(REDUCE_OP, REDUCE_DIM, (do_mask) ? (cb_intermed0) : (cb_in0), cb_scaler, 0, 0, 0);
                    reduce_revert_delta();

                    if (do_mask)
                        cb_pop_front(cb_intermed0, onetile);

                    cb_pop_front(cb_in0, onetile);
                    #if TILE_REGS
                    tile_regs_commit();
                    #endif

                    #if TILE_REGS
                    tile_regs_wait();
                    #endif
                    if (last_out) {
                        cb_reserve_back(cb_out, onetile);
                        pack_tile(0, cb_out);
                        cb_push_back(cb_out, onetile);

                    } else {
                        cb_reserve_back(cb_intermed1, onetile);
                        pack_tile(0, cb_intermed1);
                        cb_push_back(cb_intermed1, onetile);
                    }
                    #if TILE_REGS
                    tile_regs_release();
                    #endif
                    #if ACQ_REL
                    REL();
                    #endif
                    enable_reload = true;
                    num_tile_done++;
                }
            }
        }
    }
}
}  // namespace NAMESPACE

```

**Comment by dongjin-na** [comment] 2024-04-25 01:33
> if you can reproduce with watcher, i would expect it to produce better log. What does the watcher output when you can reproduce? maybe it will lead more actionable debug next step

The watcher logs are the same on both passed cases and failed cases.

### passed case
```
At 11.123s attach device 0
At 11.330s detach device 0
At 11.406s starting
Legend:
	Comma separated list specifices waypoint for BRISC,NCRISC,TRISC0,TRISC1,TRISC2
	I=initialization sequence
	W=wait (top of spin loop)
	R=run (entering kernel)
	D=done (finished spin loop)
	X=host written value prior to fw launch

	A single character status is in the FW, other characters clarify where, eg:
		NRW is "noc read wait"
		NWD is "noc write done"
	noc<n>:<risc>{a, l}=an L1 address used by NOC<n> by <riscv> (eg, local src address)
	noc<n>:<riscv>{(x,y), a, l}=NOC<n> unicast address used by <riscv>
	noc<n>:<riscv>{(x1,y1)-(x2,y2), a, l}=NOC<n> multicast address used by <riscv>
	rmsg:<c>=brisc host run message, D/H device/host dispatch; brisc NOC ID; I/G/D init/go/done; | separator; B/b enable/disable brisc; N/n enable/disable ncrisc; T/t enable/disable TRISC
	smsg:<c>=slave run message, I/G/D for NCRISC, TRISC0, TRISC1, TRISC2
	k_ids:<brisc id>|<ncrisc id>|<trisc id> (ID map to file at end of section)
```

### failed case
```
At 11.406s attach device 0
At 11.612s detach device 0
At 11.708s starting
Legend:
	Comma separated list specifices waypoint for BRISC,NCRISC,TRISC0,TRISC1,TRISC2
	I=initialization sequence
	W=wait (top of spin loop)
	R=run (entering kernel)
	D=done (finished spin loop)
	X=host written value prior to fw launch

	A single character status is in the FW, other characters clarify where, eg:
		NRW is "noc read wait"
		NWD is "noc write done"
	noc<n>:<risc>{a, l}=an L1 address used by NOC<n> by <riscv> (eg, local src address)
	noc<n>:<riscv>{(x,y), a, l}=NOC<n> unicast address used by <riscv>
	noc<n>:<riscv>{(x1,y1)-(x2,y2), a, l}=NOC<n> multicast address used by <riscv>
	rmsg:<c>=brisc host run message, D/H device/host dispatch; brisc NOC ID; I/G/D init/go/done; | separator; B/b enable/disable brisc; N/n enable/disable ncrisc; T/t enable/disable TRISC
	smsg:<c>=slave run message, I/G/D for NCRISC, TRISC0, TRISC1, TRISC2
	k_ids:<brisc id>|<ncrisc id>|<trisc id> (ID map to file at end of section)
```

**Comment by jliangTT** [comment] 2024-04-25 01:40
@tt-dma , does this watcher output produce an actionable next step?

**Comment by tt-dma** [comment] 2024-04-25 01:52
Hi @jliangTT, it does look like a timing/runtime issue - especially since with or without watcher it still nondeterministically happens, and adding in dprints (perturbs timing) makes it go away. The watcher logs linked there are empty (only the legend is present) because the test likely finishes before watcher does a poll (30s according to the commands we're running here).

If it's a timing or pcc issue, they could try to root find where the data is going wrong using the watcher ring buffer feature, which shouldn't perturb timing much: https://github.com/tenstorrent/tt-metal/actions/runs/8825157634

Seeing as everyone suspects timing issue, the runtime board is probably the correct place for it

**Comment by tt-dma** [comment] 2024-04-25 01:52
I think @ihamer-tt might be looking into a way to inject delays for testing purposes, might be useful here

**Comment by jliangTT** [comment] 2024-04-25 02:10
understood. Thanks for the explanation.

**Comment by ihamer-tt** [comment] 2024-04-25 10:05
I have tried this on bgd-lab-11, with no watcher and varying watcher intervals (1s, 100ms, 10ms), and could not reproduce the failure. I'll be looking at #7468 to introduce delays with minimal overhead to try to reproduce this more consistently.

**Comment by jliangTT** [comment] 2024-05-01 17:24
Our watcher team is investigating and taking a look

**Comment by razorback3** [comment] 2024-05-03 07:13
Our engineers investigated that using `tile_regs_acquire`, `tile_regs_wait`, `tile_regs_commit`, and `tile_regs_release` functions rather than `acquire_dst`, `release_dst` functions solves the issue.
It is weird that `acquire_dst` and `release_dst` are just simple wrappers of those `tile_regs_*` functions.

Same thing happens for issue #7521.
I think we have to make a decision between to options:
1. Change all `acquire_dst` and `release_dst` function calls to use `tile_regs_*` functions.
2. Investigate further what is a real problem in `acquire_dst` and `release_dst` functions (I think this is out of scope of Moreh's ability).

@jliangTT , how do you think about this?

**Comment by jliangTT** [comment] 2024-05-03 16:47
Is this a @rtawfik01 question? can you provide some input to @razorback3's decision point?

**Comment by TT-billteng** [comment] 2024-05-03 16:52
we attempted to do this right after I joined, I took over host-side API cleanup but device-side got dropped as we had other things to do

**Comment by davorchap** [comment] 2024-05-09 00:47
> * Change all `acquire_dst` and `release_dst` function calls to use `tile_regs_*` functions.
> *

Please do `1. Change all `acquire_dst` and `release_dst` function calls to use `tile_regs_*` functions.`. 

We will deprecate the old APIs.

**Comment by davorchap** [comment] 2024-05-09 00:49
closing the case as the issue has been resolved.

**Closed by davorchap** 2024-05-09 00:49 UTC
Labels: bug, P1_critical, ci-bug, race_or_timing
