### ISSUE TITLE
t3000 all gather hangs w/ dprint+watcher enabled

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#8184] opened 2024-05-06 22:53 UTC
pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py::test_all_gather_on_t3000_post_commit[mem_config0-input_dtype0-8-1-input_shape1-0-layout1]

**Comment by pgkeller** [comment] 2024-05-14 18:26
Confirmed this still hangs after the recent all gather fixes.  Hang is now at tear down, last line is "Closing device 7".  This was w/ DPRINT enabled only (watcher enabled runs into OOM issues)

**Comment by smehtaTT** [comment] 2024-05-29 16:28
@pgkeller  to retest after David's fix

**Comment by tt-dma** [comment] 2024-05-30 18:12
Confirmed `TT_METAL_DPRINT_CORES=all pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py::test_all_gather_on_t3000_post_commit[mem_config0-input_dtype0-8-1-input_shape1-0-layout1]` passes on latest main, but run into an issue with enabling watcher for this test on remote chips.

Problem is that having watcher enabled on remote chips and running this test causes it to slow down heavily. I see the watcher polling progressing, but very slowly. Unfamiliar with the nature of the all gather test, is it possible that watcher polling is eating up bandwidth between the chips and slowing the test down?

**Comment by pgkeller** [comment] 2024-05-31 14:28
> Confirmed `TT_METAL_DPRINT_CORES=all pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py::test_all_gather_on_t3000_post_commit[mem_config0-input_dtype0-8-1-input_shape1-0-layout1]` passes on latest main, but run into an issue with enabling watcher for this test on remote chips.
> 
> Problem is that having watcher enabled on remote chips and running this test causes it to slow down heavily. I see the watcher polling progressing, but very slowly. Unfamiliar with the nature of the all gather test, is it possible that watcher polling is eating up bandwidth between the chips and slowing the test down?

Yes, this test communicates heavily across chips.  What watcher interval were you using?  I suspect for tests like this it should be 10 seconds or longer

**Comment by tt-dma** [comment] 2024-05-31 16:54
Slowdown point (with watcher + dprint enabled) appears to happen between 20s and 25s interval, essentially the length of the test. What I think is happening is if the watcher poll happens while the test is running, it eats up the bandwidth and also slows down the watcher polling to the point where there's no dead time between polls - meaning it's going to be slow for the remainder of the test. The slowdown point is lower when running with just watcher, so likely dprint polling contributes to that slowdown as well. Think this would fall under expected behaviour, or requires further investigation?

Also, PR for a change I needed to add to get TT_METAL_WATCHER_NOINLINE working after (I think) the sfpi bump: https://github.com/tenstorrent/tt-metal/pull/9018

**Comment by tt-dma** [comment] 2024-05-31 17:53
PR is merged, if @SeanNijjar thinks this looks fine then we can close the issue.

**Comment by SeanNijjar** [comment] 2024-05-31 21:51
@pgkeller @tt-dma - it sounds like it has to do with an issue of watcher dump time vs watcher poll time? Since the watcher timer isn't expected to be very precise (I always saw `TT_METAL_WATCHER=10` to mean "do a watcher poll in every 10 or so seconds. 11 is fine and so is 9 but 5 or 50 probably aren't". 

Is that the intended design. If so is it possible to restart the watcher poll time on prior sample _finish_?

**Comment by tt-dma** [comment] 2024-05-31 22:58
I had previously implemented the interval in a way to be as accurate as possible, but I think you're right in that the program should have priority - especially since we want people to be developing with watcher enabled. Here's a PR for that change: https://github.com/tenstorrent/tt-metal/pull/9038

FYI @pgkeller

**Closed** 2024-06-04 17:56 UTC
Labels: bug, P1_critical
