### ISSUE TITLE
Matmul output mismatch

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent/tt-metal#6775] opened 2024-03-26 14:19 UTC
First qkv MM in stable diffusion produces an incorrect PCC when block sharded. 

To repro, you can run `pytest -svv tests/ttnn/integration_tests/stable_diffusion/test_sharded_attention.py::test_qkv` on `aknezevic/mm_pcc_repro`

**Comment by AleksKnezevic** [comment] 2024-03-27 15:32
It looks like the mismatch is not due to the matmul but due to sharded output. 

To repro, you can run:
`pytest -svv tests/ttnn/integration_tests/stable_diffusion/test_sharded_attention.py::test_qkv` on `aknezevic/all_qkv_tests`. 
This has 8 tests, 4 that create sharded output in L1 which fail with bad pcc and 4 that place matmul output in interleaved DRAM which pass.  

@tarafdarTT, can you please take a look?

**Comment by jliangTT** [comment] 2024-03-28 17:51
Some discussion with @jvasilje on this and this is a critical enough to highlight the attention 

@tarafdarTT / @TT-BrianLiu , please prioritize accordingly

**Comment by tarafdarTT** [comment] 2024-03-28 20:08
> It looks like the mismatch is not due to the matmul but due to sharded output.
> 
> To repro, you can run: `pytest -svv tests/ttnn/integration_tests/stable_diffusion/test_sharded_attention.py::test_qkv` on `aknezevic/all_qkv_tests`. This has 8 tests, 4 that create sharded output in L1 which fail with bad pcc and 4 that place matmul output in interleaved DRAM which pass.
> 
> @tarafdarTT, can you please take a look?

Hi @AleksKnezevic wanted to clarify one thing. When you said interleaved output is okay, does that mean that the matmul directly output interleaved data or did you take the data out of the matmul and put it through the sharded_to_interleaved op.
If you did the latter, then I think the bug is the same as: https://github.com/tenstorrent-metal/tt-metal/issues/6355

Just wanted to verify that since I'm currently working on the above bug.

**Comment by AleksKnezevic** [comment] 2024-03-28 20:35
When the matmul directly output interleaved, the data is correct. If the matmul directly outputs sharded, the data is incorrect. 

If the matmul outputs interleaved and I then convert to sharded output is correct. 

If the matmul outputs sharded and then I convert to interleaved, data is incorrect.

**Comment by tarafdarTT** [comment] 2024-03-28 20:37
I see, looks like how the MM implemented sharding support is incorrect, @TT-BrianLiu can you look into this then?

**Comment by TT-BrianLiu** [comment] 2024-04-01 20:41
I am running these tests on a grayskull and the sharded versions hang for me instead of bad PCC. After the hang, the interleaved version hangs too (so device was probably in a bad state and resetting doesn't help)

**Comment by AleksKnezevic** [comment] 2024-04-01 23:52
Did you manage to repro on wormhole?

**Comment by TT-BrianLiu** [comment] 2024-04-02 14:57
I can try on wormhole and debug there, but I wasn't expecting it to hang on Grayskull.

**Comment by TT-BrianLiu** [comment] 2024-04-02 16:53
Ok I think interleaved is fine for both Grayskull and Wormhole. For sharded output, Grayskull hangs and Wormhole has bad PCC.

**Comment by TT-BrianLiu** [comment] 2024-04-02 18:48
I think I know what the issue is. It's related to uneven output shards in the last core. I need to double check how sharded infra is handling this, but for example for `N=2304` on 5 cores, `per_core_N` should be set tp 15 (2304 / 32 / 5 rounded up). This means each core's shard width will be 15 tiles, with last core "padded" up. For interleaved, this is not an issue since we write to a separate tensor allocator. 

@AleksKnezevic Side note, what is this piece of code trying to do here? For the example above, this gives me `per_core_N=17`. It should work but 15 is better.
<img width="426" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/109366241/ccc970b2-ce02-4141-af5f-259d8880e487">

**Comment by AleksKnezevic** [comment] 2024-04-02 18:50
What should the calculation be?

**Comment by TT-BrianLiu** [comment] 2024-04-02 18:56
> What should the calculation be?

It should be some from of `divup`. We have these implemented in various helper functions, but this is how we typically do it:
<img width="364" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/109366241/e1bbb6ed-6142-49a9-86bc-68445bcc484f">

**Comment by jliangTT** [comment] 2024-04-03 15:32
workaround will fix the mismatch but is slow. Also need to understand the root cause (or understand it & assert on it). P1

**Comment by TT-BrianLiu** [comment] 2024-04-03 21:10
I simplified the test to have smaller shapes and confirmed that the output sharded buffers on each core looks correct after the matmul. I think something may be messed up for how the output sharded tensor is being interpreted.

**Comment by TT-BrianLiu** [comment] 2024-04-04 19:57
The source of the bug is with BLOCK_SHARDED tensors with padding. You can reproduce by just creating BLOCK_SHARDED tensors and reading them back. @tarafdarTT is taking a look at fixing this.

**Comment by tarafdarTT** [comment] 2024-04-08 13:29
@TT-BrianLiu could you try cherry-picking my commit (aa8f406e29a3c02b5b0b54f2f2c0550b6f438a63) and running the matmul test. Sorry I tried but I think the test is only for wormhole .

**Comment by tarafdarTT** [comment] 2024-04-08 15:37
I tested it myself, turns out I was using a smaller shape on the height and when I use the same height I see hangs.
I will debug this rn and get it working. @TT-BrianLiu is ooo but he has given me blessings to use his wormhole machine. 
CC @AleksKnezevic @jliangTT

**Comment by tarafdarTT** [comment] 2024-04-09 22:26
@AleksKnezevic @jliangTT @davorchap @jvasilje @TT-BrianLiu 

The PCC issue is actually caused by two things. Uneven shards for direct sharded reads and writes, and uneven shards from sharded_to_interleaved. I have a fix for the former that increases PCC greatly but is still not perfect (around 0.9 ) for 2/3 cases (the other case is perfect). I can push that fix in today, and the other fix I can get to Thursday. (I am off Wednesday for Eid). 
I was also able to make a unit test where I see pcc failures for a single tile for interleaved_to_sharded.

**Comment by tarafdarTT** [comment] 2024-04-09 22:35
This is the PR that improves PCC and covers the direct read write case https://github.com/tenstorrent-metal/tt-metal/pull/7196

**Comment by tarafdarTT** [comment] 2024-04-15 16:56
Update, after addressing one bug in interleaved_to_sharded we did see PCC improve and are close, 0.94 and 0.97 on the two failing sizes and the rest is working. We are investigating what else could be the problem at the moment.

@jliangTT @AleksKnezevic @TT-BrianLiu

**Comment by TT-BrianLiu** [comment] 2024-04-15 22:00
Seems like a matmul issue with sharded output. Compute always produces the number of subblocks needed and writer would handle the output tiles. For interleaved, we respect padding for block and subblocks. For sharded, we just do a dummy wait. However, we need to do similar logic in the writer so that output sharded cb is properly padded, otherwise we will have contiguous useful data in spaces that will be treated as garbage. 

On the left is what we have now which is incorrect. On the right is what it's supposed to be. We have to "insert" dummy padded tiles, so our shard write interprets padded shards correctly.
<img width="830" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/109366241/4d06a022-0fd3-4f53-84d5-196875fa2b87">

**Comment by TT-BrianLiu** [comment] 2024-04-17 21:14
Looked into it a bit more and what's happening is exactly backwards ^_^. Sharded read always reads pages back in row major order without respecting padding, while output CB from matmul has the padded tiles. We need to augment sharded struct to keep track of padded cores for both write/read so it matches what our op produces.

<img width="592" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/109366241/2c9f5b3b-7955-4a17-af35-af50243740d3">

**Comment by tarafdarTT** [comment] 2024-04-24 00:28
Addressed in PR: https://github.com/tenstorrent/tt-metal/pull/7658

**Closed by tarafdarTT** 2024-04-24 00:28 UTC
Labels: bug, P0_Showstopper, CNN_bug, Stable Diffusion, op_cat: TM
