### ISSUE TITLE
Reduce in test_sharded.py PCC failure for BH

### ISSUE THREAD

**Issue by ntarafdar** [tenstorrent/tt-metal#15106] opened 2024-11-15 17:03 UTC
We need to comment out the skip for bh as it no longer hangs 

```FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py::test_sharded_reduce_h[dtype1-out_sharded-in0_sharded-8] - assert False
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py::test_sharded_reduce_h[dtype1-out_sharded-in0_sharded-16] - assert False
```

**Comment by ntarafdar** [comment] 2024-11-15 17:03
CC: @sjameelTT

**Comment by bbradelTT** [comment] 2024-11-15 17:28
The test still fails for me. We need to keep the skip until that is fixed. Otherwise BH all-post commit will fail. 

```
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py::test_sharded_reduce_h[dtype0-out_sharded-in0_sharded-8]
PASSED tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py::test_sharded_reduce_h[dtype0-out_sharded-in0_sharded-16]
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py::test_sharded_reduce_h[dtype1-out_sharded-in0_sharded-8] - assert False
FAILED tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py::test_sharded_reduce_h[dtype1-out_sharded-in0_sharded-16] - assert False
```

Will use this issue to investigate the failures.

**Comment by bbradelTT** [comment] 2024-12-04 19:46
Test to reproduce:

```
import pytest
import torch
import math

import ttnn
from tests.tt_eager.python_api_testing.sweep_tests.comparison_funcs import (
    comp_equal,
    comp_pcc,
)
from loguru import logger
from models.utility_functions import torch2tt_tensor, tt2torch_tensor, pad_by_zero, roundup32

def test_sharded_reduce_h(device):
    in_sharded = False
    out_sharded = False
    dtype = ttnn.bfloat8_b
    compute_grid_size = device.compute_with_storage_grid_size()
    N = 1
    C = 1
    H = 32
    W = 32

    interleaved_mem_config = ttnn.MemoryConfig(
        memory_layout=ttnn.TensorMemoryLayout.INTERLEAVED,
        buffer_type=ttnn.BufferType.L1,
    )
    sharded_mem_config = ttnn.MemoryConfig(
        memory_layout=ttnn.TensorMemoryLayout.WIDTH_SHARDED,
        buffer_type=ttnn.BufferType.L1,
    )

    out_mem_config = sharded_mem_config if out_sharded else interleaved_mem_config

    x = torch.randn((N, C, H, W)).bfloat16()

    xt = (
        ttnn.Tensor(
            x.reshape(-1).tolist(),
            x.shape,
            dtype,
            ttnn.ROW_MAJOR_LAYOUT,
        )
        .to(ttnn.TILE_LAYOUT)
        .to(
            device,
            interleaved_mem_config,
        )
    )

    yt = ttnn.max(xt, 2, memory_config=out_mem_config)

    tt_got_back = yt.cpu().to(ttnn.ROW_MAJOR_LAYOUT).to_torch()[:, :, :1, :]

    y = torch.max(x, 2, True)[0]

    if dtype == ttnn.bfloat16:
        passing, output = comp_equal(y, tt_got_back)
    else:
        passing, output = comp_pcc(y, tt_got_back, 0.999)
    logger.info(output)

    assert passing
```

**Comment by bbradelTT** [comment] 2024-12-04 20:32
Compute kernel: ttnn/cpp/ttnn/operations/reduction/generic/device/kernels/compute/reduce_h.cpp

Also, the test passes for float16 (dtype1 in the test in the repo).

@ncvetkovicTT hopefully the LLK team can take a look.

**Comment by nvelickovicTT** [comment] 2024-12-06 14:37
@bbradelTT when I run this test I get the following warning from test infra:

`Tensor layout must be Layout::TILE for bfloat8_b or bfloat4_b! Tensor layout will be Layout::TILE instead of the requested Layout::ROW_MAJOR!`

I tried just replacing ROW_MAJOR layout with TILE_LAYOUT, but than even the bfloat16 test fails.
What would be the correct way to work around this warning for further debugging?

**Comment by bbradelTT** [comment] 2024-12-06 14:53
@nvelickovicTT I think this is related to https://github.com/tenstorrent/tt-metal/pull/15393

I'll look into how to avoid the warning. But I'm not sure if the warning is related to the failure, this test should pass for GS/WH despite the warning.

**Comment by nvelickovicTT** [comment] 2024-12-11 14:41
@bbradelTT I ended up doing a simulation for this issue and in the waveforms everything looks fine on the packer side. Seems to be writing the correct data to L1.
One thing that is not easy for me to check with the current test is whether the location is correct, as I see interleaved/sharded memory config is used.
How can I turn these off, to simplify the test further?

**Comment by bbradelTT** [comment] 2024-12-11 15:51
@nvelickovicTT 
The code is designed to read in height order: NCWH instead of NCHW. There's no way around that.

The code was changed at some point after the test was failing to read in N C W_skip H W_chunk order, but you can undo that by setting W_chunk=1.

I think easiest is to set chunk_size to 1 in
ttnn/cpp/ttnn/operations/reduction/generic/device/multi_core_h/reduce_op_multi_core_h.cpp
at line 123.
```
uint32_t chunk_size = out_sharded ? 1 : ttnn::get_dest_reg_count(compute_kernel_config);
```

See https://github.com/tenstorrent/tt-metal/pull/15501 for details.

**Comment by bbradelTT** [comment] 2024-12-11 15:54
Also, the test I provided https://github.com/tenstorrent/tt-metal/issues/15106#issuecomment-2518419043 should be for a single tile. Which would make the chunk size irrelevant.

**Comment by nvelickovicTT** [comment] 2024-12-11 17:29
@bbradelTT I've put a fix in https://github.com/tenstorrent/tt-metal/tree/nvelickovic/15106_reduce_bfp8_b_fix
I've tested with your minima test and with the test from the issue. Both pass.

Issue was that num_faces passed to LLK API was 0, due to an omitted argument in a function call.
This than led to BFP EXP section size being programmed to be 0, thus producing bad results.

**Comment by bbradelTT** [comment] 2024-12-11 19:53
Thanks @nvelickovicTT 

Merged in a PR with your fix.

I noticed that method had a fixme comment. I left the comment there. It seems that the specific comment is in 6 places, 3 for WH, 3 for BH:
```
tt_metal/hw/ckernels/wormhole_b0/metal/llk_io/llk_io_pack.h:// FIXME-WH-UPLIFT
tt_metal/hw/ckernels/wormhole_b0/metal/llk_io/llk_io_unpack.h:// FIXME-WH-UPLIFT
tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_pack_api.h:// FIXME-WH-UPLIFT
tt_metal/hw/ckernels/blackhole/metal/llk_io/llk_io_pack.h:// FIXME-WH-UPLIFT
tt_metal/hw/ckernels/blackhole/metal/llk_io/llk_io_unpack.h:// FIXME-WH-UPLIFT
tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_pack_api.h:// FIXME-WH-UPLIFT
```

It would be good for someone to go through these comments and see if they can be removed (with or without additional work).

**Closed by bbradelTT** 2024-12-11 19:53 UTC
Labels: LLK, P1, blackhole, op_cat: reduces
