### ISSUE TITLE
PCC issue from interleaved to shared conversion.

### ISSUE THREAD

**Issue by shwetankTT** [tenstorrent/tt-metal#8212] opened 2024-05-07 17:50 UTC
Issues come up with uneven sharding, specific test and shard spec posted in comments below

**Comment by tarafdarTT** [comment] 2024-05-07 20:11
@shwetankTT has this python test 

```
import pytest
import math
from typing import Union, Tuple
from loguru import logger
import torch

# import torch.nn as nn

# import tt_lib
import tt_lib as ttl
import ttnn

from tests.ttnn.utils_for_testing import check_with_pcc_without_tensor_printout
from tests.ttnn.ttnn_utility_fuction import get_shard_grid_from_num_cores
from models.utility_functions import skip_for_wormhole_b0, skip_for_grayskull
from tt_lib.utils import (
    _nearest_y,
)

TILE_WIDTH = 32

def write_to_file(tensor, filename):
    tensor = tensor.detach().cpu().numpy()
    with open(filename, "w") as f:
        for i in range(tensor.shape[0]):
            for j in range(tensor.shape[1]):
                for k in range(tensor.shape[2]):
                    for l in range(tensor.shape[3]):
                        f.write(str(tensor[i][j][k][l]) + " ")
                    f.write("\n")
                f.write("\n")


def test_interleaved_to_sharded(device):
    torch.manual_seed(0)
    max_grid_size = (device.compute_with_storage_grid_size().y, device.compute_with_storage_grid_size().x)
    print(max_grid_size)
    input_channel = 64
    input_rest = 20*112*112
    shape = [1, 1, input_rest, input_channel]
    torch_input = torch.rand(shape, dtype = torch.bfloat16)
    input_tensor = ttnn.from_torch(
        torch_input, device=device, dtype=ttnn.bfloat8_b, layout=ttnn.TILE_LAYOUT
    )
    shard_cofig = ttnn.create_sharded_memory_config(
        shape=(3920, 64),
        core_grid=ttnn.CoreGrid(y=8, x=8),
        strategy=ttnn.ShardStrategy.HEIGHT,
        orientation=ttnn.ShardOrientation.ROW_MAJOR,
        use_height_and_width_as_shard_shape=True,
    )
    print(ttnn.get_memory_config(input_tensor))
    print(input_tensor.shape
          
          )
    #write_to_file(ttnn.to_torch(input_tensor).float(), "1.log")
    torch_in = ttnn.to_torch(input_tensor).float() 
    print(shard_cofig)
    #input_tensor = ttnn.pad(input_tensor, ((0, 0), (0, 0), (0, 16*64), (0,0)), value=0)
    #print(input_tensor.shape)
    #breakpoint()
    input_tensor = ttnn.to_layout(input_tensor,
                                         ttnn.ROW_MAJOR_LAYOUT,
                                         memory_config = shard_cofig)
    
    write_to_file(ttnn.to_torch(input_tensor).float(), "3.log") 
    print("breakpoint")
    input_tensor = ttnn.to_memory_config(input_tensor, memory_config=shard_cofig)
    #input_tensor = ttnn.unpad(input_tensor)
    torch_out = ttnn.to_torch(input_tensor).float()  
    write_to_file(ttnn.to_torch(input_tensor).float(), "2.log")
    print(ttnn.get_memory_config(input_tensor))
    print(input_tensor)
    passing, pcc_msg = check_with_pcc_without_tensor_printout(torch_in, torch_out, 0.999)
    logger.info(pcc_msg)
   ```

**Comment by mywoodstock** [comment] 2024-05-08 04:53
@tarafdarTT Could you please take a look at this issue? @shwetankTT has a fix, but he gets a hang.

**Comment by shwetankTT** [comment] 2024-05-08 15:04
@tt-aho I checked out your branch and ran the test case shared over there. I see the PCC is 0.15.

**Comment by tarafdarTT** [comment] 2024-05-08 15:05
hmm as @tt-aho mentioned, and I didn't notice when copy pasting the test case above, the test doesn't actually test interleaved_to_sharded. It does a direct sharded write, so that looks like a diff problem

**Comment by tarafdarTT** [comment] 2024-05-08 15:17
Closing this , the issue is not in interleaved_to_sharded but using a sharded memory config in `to_layout` while the tensor is an interleaved tensor.
There is another issue that comes up with reshard which I will open up a new issue for.

**Closed by tarafdarTT** 2024-05-08 15:17 UTC
Labels: bug, P0_Showstopper

**Comment by mywoodstock** [comment] 2024-05-08 16:37
@tarafdarTT could you please link the new issue here? thanks!

**Comment by tarafdarTT** [comment] 2024-05-08 16:43
https://github.com/tenstorrent/tt-metal/issues/8260
