### ISSUE TITLE
ND Hang for Falcon Multi Device + Async with FD2

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#8133] opened 2024-05-03 22:23 UTC
This is on fd2 branch:

- Hang on prefill + async https://github.com/tenstorrent/tt-metal/actions/runs/8943959906/job/24569826226
- Seems like it’s hung on decode + async https://github.com/tenstorrent/tt-metal/actions/runs/8945313117/job/24574051492
- A run from yesterday on an older rebase was able to finish running all of them https://github.com/tenstorrent/tt-metal/actions/runs/8941042299
- Latest main was passing https://github.com/tenstorrent/tt-metal/actions/runs/8944728624/attempts/1

Seems nd since the one that’s hung on decode means it passed the prefill one that hung before

**Comment by tt-asaigal** [comment] 2024-05-04 23:42
Hey @tt-aho I've pushed the discussed debug changes to [asaigal/fd2_falcon_hang](https://github.com/tenstorrent/tt-metal/tree/asaigal/fd2_falcon_hang). Seems like the issue is on the read path. I would appreciate it if you could take a look.

Repro command (this will run 1 decode layer on 2 chips):
`pytest -svv models/demos/falcon7b/tests/test_perf_falcon.py::TestParametrized::test_perf_t3000_bare_metal[decode_batch32_1024_async-falcon_7b]`

Please (re)assign as you see fit.

**Comment by cglagovichTT** [comment] 2024-05-06 14:35
Seeing this same issue on Llama. FD2 + async queues leads to reproducible hang

**Comment by davorchap** [comment] 2024-05-06 15:09
> Seeing this same issue on Llama. FD2 + async queues leads to reproducible hang

ND?

**Comment by cglagovichTT** [comment] 2024-05-06 15:14
Not clear how "ND" it is. Always hangs before first generation

**Comment by skhorasganiTT** [comment] 2024-05-06 16:00
Falcon7b single chip prefill + async perf test also hangs when reading back outputs on [this line](https://github.com/tenstorrent/tt-metal/blob/main/models/demos/falcon7b/tests/test_perf_falcon.py#L266)
Seems deterministic, can reproduce using this command (ignore and remove [this skip](https://github.com/tenstorrent/tt-metal/blob/main/models/demos/falcon7b/tests/test_perf_falcon.py#L557)):
`pytest models/demos/falcon7b/tests/test_perf_falcon.py::TestParametrized::test_perf_wh_bare_metal[True-prefill_seq256_bf16_l1-falcon_7b]`

**Comment by tt-aho** [comment] 2024-05-06 20:32
Determined the issue to be that the main thread is issuing the finish command while worker threads are still enqueueing other commands, so they may conflict and write to the same issue/fetch queue locations. @tt-asaigal will work on a fix to make worker threads issue the finish so there is no overlap.

**Comment by tt-asaigal** [comment] 2024-05-06 23:28
Changes on latest main should resolve both Falcon hangs. The previously hanging tests have been added back to CI. @cglagovichTT to test LLAMA with latest main.

**Comment by davorchap** [comment] 2024-05-07 00:14
closing this case, if the fix doesn't resolve  Llama3 issue we can open a new one (probably a different bug anyway)

**Closed by davorchap** 2024-05-07 00:14 UTC
Labels: bug, P0_Showstopper, LLM_bug
