### ISSUE TITLE
[Bug Report] Bilinear Upsampling seems to cause a problem

### ISSUE THREAD

**Issue by athul-bos-semi** [tenstorrent/tt-metal#13039] opened 2024-09-24 08:06 UTC
**Describe the bug**
The program was working, until after Bilinear Upsampling stage. The very next convolution gets stuck in the _HWCommandQueue_write_buffer_ stage according to Tracy. I’m also attaching the results of Tracy for reference.

**To Reproduce**
1. tt-smi -r 2
2. python text_unet.py
(You can find the files [here](https://github.com/athul-bos-semi/UNet_TTNN))

**Expected behavior**
The program should run to completion.

**Screenshots**
![What a Convolution is supposed to look like](https://github.com/user-attachments/assets/052ee874-27e3-404a-afb0-3544a928db26)
![What this Convolution looks like](https://github.com/user-attachments/assets/2bb2b585-786c-440b-a50c-de73e7edbb4d)
![More details on what this Convolution looks like](https://github.com/user-attachments/assets/64c24112-a6ff-4cb7-90fb-da54bfa191d7)

**Environment Information:**

- OS: Metal Devcloud accessed through Ubuntu 22.04 client
- Device: Wormhole
- Version of software: TT-Metal v0.51.0

**Additional context**
Use Tracy when checking. Also use L1 Buffer analyzer if available.

**Comment by mywoodstock** [comment] 2024-09-24 18:16
@athul-bos-semi The example seems to use deprecated `tt_lib` library. Which version of tt-metal are you using? It would be better to port it to the latest ttnn api.

**Comment by athul-bos-semi** [comment] 2024-09-26 05:57
I ported to v0.51.0, but ttnn.reshard does not work. The I ported it to main where reshard works, but convolution throws L1 memory error for code that was previously working.

**Comment by mywoodstock** [comment] 2024-09-26 18:04
> but convolution throws L1 memory error for code that was previously working.

Can you please provide repro details on this? Since you say this regression is with the latest `main` version, we need to look into that issue first.

**Comment by athul-bos-semi** [comment] 2024-09-26 23:09
You can download both the files from [here](https://github.com/athul-bos-semi/UNet_TTNN) and run the test_unet.py file to reproduce the errors.

**Comment by athul-bos-semi** [comment] 2024-09-30 00:42
The main has already changed, now the error is different. Can you try and run these two files? I am now running on specifc versions to avoid confusion instead of running on main.

**Comment by mbahnasTT** [comment] 2024-10-03 23:38
@athul-bos-semi please we need the updated code that is causing the recent issue.

**Comment by athul-bos-semi** [comment] 2024-10-07 02:01
I've uploaded the new code [here](https://github.com/athul-bos-semi/UNet_TTNN/tree/main) that does not use tt-lib anywhere.  Bilinear Upsampling issue seems to have solved itself when I switched to v0.52.0, and now the program goes all the way to Upsample 3, but fails due to a memory error. I am now working on fixing it.

**Comment by mywoodstock** [comment] 2024-10-08 18:59
Thanks for the update @athul-bos-semi. Can we close this then?

**Closed** 2024-10-08 20:15 UTC
Labels: bug, P0_Showstopper, CNNs, Customer_Bug, CNN_bug, community, vanilla unet
