### ISSUE TITLE
ttnn::transpose data mismatch when using BFLOAT16 data format

### ISSUE THREAD

**Issue by dgolubovicTT** [tenstorrent/tt-metal#15099] opened 2024-11-15 15:42 UTC
**Describe the bug**
ttnn::transpose has data mismatch with torch::transpose with bfloat16 dataformat on specific shapes:

```
Input shape (1,12,32,100) and dims for transpose (-3,-2) - Tensor mismatch

Input shape (32,12,100) and dims for transpose (-1,-2) - Tensor mismatch
```

These two shapes are expact transposes we have in Llama attention, so this mismatch causes data mismatch in Llama attention.

There also some transpose tests failing with bfloat16:

```
Input shape (18, 65) and dims for transpose (1, 0) - Tensor mismatch

Input shape (18, 64) and dims for transpose (1, 0) - Tensor match
```

```
Input shape (6, 33, 34) and dims for transpose (1, 0) - Tensor mismatch

Input shape (6, 33, 32) and dims for transpose (1, 0) - Tensor match
```

**Expected behavior**
It is expected for transpose to work for bfloat16 inputs without tensor missmatch.

**Additional context**
I am attaching ttnn IR for transpose tests that are failing with tensor mismatch. [Transpose_tensor_mismatch_2.txt](https://github.com/user-attachments/files/17777786/Transpose_tensor_mismatch_2.txt)
[Transpose_tensor_mismatch_1.txt](https://github.com/user-attachments/files/17777787/Transpose_tensor_mismatch_1.txt)

Here is a ttnn repro test:

```
@pytest.mark.parametrize("b", [1])
@pytest.mark.parametrize("h", [18])
@pytest.mark.parametrize("w", [65])
@pytest.mark.parametrize("dim0", [1])
@pytest.mark.parametrize("dim1", [2])
def test_transpose(device, b, h, w, dim0, dim1):
    torch.manual_seed(1234)

    torch_input_tensor = torch_random((b, h, w), -0.1, 0.1, dtype=torch.bfloat16)
    torch_output_tensor = torch_input_tensor.transpose(dim0, dim1)

    input_tensor = ttnn.to_device(ttnn.from_torch(torch_input_tensor), device, memory_config=ttnn.DRAM_MEMORY_CONFIG)
    input_tensor = ttnn.to_layout(input_tensor, layout=ttnn.TILE_LAYOUT)
    output_tensor = ttnn.transpose(input_tensor, dim0, dim1, memory_config=ttnn.DRAM_MEMORY_CONFIG)
    output_tensor = ttnn.from_device(output_tensor)
    output_tensor = ttnn.to_layout(output_tensor, layout=ttnn.ROW_MAJOR_LAYOUT)
    output_tensor = ttnn.to_torch(output_tensor)

    assert_with_pcc(torch_output_tensor, output_tensor)

```

I tried reproing this with much smaller tensor shape:
```
@pytest.mark.parametrize("b", [1])
@pytest.mark.parametrize("h", [2])
@pytest.mark.parametrize("w", [3])
@pytest.mark.parametrize("dim0", [-1])
@pytest.mark.parametrize("dim1", [-2])
def test_transpose(device, b, h, w, dim0, dim1):
    torch.manual_seed(1234)

    torch_input_tensor = torch_random((1, b, h, w), -0.1, 0.1, dtype=torch.bfloat16)
    torch_output_tensor = torch_input_tensor.transpose(dim0, dim1)

    input_tensor = ttnn.to_device(ttnn.from_torch(torch_input_tensor), device, memory_config=ttnn.DRAM_MEMORY_CONFIG)
    input_tensor = ttnn.to_layout(input_tensor, layout=ttnn.TILE_LAYOUT)
    output_tensor = ttnn.transpose(input_tensor, dim0, dim1, memory_config=ttnn.DRAM_MEMORY_CONFIG)
    output_tensor = ttnn.from_device(output_tensor)
    output_tensor = ttnn.to_layout(output_tensor, layout=ttnn.ROW_MAJOR_LAYOUT)
    output_tensor = ttnn.to_torch(output_tensor)
    print("torch_input_tensor: ")
    print(torch_input_tensor)
    print("output_tensor: ")
    print(output_tensor)
    print("torch_output_tensor: ")
    print(torch_output_tensor)

    assert_with_pcc(torch_output_tensor, output_tensor)
```

Here is the output:

```
torch_input_tensor: 
tensor([[[[-0.0635,  0.0649, -0.0703],
          [-0.0586,  0.0593, -0.0094]]]], dtype=torch.bfloat16)
output_tensor: 
TorchTensor([[[[-6.3477e-02,  5.9326e-02],
               [ 6.4941e-02, -9.3994e-03],
               [-7.0312e-02,  3.2300e+38]]]], dtype=torch.bfloat16)
torch_output_tensor: 
tensor([[[[-0.0635, -0.0586],
          [ 0.0649,  0.0593],
          [-0.0703, -0.0094]]]], dtype=torch.bfloat16)
```

**Comment by nvukobratTT** [comment] 2024-11-18 09:17
Just to clarify, this is the bug for one of the core models on Forge, therefore we set P0 for it :)) 

@ntarafdar @sjameelTT thanks for looking into this one! ❤

**Comment by sjameelTT** [comment] 2024-11-18 22:35
Are these all tiled tensors? Do you have a unit tests I can use to recreate this?

**Comment by dgolubovicTT** [comment] 2024-11-19 15:24
Hi @sjameelTT I updated issue description with one repro test.

**Comment by sjameelTT** [comment] 2024-11-19 15:44
Hm I can repro using your test, but oddly if I change it up to use some other APIs:


```
@pytest.mark.parametrize("b", [1])
@pytest.mark.parametrize("h", [18])
@pytest.mark.parametrize("w", [65])
@pytest.mark.parametrize("dim0", [1])
@pytest.mark.parametrize("dim1", [2])
def test_transpose_15099(device, b, h, w, dim0, dim1):
    torch.manual_seed(1234)

    torch_input_tensor = torch_random((b, h, w), -0.1, 0.1, dtype=torch.bfloat16)
    torch_output_tensor = torch_input_tensor.transpose(dim0, dim1)

    input_tensor = ttnn.from_torch(torch_input_tensor, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)
    output_tensor = ttnn.transpose(input_tensor, dim0, dim1)
    output_tensor = ttnn.to_layout(output_tensor, layout=ttnn.ROW_MAJOR_LAYOUT)
    output_tensor = ttnn.to_torch(output_tensor)
    print("torch_input_tensor: ")
    print(torch_input_tensor)
    print("output_tensor: ")
    print(output_tensor)
    print("torch_output_tensor: ")
    print(torch_output_tensor)


    assert_with_pcc(torch_output_tensor, output_tensor)
```

I get the following:


```
torch_input_tensor:
tensor([[[-0.0635,  0.0649, -0.0703,  ...,  0.0359,  0.0219, -0.0369],
         [-0.0320, -0.0898, -0.0094,  ..., -0.0344, -0.0179, -0.1001],
         [-0.0055, -0.0234,  0.0947,  ..., -0.0055,  0.0330, -0.0986],
         ...,
         [-0.0603,  0.0086,  0.0991,  ..., -0.0698,  0.0376,  0.0571],
         [ 0.0618,  0.0737, -0.0815,  ..., -0.0055, -0.0461, -0.0219],
         [-0.0635,  0.0923, -0.0640,  ..., -0.0625,  0.0047,  0.0391]]],
       dtype=torch.bfloat16)
output_tensor:
TorchTensor([[[-0.0635, -0.0320, -0.0055,  ..., -0.0603,  0.0618, -0.0635],
              [ 0.0649, -0.0898, -0.0234,  ...,  0.0086,  0.0737,  0.0923],
              [-0.0703, -0.0094,  0.0947,  ...,  0.0991, -0.0815, -0.0640],
              ...,
              [ 0.0359, -0.0344, -0.0055,  ..., -0.0698, -0.0055, -0.0625],
              [ 0.0219, -0.0179,  0.0330,  ...,  0.0376, -0.0461,  0.0047],
              [-0.0369, -0.1001, -0.0986,  ...,  0.0571, -0.0219,  0.0391]]],
            dtype=torch.bfloat16)
torch_output_tensor:
tensor([[[-0.0635, -0.0320, -0.0055,  ..., -0.0603,  0.0618, -0.0635],
         [ 0.0649, -0.0898, -0.0234,  ...,  0.0086,  0.0737,  0.0923],
         [-0.0703, -0.0094,  0.0947,  ...,  0.0991, -0.0815, -0.0640],
         ...,
         [ 0.0359, -0.0344, -0.0055,  ..., -0.0698, -0.0055, -0.0625],
         [ 0.0219, -0.0179,  0.0330,  ...,  0.0376, -0.0461,  0.0047],
         [-0.0369, -0.1001, -0.0986,  ...,  0.0571, -0.0219,  0.0391]]],
       dtype=torch.bfloat16)
```

Which is correct. Seems like one of the other functions is causing issues.

**Comment by dgolubovicTT** [comment] 2024-11-19 16:07
Also, I can't repro mismatch on for example 2x4 tensors.  When I run transpose on 2x4 tensor on forge I get mismatch:

```
input_tensor: 
[tensor([[[0.6719, 0.1836, 0.4570, 0.7500],
         [0.2617, 0.9805, 0.7617, 0.4023]]], dtype=torch.bfloat16)]
output_tensor: 
tensor([[[    0.6719, 13147068288309092274929664.0000],
         [    0.1836, 72016088863762089508864.0000],
         [    0.4570, 279007004114856968192.0000],
         [    0.7500, 75514342396408196768846577664.0000]]],
       dtype=torch.bfloat16)
torch_output_tensor: 
tensor([[[0.6719, 0.2617],
         [0.1836, 0.9805],
         [0.4570, 0.7617],
         [0.7500, 0.4023]]], dtype=torch.bfloat16)
```

However, If I set that shape in my ttnn repro test, everything works fine...

**Comment by dgolubovicTT** [comment] 2024-11-19 16:58
I have ttnn IR for the transpose 2x4 case that fails in forge but doesn't repro on ttnn test. [transpose_2x4_ttnn_ir.txt](https://github.com/user-attachments/files/17818696/transpose_2x4_ttnn_ir.txt)

It essentially contains ttnn ops called sequentialy like in ttnn test.

**Comment by sjameelTT** [comment] 2024-11-19 17:16
That one also seems to be calling ttnn.to_layout after ttnn.to_device, though I'm not sure why you can't repro it on ttnn. For the initial set of cases though, it appears to be related to to_layout on device, and tilize at the fundamental level. I will reassign this to @llongTT as he's the new owner of tilize.

**Comment by ntarafdar** [comment] 2024-11-21 16:26
@llongTT is working on another P0 at the moment. 
We will have someone joining us on Monday who will be responsible for tilize and untilize, with guidance from either @sjameelTT or myself I think she can get this by two weeks, giving her 1.5 weeks to look into this. 
@dgolubovicTT is that okay?

**Comment by nvukobratTT** [comment] 2024-11-21 17:04
> [@llongTT](https://github.com/llongTT) is working on another P0 at the moment. We will have someone joining us on Monday who will be responsible for tilize and untilize, with guidance from either [@sjameelTT](https://github.com/sjameelTT) or myself I think she can get this by two weeks, giving her 1.5 weeks to look into this. [@dgolubovicTT](https://github.com/dgolubovicTT) is that okay?

Thanks for the update @ntarafdar. I don't think prolonging this issue for 2 more weeks is okay.

This blocks the models we are working to bring up E2e which is already significantly delayed (originally targeted for completion by the end of September) due to various issues encountered on the TTNN side. We would appreciate it if we could avoid further delaying as these are critical for us.

**Comment by ntarafdar** [comment] 2024-11-21 17:06
@nvukobratTT if that's the case I will assign this to @sjameelTT as a P0 now .

**Comment by ntarafdar** [comment] 2024-11-21 17:10
@jaykru-tt , @sjameelTT can drive this but I also added you here since you are familiar with Untilzie, if you can help guide @sjameelTT that would be dope.

**Comment by ntarafdar** [comment] 2024-11-21 17:13
@dgolubovicTT @nvukobratTT I spoke to @sjameelTT , this is going to be hard to solve if we can't reproduce this in TTNN, Can you make a TTNN python unit test or at least give us the shapes and dim going into the transpose. 
We can sync on this if that is hard to get.

**Comment by ntarafdar** [comment] 2024-11-21 17:16
Something like this:
https://github.com/tenstorrent/tt-metal/blob/main/tests/tt_eager/python_api_testing/unit_testing/misc/test_transpose.py#L37-L40
The tensor shape, layout , (we know type is float 16) , along with the dims.
I'm assigning this to you guys as well, and feel free to remove the assignment after we get a test case.

**Comment by sjameelTT** [comment] 2024-11-21 20:48
After rebase it works as @sminakov-tt 's changes enabled odd inner dim row major tensors on device. All the tests in the issue should work now.

**Comment by dgolubovicTT** [comment] 2024-11-22 14:51
Hi @ntarafdar sorry for late response, I was OOOF. I can provide you with ttnn IR of transpose that causes mismatch on forge. I am attaching transpose of 2x4 tensor as a smallest test I couldn't reproduce in ttnn test. TTNN IR should have all the info you need (layouts, shapes, ttnn ops used). [test_transpose_2x4_mismatch_ttnn.txt](https://github.com/user-attachments/files/17871837/test_transpose_2x4_mismatch_ttnn.txt)

**Comment by ntarafdar** [comment] 2024-11-22 14:59
@dgolubovicTT , ty for the IR. 


First as @sjameelTT suggested can you rebase TT metal and see if its still broken as a big fix was pushed.

Second if it's still broken,
Neither @sjameelTT nor I are familiar with the IR format so will need your help to decipher this.

I see a 1x2x4 tensor being transposed

Can you answer the following questions:
1. what dims are being transposed, 
2. is this interleaved or sharded, 
3. if sharded what's the shard config ( core grid, shard orientation, shard shape)
4. L1 or Dram input
5. L1 or Dram output

**Comment by dgolubovicTT** [comment] 2024-11-22 15:17
1. dim0 = -2, dim1 = -1
2. dram interleaved input and output
From IR I see that input is in tile layout.

**Comment by sjameelTT** [comment] 2024-11-22 16:10
B to work for me locally. Could you try rebasing?

**Comment by prajaramanTT** [comment] 2024-11-22 17:45
Marking this ticket for closure. Please open if you run into this issue again.

**Closed** 2024-11-22 17:48 UTC
Labels: bug, P0, forge
