### ISSUE TITLE
Demo for SD

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent/tt-metal#5773] opened 2024-02-28 15:53 UTC
Currently we are running SD with `bfloat8_b` accumulation for convs on WH.
Once `fp32` accumulation for convs is enabled, run SD with both options for same inputs and generate images to compare.

**Comment by mywoodstock** [comment] 2024-02-28 16:13
https://github.com/tenstorrent-metal/tt-metal/issues/5772

**Comment by mywoodstock** [comment] 2024-03-06 16:19
we already have this in `main` since last week

**Comment by boris-drazic** [comment] 2024-03-11 14:21
@saichandax To run on WH, you need to flash to new firmware.
You can find new firmware patch `fw_pack-80.8.11.0.tar.gz` in home folder on two WH machines.
To flash with new patch use `tt-flash --fw-tar fw_pack-80.8.11.0.tar.gz` and then reboot the card afterwards `tt-smi -wr all wait`

If `tt-flash` is not available you can install it with
```
sudo apt install cargo
pip install git+https://github.com/tenstorrent/tt-flash.git
```

**Comment by saichandax** [comment] 2024-03-11 14:24
Sure @boris-drazic , we'll try the above steps and keep you posted.
Thank you.

**Comment by Sudharsan-V** [comment] 2024-03-20 13:41
Attached here are the images generated using the Stable Diffusion model for 30 iterations. Due to excessive denoising occurring in the final two layers, the denoising loop was stopped at 28 iterations.

[SD_WH.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14667290/SD_WH.pdf)

**Comment by boris-drazic** [comment] 2024-04-04 14:02
We need to debug what is happening with images in the last two steps.
Can you generate images for the same prompt in this way:
1) all 30 iterations in PyTorch
2) all 30 iterations in ttnn
3) run 28 iterations in ttnn and then for the 29th iteration in ttnn pass in PyTorch output from 28th iteration of PyTorch run
4) run 28 iterations in PyTorch and then for the 29th iteration in PyTorch pass in ttnn output from 28th iteration of ttnn run

Then compare tensors after 28th iteration between ttnn and PyTorch. For output tensors of 28th iteration do PCC and all close comparison and then plot difference between tensors.

**Comment by Sudharsan-V** [comment] 2024-04-05 12:28
Hi @boris-drazic , tried running the demo after pulling the latest main. However in the latest main, the test hangs before completing the first iteration, to be specific the hang occurs in the first resnet block.
I used WH machine to run this demo.

**Comment by boris-drazic** [comment] 2024-04-18 14:17
@Sudharsan-V SD should not hang any more.
Here are suggestions to improve image quality:

- instead of ttnn scheduler module, use the one from diffusers pkg
- use parameters from `CompVis/stable-diffusion-v1-4` for tokenizer/text_encoder/schedulers (note: the scheduler used in the original model (PNDMScheduler) is different from the one currently used by the demo script (LMSDiscreteScheduler))
- do the same data pre-processing to generate the prompt embedding as `diffusers` pkg

for the detail, please check the following commits:
- `c5bcc49c16f261bc0456b20ef216ed13dde4eefc`  (change scheduler from ttnn -> diffusers)
- `bcfd65be3db11bd0c562a7b662d6e905b5482276`  (update tokenizer/text_encoder/scheduler and embedding pre-processing)

Please apply these changes and generate a few images to see how good they look.

**Comment by Sudharsan-V** [comment] 2024-04-22 12:22
@boris-drazic, Images are generated after incorporating the suggestions mentioned above. The generated images are attached to the [document](https://docs.google.com/document/d/1C11am_Y-ac2xXdbVBV_-9kb_-tmON4swWDgpReuqO5M/edit?usp=sharing) for your reference.

Even with the PyTorch scheduler we encounter over-denoising at the last 2 iterations(i.e the image generated at the (n-2) iteration is better than the image generated at the nth iteration, n=30)
Corresponding [commit](https://github.com/tenstorrent/tt-metal/compare/main...sudharsan/sd_demo_pt_scheduler)

**Comment by mtatsumiTT** [comment] 2024-04-24 17:40
@boris-drazic I tried to run the demo script with cherry-picking [the commit](https://github.com/tenstorrent/tt-metal/compare/main...sudharsan/sd_demo_pt_scheduler), but it hangs at the end of the first iteration. I tested with the command:
```
pytest -svv models/experimental/functional_stable_diffusion/demo/demo.py::test_demo_diffusiondb
```

**Comment by Sudharsan-V** [comment] 2024-04-25 13:21
@mtatsumiTT, Even I encountered this hang  but after resetting the device using `tt-smi -wr all` (for wH device), I was able to run the demo.
Moreover, after replacing the `LMSDiscreteScheduler` with `PNDMScheduler`, the images generated looks promising.
The images are attached in the [document](https://docs.google.com/document/d/1C11am_Y-ac2xXdbVBV_-9kb_-tmON4swWDgpReuqO5M/edit) (page 28 - 33) for your reference.

**Comment by mtatsumiTT** [comment] 2024-04-25 13:47
ah I reset board and run the demo after making sure another small test runs without hang for multiple times, but the demo script hangs for all trials for me.

Yes, I think that's also included in the suggestion. The current demo script code with the commit still uses `LMSDiscreteScheduler`, could you update it?

**Comment by Sudharsan-V** [comment] 2024-04-26 16:07
@mtatsumiTT , Please find the commit for SD using PNDMScheduler[here](https://github.com/tenstorrent/tt-metal/commit/eb2ac4f71c43c39932f245fecb2d82b78480e3be#diff-22ac428f745f9cb5b82252999229e53e89bd75790498728ca7e46793ca9fa421).
Image generated using  ttnn PNDMScheduler are attached in the [document](https://docs.google.com/document/d/1C11am_Y-ac2xXdbVBV_-9kb_-tmON4swWDgpReuqO5M/edit?usp=sharing) (pg: 34 - 39)

**Comment by mtatsumiTT** [comment] 2024-04-26 16:42
thanks, will try that

**Comment by mtatsumiTT** [comment] 2024-04-30 21:27
Hi, I tested the demo script locally and I'm currently observing the allocator error ([issue](https://github.com/tenstorrent/tt-metal/issues/7985)). The error is raised even without cherry-picking the commit mentioned above, so I guess the SD demo script is broken in main now. 

fyi @AleksKnezevic

**Comment by AleksKnezevic** [comment] 2024-04-30 22:04
@mtatsumiTT, can you please add 
`@pytest.mark.parametrize("device_l1_small_size", [32768], indirect=True)` to the demo and try again?

**Comment by mtatsumiTT** [comment] 2024-05-01 16:43
I confirmed that the SD demo script generates promising image with the commit and patch locally, thanks!

**Comment by jliangTT** [comment] 2024-05-01 22:03
@AleksKnezevic @mtatsumiTT , thanks for merging with a quick around. There remains three things that needs your help on:
- demo moved to the /model/demo/wormhole folder
- demo needs a readme page so people can run (refer to this [page](https://github.com/tenstorrent/tt-metal/tree/main/models/demos/t3000/llama2_70b) as a reference)
- the table https://github.com/tenstorrent/tt-metal?tab=readme-ov-file#wormhole-wh-models needs to be updated.

**Comment by jliangTT** [comment] 2024-05-03 18:21
@saichandax , do you mind helping with the above three TODO items, thanks!

**Comment by Sudharsan-V** [comment] 2024-05-09 12:49
Stable Diffusion model is moved to`models/demos/grayskull` folder and the PR is created for the same.
Corresponding PR:[#8294]( https://github.com/tenstorrent/tt-metal/pull/8294)
Running the test_performance throws the following error
`E       AssertionError: act_block_h must evenly divide out_block_h`
Currently, debugging this error, will update this file in the separate commit.

**Comment by jliangTT** [comment] 2024-05-10 15:08
isn't this demo running on Wormhole? why is it going to the grayskull folder?

**Comment by AleksKnezevic** [comment] 2024-05-10 15:10
@jliangTT the file location in the PR itself is correct, just typo in the comment.

**Comment by Sudharsan-V** [comment] 2024-05-10 15:15
Sorry @jliangTT, It is a typo. The files are in `models/demos/wormhole`.
The PR:https://github.com/tenstorrent/tt-metal/pull/8294 is updated with the performance file.
Adding the performance number for your reference:
```
Compilation time ~ 127.748s
Inference time ~ 2.4s
```

**Comment by smehtaTT** [comment] 2024-06-05 15:33
Can be closed after @mbahnasTT can test it this week

**Comment by tt-rkim** [comment] 2024-06-12 15:24
Per @dvartaniansTT , the only feedback was a typo: https://github.com/tenstorrent/tt-metal/issues/9127#issuecomment-2148571965

This was captured and fixed in main.

**Closed** 2024-06-26 15:29 UTC
Labels: bug, P1_critical, CNN_bug, Stable Diffusion
