### ISSUE TITLE
acosh is causing hangs on the sweeps

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#10557] opened 2024-07-23 00:22 UTC
It appears this op continues to hang the CI pipeline. 
https://github.com/tenstorrent/tt-metal/actions/workflows/ttnn-run-sweeps.yaml

**Comment by umadevimcw** [comment] 2024-07-24 09:34
@eyonland  In WHB0 I ran the above sweep tests for acosh and it passed without any issue. PFA

<img width="1131" alt="image" src="https://github.com/user-attachments/assets/c6dc9df7-9e29-4ac0-8d81-ff68100f3af8">



<img width="1073" alt="image" src="https://github.com/user-attachments/assets/e7d2749b-0a48-4096-9378-aff9c2ed7305">

**Comment by umadevimcw** [comment] 2024-07-24 10:01
PFA for GS

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/a864903e-6326-4b2b-a1f9-779598fe42a1">

**Comment by umadevimcw** [comment] 2024-07-25 10:35
@eyonland Please find the PR that skips tests on GS here #10728

**Comment by umadevimcw** [comment] 2024-07-25 10:40
@eyonland Please find the watcher zip for GS and WHB0. it has three folders in it

[acsoh_watcher.zip](https://github.com/user-attachments/files/16374714/acsoh_watcher.zip)

**GS**
generated_GS - has all the features like ring buffer details etc.
generated_GS1 - Remove additional features of watcher with the env 

**WHB0**
generated_whb0

**Comment by eyonland** [comment] 2024-07-25 16:10
@pgkeller / @jvasilje ,   I am recommending that this test be skipped to keep the CI pipelines flowing without issue.   Please see attached documentation if anyone needs to review the hangs on GS.

**Comment by pgkeller** [comment] 2024-07-25 20:59
what's the history of this test?  is it new?  or did it recently start failing?  from 10K feet, looks like a runtime problem, we can reassign

**Comment by umadevimcw** [comment] 2024-08-12 06:01
@eyonland Looks the issue is not occurring in the recent CI tests also one of our team member tried to run it on GS and test passed with recent code
![image](https://github.com/user-attachments/assets/7e27170b-3833-462e-9e8b-faf000fff9b0)

Hence I am closing this issue

**Closed by umadevimcw** 2024-08-12 06:01 UTC
Labels: bug, op_cat: eltwise
