### ISSUE TITLE
[Bug Report] CPU and NPU produce different BFP8_B values from the same BF16 tensor.

### ISSUE THREAD

**Issue by namhyeong-kim** [tenstorrent/tt-metal#14032] opened 2024-10-21 09:29 UTC
**Describe the bug**
The CPU and NPU produce different BFP8_B values from the same BF16 tensor.

**To Reproduce**
1. go to branch `namhyeong/....` [Link to branch](https://github.com/tenstorrent/tt-metal/tree/namhyeong/bf8_bf16_conversion_bug)
2. run `tests/ttnn/unit_tests/test_bfp8_bf16_conversion.py` [Link to test file](https://github.com/tenstorrent/tt-metal/blob/namhyeong/bf8_bf16_conversion_bug/tests/ttnn/unit_tests/test_bfp8_bf16_conversion.py)
    1. `test_typecast_bf16_to_bfp8_b` fails, while `test_typecast_bfp8_b_to_bf16` passes. 

**Expected behavior**
The CPU and NPU should produce the same BFP8_B values.

**Screenshots**
<img width="810" alt="스크린샷 2024-10-21 오후 6 28 49" src="https://github.com/user-attachments/assets/4fca23f6-aa16-469c-bca9-e104a5bf53ea">

**Please complete the following environment information:**
- OS: [Ubuntu 20.04]

**Additional context**
No additional context

**Comment by rdjogoTT** [comment] 2024-10-21 23:36
I have started investigating and should have an update by tomorrow.

**Comment by rdjogoTT** [comment] 2024-10-22 21:10
I've managed to trace the data through the HW path it takes, and it looks like the issue occurs in the Packer. I will be investigating this further

**Comment by rdjogoTT** [comment] 2024-10-24 18:40
The issue comes from how the packer handles bfp8_b datums, with rounding and shifting with rounding again. I'm looking into best course of action now.

Can you please provide some context to why the values need to match exactly? Is this just a bug report or is the accuracy needed somewhere specific? One potential fix would come at the expense of perf due to not using full packer bandwidth, so it would help to know the application.

**Comment by namhyeong-kim** [comment] 2024-10-25 07:28
1. We will use BFP8_B for training large language models. I can't fully anticipate the model-level side effects caused by conversion inconsistencies between the CPU and NPU. Could you implement an option for precise conversion, even if it slightly reduces packer bandwidth?
2. CPU converts correctly, while the NPU converts approximately. Is that correct?

**Comment by rdjogoTT** [comment] 2024-10-25 14:27
Yes, the CPU is producing the more accurate values in this case. Ok I will look into how that can be done.

**Comment by jvasilje** [comment] 2024-10-30 15:16
@rdjogoTT any updates on this P0 bug?

**Comment by rdjogoTT** [comment] 2024-10-30 16:32
I have pushed a branch `origin/rd/bfp8b_pack` with the workaround we found. It involves changing the pack src format for bfp8b to fp16b instead, which would cut packer bandwidth in half for WHB0 (but shouldn't affect BH).

This raises the question of how to handle this tradeoff. The way to decide would be to try training with bfp8b and see whether or not the accuracy is needed/tradeoff is worth it.

**Comment by namhyeong-kim** [comment] 2024-11-04 22:32
It looks that I cannot apply the accurate conversion in program-object-level. Could you make an option that toggles this feature?

**Comment by rdjogoTT** [comment] 2024-11-05 16:50
Ok, I will add an option ASAP.

**Comment by rdjogoTT** [comment] 2024-11-06 21:54
https://github.com/tenstorrent/tt-metal/pull/14822 contains the new flag `bfp8_pack_precise` which allows you to toggle the feature. Setting it to true in the `ComputeConfig` will result in the test above passing. I will work to merge this change quickly.

In the case of typecast, this is how it can be set to True:
```
auto eltwise_unary_kernel_group_1_id = tt::tt_metal::CreateKernel(
        program,
        "tt_metal/kernels/compute/eltwise_sfpu.cpp",
        core_group_1,
        tt::tt_metal::ComputeConfig{
            .math_fidelity = MathFidelity::HiFi4,
            .fp32_dest_acc_en = args.fp32_dest_acc_en,
            .unpack_to_dest_mode = unpack_to_dest_mode,
            .bfp8_pack_precise = true, // <----------- add this line
            .math_approx_mode = math_approx_mode,
            .compile_args = compute_kernel_args_group_1,
            .defines = unary_defines});
```

**Comment by namhyeong-kim** [comment] 2024-11-07 01:04
Thank you! Could I check the feature in various input?
The test `test_typecast_bf16_to_bfp8_b` only demonstrates the existence of the bug; it doesn't have sufficient coverage.

**Comment by rdjogoTT** [comment] 2024-11-07 01:11
The feature should enable fp16b or fp32 dest to be packed out accurately. Yes, please test it with various inputs.

**Comment by namhyeong-kim** [comment] 2024-11-07 01:14
What is enabling bf16?

**Comment by rdjogoTT** [comment] 2024-11-07 01:20
Sorry I should have clarified - typecast works by unpacking the fp16b to Dest and using the packer to convert to bfp8b. Similar with fp32 to bfp8b typecast. This bug was caused by that packer conversion, so this feature should enable accurate conversion now.

**Comment by rdjogoTT** [comment] 2024-11-07 16:45
Hi @namhyeong-kim, can you please share your tests with me when you make them. I would like to include them with my PR: https://github.com/tenstorrent/tt-metal/pull/14822 before merging to main.

**Comment by namhyeong-kim** [comment] 2024-11-08 00:34
Ok. I will share it

**Comment by namhyeong-kim** [comment] 2024-11-08 01:19
I pushed the tests to [my branch](https://github.com/tenstorrent/tt-metal/tree/namhyeong/bf8_bf16_conversion_bug) that is rebased on your branch.
The test `test_typecast_bf16_to_bfp8_b_various_input` all pass
But when `insert_nan` is true  in `test_typecast_bf16_to_bfp8_b_with_inf_nan`, the tests fails.
cpu makes `nan` but npu makes `-inf`. 
```
idx=(tensor(0), tensor(1)) cpu=nan npu=-inf
idx=(tensor(0), tensor(4)) cpu=nan npu=-inf
idx=(tensor(0), tensor(18)) cpu=nan npu=-inf
idx=(tensor(0), tensor(29)) cpu=nan npu=-inf
idx=(tensor(0), tensor(35)) cpu=nan npu=-inf
```
Could you check these failed tests?

**Comment by rdjogoTT** [comment] 2024-11-08 19:18
I've found that the issue is again to do with the packer, will post further updates soon.

**Comment by rdjogoTT** [comment] 2024-11-08 21:03
Tensix team has confirmed that we have had issues in the past as well with these special values. Unfortunately nothing can be done from the HW/LLK side to remedy this.

LLK recommendation is to make the checks for special values aware that NaN in Bfp8_b may be converted to -Inf. If there is a case that you must know if there is a NaN, maybe check before converting to Bfp8_b?

**Comment by namhyeong-kim** [comment] 2024-11-09 00:14
I understood the limitation. I will check before conversion to bfp8_b as your recommendation if `nan` should be handled.
Please double check the tests that I provided have enough coverage.

**Comment by jvasilje** [comment] 2024-11-12 16:10
@namhyeong-kim can we close this P0 issue?

**Comment by rdjogoTT** [comment] 2024-11-12 16:12
@jvasilje I am working on adding the tests and merging the PR today.

**Comment by zzigler-tt** [comment] 2024-11-13 05:58
@rdjogoTT Please advise when this is fully complete so we can close out this issue, thanks.

**Comment by rdjogoTT** [comment] 2024-11-13 19:09
This has been resolved with PR: https://github.com/tenstorrent/tt-metal/pull/14822. Can now be closed

**Closed** 2024-11-13 19:34 UTC
Labels: bug, P0, WH, moreh, LLK, blackhole
