### ISSUE TITLE
WH N300 PCC error with watcher enabled in `test_mo reh_logsoftmax.py::test_logsoftmax_backward_large_algorithm_for_dim_hw`

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#7521] opened 2024-04-16 20:59 UTC
Occurs on N300, and started happening the past few days. To reproduce (almost always failed for me in a VM):

```
TT_METAL_WATCHER=60 pytest --count=1000  -xv tests/tt_eager/python_api_testing/unit_testing/misc/test_mo
reh_logsoftmax.py::test_logsoftmax_backward_large_algorithm_for_dim_hw
```

**Comment by TT-billteng** [comment] 2024-04-16 21:03
@jliangTT did we re-make the Moreh project board? I can't find it

**Comment by jliangTT** [comment] 2024-04-16 21:07
yes it is there. hold on. https://github.com/orgs/tenstorrent/projects/37

**Comment by TT-billteng** [comment] 2024-04-16 21:07
CI stress test run https://github.com/tenstorrent/tt-metal/actions/runs/8699776501

**Comment by TT-billteng** [comment] 2024-04-16 21:08
> yes it is there. hold on. https://github.com/orgs/tenstorrent/projects/37

can't add it to the board for some reason

**Comment by jliangTT** [comment] 2024-04-16 22:16
Yeah i know why. Forgot to add write privilege to metalium team. I added it on your behalf, but you should be able to do it now.  thanks Bill

**Comment by jliangTT** [comment] 2024-04-23 17:54
same as #5868

**Comment by hschoi4448** [comment] 2024-04-24 09:49
I have created the code for reproducing the issue.

To reproduce the issue, use the 
- branch: [logsoftmax_debug](https://github.com/tenstorrent/tt-metal/tree/hyungsuk/moreh_logsoftmax_debug)
- kernel code https://github.com/tenstorrent/tt-metal/blob/hyungsuk/moreh_logsoftmax_debug/tt_eager/tt_dnn/op_library/moreh_softmax_backward/kernels/moreh_softmax_backward_h_large.cpp
- cmd: 
```
 TT_METAL_WATCHER=60 pytest --count=1000  -xv tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_logsoftmax.py::test_logsoftmax_backward_large_algorithm_for_dim_hw >log.txt
```


```C++

        // This for loop should not affect the result.
        for (uint32_t h = 0; h < Ht; ++h) {
            if (h == 0) {
                ACQ();
                copy_tile_to_cb(cb_dy, cb_add);
                REL();
            }
            else {
                if (h == Ht - 1) {
                    ACQ();
                    constexpr uint32_t onetile = 1;
                    constexpr int dst0 = 0;
                    constexpr int dst_mask = 1;

                    cb_reserve_back(cb_inter0, onetile);
                    cb_wait_front(cb_dy, onetile);
                    cb_wait_front(cb_mask, onetile);

                    copy_tile_init();
                    copy_tile(cb_dy, 0, dst0);

                    // The code copies the mask and does nothing else. However, deleting this code does not reproduce the issue.
                    copy_tile_init();
                    copy_tile(cb_mask, 0, dst_mask);

                    pack_tile(dst0, cb_inter0);

                    cb_pop_front(cb_dy, onetile);

                    cb_push_back(cb_inter0, onetile);

                    REL();

                    ACQ();
                    add_tiles_to_cb(cb_add, cb_inter0, cb_add);
                    REL();
                } else {
                    ACQ();
                    copy_tile_to_cb(cb_dy, cb_add);
                    REL();
                }
            }
        }

        // This reduce should not affect the result.
        // The reduce result is also not used. However, deleting it does not reproduce the issue.
        ACQ();
        reduce_tile_to_cb(REDUCE_OP, REDUCE_DIM, cb_add, cb_bcast_scaler, cb_sum, 1, /*pop0=*/1, /*pop1=*/0);
        REL();

        // Only this for loop should affect the result.
        for (uint32_t h = 0; h < Ht; ++h) {
            constexpr auto cb_tmp0 = tt::CB::c_intermed0;
            ACQ();
            copy_tile_to_cb(cb_y, cb_tmp0);
            REL();

            // dy - y
            ACQ();
            sub_tiles_to_cb(cb_dy, cb_tmp0, cb_dx);
            REL();
        }

        cb_pop_front(cb_sum, onetile);
```

The new reproduction code calculates `dy - y` instead of logsoftmax backward.
It's a simple calculation, but only the first face of the first tile is incorrect.

```C++
tt_dev tensor([[[[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
```


Looking at the new code, only the calculation of `dy - y` in the last for loop should affect the result. Indeed, if we delete the code above, the issue is not reproduced.

since there doesn't seem to be any unusual code in the kernel but the issue still occurs, it seems that there might be an issue with timing or something else. It would be best to have TT check it out.




@razorback3 @TT-billteng @jliangTT

**Comment by TT-billteng** [comment] 2024-04-25 04:03
Thank you for the investigation @hschoi4448, deep analysis like this may uncover something fundamental, and a fix/patch will benefit many :)

**Comment by ihamer-tt** [comment] 2024-04-26 11:55
For pytest to support --count, one must `pip install pytest-repeat`.
Full command:
```
TT_METAL_WATCHER=10ms pytest --count=100  -xv tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_logsoftmax.py::test_logsoftmax_backward_large_algorithm_for_dim_hw
```

Test **passes** when all watcher features are disabled:
```
export TT_METAL_WATCHER_DISABLE_ASSERT=1
export TT_METAL_WATCHER_DISABLE_RING_BUFFER=1
export TT_METAL_WATCHER_DISABLE_NOC_SANITIZE=1
export TT_METAL_WATCHER_DISABLE_PAUSE=1
export TT_METAL_WATCHER_DISABLE_STATUS=1
```

Test **fails** when only **STATUS** feature is enabled:
```
unset TT_METAL_WATCHER_DISABLE_STATUS
```

Test **passes** when only **STATUS** is **disabled**:
```
unset TT_METAL_WATCHER_DISABLE_ASSERT
unset TT_METAL_WATCHER_DISABLE_RING_BUFFER
unset TT_METAL_WATCHER_DISABLE_NOC_SANITIZE
unset TT_METAL_WATCHER_DISABLE_PAUSE
export TT_METAL_WATCHER_DISABLE_STATUS=1
```

Seems like there is something with STATUS that causes this.

**Comment by ihamer-tt** [comment] 2024-04-26 13:24
One interesting data point is that the issue goes away if I add 2 NOPs in write_debug_status (one NOP is not enough):
```
template<typename... Types>
inline void write_debug_status(volatile tt_l1_ptr uint32_t *debug_status, uint32_t c, Types... rest)
{
    volatile uint32_t x = get_debug_status(c, rest...);
    asm volatile("nop");
    asm volatile("nop");
    * debug_status = x;
}
```

@pgkeller, do you have any thoughts on this?

I reproduced the issue with the file that is committed on the branch (i.e. not with the snippet pasted above).
@hschoi4448, I see that the file you linked to (moreh_softmax_backward_h_large.cpp) is different from the snippet you pasted.

**Comment by pgkeller** [comment] 2024-04-26 16:06
My best guess is that we have a race and the NOPs change timing (extra insns, possibly cache misses) that triggers this issue.  I'd be curious __which__ DEBUG_STATUS causes the issue.  That will point us to brisc/ncrisc/trisc<n> and possibly which datamovement/compute llk.  I also wonder if the kernel is using atomics and/or writing to L1 and reading the results with NOC

**Comment by jliangTT** [comment] 2024-05-01 17:29
ok. this is the runtime issue queue it does.

**Comment by razorback3** [comment] 2024-05-03 07:15
> Our engineers investigated that using tile_regs_acquire, tile_regs_wait, tile_regs_commit, and tile_regs_release functions rather than acquire_dst, release_dst functions solves the issue.
> It is weird that acquire_dst and release_dst are just simple wrappers of those tile_regs_* functions.
> 
> Same thing happens for issue https://github.com/tenstorrent/tt-metal/issues/7521.
> I think we have to make a decision between to options:
> 
> Change all acquire_dst and release_dst function calls to use tile_regs_* functions.
> Investigate further what is a real problem in acquire_dst and release_dst functions (I think this is out of scope of Moreh's ability).
> @jliangTT , how do you think about this?

Copied above comment from issue https://github.com/tenstorrent/tt-metal/issues/5868#issuecomment-2092440555.

**Comment by davorchap** [comment] 2024-05-09 00:56
Closing the issue, the solution is the same as in https://github.com/tenstorrent/tt-metal/issues/5868

**Closed by davorchap** 2024-05-09 00:56 UTC
Labels: bug, moreh, P1_critical, ci-bug, race_or_timing
