### ISSUE TITLE
[Bug Report] ttnn::reshape failing to reshape tensor from `[1, 1, 1, 65536]` to `[1, 32, 32, 32]` citing L1 allocation error

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#15075] opened 2024-11-15 04:23 UTC
**Describe the bug**
I'm attempting to eliminate most if not all CPU fallback code paths in my GGML backend. One of which is reshaping a single vector into a 3D tensor - I know this is not efficient on TT hardware and I should eliminate it completely by graph rewrite in the future - This operation fails when performed purely on device.

**To Reproduce**
The following is the minimal reproducible example. Compile and run it:

```cpp
#include <cstddef>
#include <ttnn/core.hpp>
#include <ttnn/operations/eltwise/unary/unary.hpp>
#include <ttnn/operations/creation.hpp>
#include <ttnn/device.hpp>
#include <ttnn/operations/data_movement/tilize_with_val_padding/tilize_with_val_padding.hpp>
#include "ttnn/operations/data_movement/reshape_on_device/reshape.hpp"

#include "ttnn/operations/data_movement/reshape_view/reshape.hpp"
#include "common/bfloat16.hpp"

#include <vector>
#include <iostream>

int main()
{
    auto& device = ttnn::open_device(0);
    auto t = ttnn::zeros(ttnn::SimpleShape({1, 1, 1, 65536})).to(&device);
    t = ttnn::tilize_with_zero_padding(t);

    std::cout << "Original shape: " << t.shape() << std::endl;
    auto b = ttnn::reshape(t, ttnn::SimpleShape({1, 32, 32, 32}));
    std::cout << "resulting shaoe: " << b.shape() << std::endl;
}
```

Observe the error:

```
                  Metal | INFO     | Initializing device 0. Program cache is NOT enabled
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
                  Metal | INFO     | MMIO Device 0 : Tunnel 0 : Device 0
                  Metal | INFO     | MMIO Device 0 : Tunnel 0 : Device 4
Original shape: ttnn.Shape([1, 1, 1[32], 65536])
                 Always | FATAL    | Statically allocated circular buffers on core range [(x=0,y=0) - (x=0,y=0)] grow to 8487424 B which is beyond max L1 size of 1499136 B
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_THROW @ /home/marty/Documents/tt/tt-metal/tt_metal/impl/program/program.cpp:761: tt::exception
info:
Statically allocated circular buffers on core range [(x=0,y=0) - (x=0,y=0)] grow to 8487424 B which is beyond max L1 size of 1499136 B
```

**Expected behavior**
Reshape from 1D vector should work no matter the vector size. Or at least the API/document should provide some way to indicate the algorithm cannot run if the input exceeds a certain size.

**Screenshots**

**Please complete the following environment information:**
- OS: Arch Linux
- Card: N300
- commit: 008c50a744ab398526f12992f9f4902283f9215a

**Additional context**

**Comment by ayerofieiev-tt** [comment] 2024-11-15 04:25
Looks like its the same issue
https://github.com/tenstorrent/tt-metal/issues/15032

**Comment by dmakoviichuk-tt** [comment] 2024-11-15 04:27
@marty1885  could you pass last parameter multicore=true please?

**Comment by marty1885** [comment] 2024-11-15 04:29
@ayerofieiev-tt The problem is not `tilize_with_zero_padding`. It's with `ttnn::reshape`.

**Comment by marty1885** [comment] 2024-11-15 05:31
@dmakoviichuk-tt No unfortunately. `ttnn::reshape` eventually calls `ttnn::to_layout` and runs into the same issue.

**Comment by jvegaTT** [comment] 2024-11-15 19:33
This is a tough one,

I suspect at some point in time we are trying to convert the tensor to a TILE which turns it from 1 X 65536 to 32 X 65536 which will require 65536*4*32=8388608 bytes of memory which is about what the error message is stating.

However we also can not use the current algorithm to do reshape on device on it since we are going from a very large page size (262144B) to many (1024) small pages. The current algorithm for on device reshape for row major requires creating in each worker a circular buffer whose size is max(input_page_size,output_page_size) * number_of_output_pages / number_of_workers. However since number_of_output_pages is very large and input_page_size is also huge we end up requiring a huge CB, 0.25GB/number of workers of L1! To change this without breaking functionality in device a significant re-write of the kernel code is required to prevent data corruption in other cases.

This means host side reshape is currently the only option. I haven't studied it fully, I was only assigned reshape yesterday but the host should be able to handle 0.25GB. What we need to do is to pre-identify that this will fail down the road and to pre-emptively send it to do the work on host.

I am currently working on a new version of device side reshape where proper memory management is one of the priorities in the new algorithm, but it is a very complex task and will take time. I can do the bandaid solution of sending it to fall back on host version as I mentioned in the meantime.

**Comment by jvegaTT** [comment] 2024-11-15 20:42
Also 32 X 32 X 32 = 32768 not 65536 so the tensors are not the same size, this is not a supported case for reshape

**Comment by jvegaTT** [comment] 2024-11-15 20:46
I ran this python with the supported dimensions and the test passed

![Image](https://github.com/user-attachments/assets/f931cafe-cb09-4c0f-a79a-6884d7352173)

**Comment by jvegaTT** [comment] 2024-11-18 21:12
Closing this issue as the test case is not valid

**Comment by dmakoviichuk-tt** [comment] 2024-11-18 23:23
@jvegaTT  case is still valid.Error didn't mention that it is a wrong shape.

**Comment by jvegaTT** [comment] 2024-11-19 19:19
The problem is some other OPs have been using Reshape in a way that is not supported (as essentially a wrapper to call tensor.reshape) when they have tiled tensors they want to make "wider" by allowing some of the padded data to be marked as part of the regular data. In all implementations of reshape (PyTorch, Tensorflow), reshape should never change the volume of the logical shape. Therefore to add the correct assert would be to remove support for the erroneous usage of reshape which breaks thousands of tests at once. I am adding a bandaid fix where I check whether they want to use this as a wrapper for tensor.reshape (if the padded volume is not changing), allowing that usage pattern to work, and then adding the assert if, as is the case here, it is a completely unsupported case.

**Comment by ntarafdar** [comment] 2024-12-05 05:08
@jvegaTT @nardoTT @dmakoviichuk-tt is this close able? Or should we wait for @nardoTTs PR?

**Comment by jvegaTT** [comment] 2024-12-10 23:01
> [@jvegaTT](https://github.com/jvegaTT) case is still valid.Error didn't mention that it is a wrong shape. It should return good explanation if reshape cannot be called. Please don't close issue.

The above operation now causes a TT_FATAL assertion informing the user that the volumes do not match. Can the issue be closed?

**Closed** 2024-12-11 00:36 UTC
Labels: bug, P1, community
