### ISSUE TITLE
unpacker race exposed when speeding up kernel launch

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#11591] opened 2024-08-18 16:45 UTC
metal is double-initializing CB configs on unpacker.  Removing the 2nd init causes failures in CI.  Running

pytest "tests/ttnn/unit_tests/operations/test_eltwise_typecast.py::TestTypecast::test_run_eltwise_typecast_op[dst_mem_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)-input_mem_config=MemoryConfig(memory_layout=TensorMemoryLayout::INTERLEAVED,buffer_type=BufferType::DRAM,shard_spec=std::nullopt)-input_shapes=[[1, 1, 32, 32]]-pt_input_dtype=torch.int32-tt_input_dtype=DataType.INT32-tt_output_dtype=DataType.BFLOAT16]"

Gives a mismatch.  This is test runs the following kernels:
reader_unary_interleaved_start_id.cpp
writer_unary_interleaved_start_id.cpp 
eltwise_sfpu.h

Add a delay per the following makes the test pass (ifdef is the new code):
inline void _llk_unpack_dbg_feature_disable_() {
#if defined(UCK_CHLKC_UNPACK)
    for (volatile uint32_t xxx = 0; xxx < 100; xxx++);
#endif
    reg_write(RISCV_DEBUG_REG_DBG_FEATURE_DISABLE, 1<<11); // Set debug feature disable bit 11
                                                           // workaround for bug tenstorrent/budabackend#1372
} 

However, that makes the following test fail:
pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_scaled_dot_product_attention.py::test_sdpa_tt_with_program_cache[1-16-1-2048-64-k128-q128-bfp8]

Moving the delay to where the original CB config init was in metal fw trisc.cc makes both tests pass.

(not sure how to tag llk issues, assigned Milos for reassignment/visibility)

**Comment by tt-aho** [comment] 2024-08-28 13:04
It looks like the hack delay added to `trisc.cc` did not resolve the issue in all cases, so some tests still had ND output, and trying to increase the delay didn't really help these cases pass.
Was found that moving the delay into `trisck.cc` before `run_kernel` allows all these tests to pass with deterministic pcc. This is similar to adding the delay where the original duplicated CB init was happening for unpacker, since `llk_setup_operands` was the function duplicating CBs and was basically the very first fn run for unpacker at the start of `run_kernel`.

**Comment by tt-aho** [comment] 2024-08-28 13:09
Currently looking at debugging on `aho/cb-unpack-debug`, which is rebased off of the commit before the CB changes went into main. Just commenting out the contents of `llk_setup_operands` will cause the test mentioned in the OP to get PCC errors, though adding the hack delay into `llk_setup_operands` will make it pass. It needs to be a sufficiently large delay for it to pass, ex. the hack delay we put in loops 100 iterations, but a loop of 10 iterations does not. This happens for slow or fast dispatch, and doesn't seem likely that it's a dispatch issues at the moment.

**Comment by tt-aho** [comment] 2024-08-28 20:03
I believe I've found what the race was, and this fixes the `test_eltwise_typecast.py` test without needing to add a delay. Not sure if `sdpa` failures are related since it had known ND issues, and the original change to just remove cb init could have just disturbed timing and caused it to fail.

The issue is that in `firmware_kernel_common_init` which is run by all RISCs, it zeros out a register `memory_write(RISCV_DEBUG_REG_DBG_FEATURE_DISABLE, 0);`, this means that all RISCs will be trying to zero out the register at different times. In the failing typecast test, the unpacker kernel will try to write a required non-zero value here. The race is that some other risc zeros out the register after unpacker writes the value, and adding a delay in unpacker makes it so that all riscs zeroed out the register before unpacker attempts to write the value, making it pass. The fix is to restrict zeroing the register to only unpacker, since from what I can tell only unpacker interacts with the register.

**Comment by yieldthought** [comment] 2024-08-29 10:20
@tt-aho With this fix `pytest models/demos/wormhole/llama31_8b/tests/test_llama_attention_prefill.py` is passing for me again in main on `aus-wh-01` 🙌

**Comment by tt-aho** [comment] 2024-08-29 14:40
> @tt-aho With this fix `pytest models/demos/wormhole/llama31_8b/tests/test_llama_attention_prefill.py` is passing for me again in main on `aus-wh-01` 🙌

Might just be due to timing or another change on main, as I don't see the race fix resolve the pcc issues in conditions below.

On my branch https://github.com/tenstorrent/tt-metal/tree/aho/cb-unpack-debug, this is checked out to the commit before all the cb changes went in, and removes the duplicate CB init from pack/unpack only. If I apply the proper race fix to this branch, I see that the llama test still has ND pcc, but like you mentioned on latest main this test seems to have stable passing pcc.

**Comment by tt-aho** [comment] 2024-08-29 14:42
Closing as this race issue seems resolved, and the llama pcc seems related to the ND sdpa pcc issue #9370, and not directly related to this besides potentially changed timing affecting sdpa.

**Closed by tt-aho** 2024-08-29 14:42 UTC
Labels: LLK, P1_critical
