### ISSUE TITLE
[Bug Report] When `preserve_fp32_precision=True` and an fp32 CB is used as input in `reduce_tile`, incorrect values are produced.

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#10337] opened 2024-07-16 06:53 UTC
**Describe the bug**

# Test Purpose
I wanted to verify if it is possible to execute `reduce_tile` on an fp32 type CB while using `preserve_fp32_precision=True`.
So, I created `CB::c_intermed0` and `CB::c_intermed1` as fp32 CBs and executed `reduce_tile` on them.
As a result, I discovered that the output of `reduce_tile` was half of the correct value.

# fill intermed CB

```C++
    Scalar val1, val2;
    val1.f = 10.0f;
    val2.f = 0.1f;

    fill_cb_with_value(tt::CB::c_intermed0, val1.u);
    fill_cb_with_value(tt::CB::c_intermed1, val2.u);
```
https://github.com/tenstorrent/tt-metal/blob/hyungsuk/bug_preserve_fp32_and_reduce_tile/tt_eager/tt_dnn/op_library/moreh_softmax/kernels/reader_moreh_softmax_w.cpp#L35

In the test code above, the reader data movement kernel fills intermed0 with the value 10 and intermed1 with the value 0.1.

```C++
        // If you want to check the value of intermed0, please comment it out.
        // copy_tile_to_cb(tt::CB::c_intermed0, cb_out0);  

        // If you want to check the value of intermed0, please comment it out.
        // copy_tile_to_cb(tt::CB::c_intermed1, cb_out0);  

        reduce_tile_to_cb<false>(REDUCE_OP, REDUCE_DIM, tt::CB::c_intermed0, tt::CB::c_intermed1, cb_out0, 1);
```
https://github.com/tenstorrent/tt-metal/blob/hyungsuk/bug_preserve_fp32_and_reduce_tile/tt_eager/tt_dnn/op_library/moreh_softmax/kernels/moreh_softmax_w.cpp#L39C1-L45C111

To check whether the intermed CBs contain values,  you can comment out `reduce_tile_to_cb` and uncomment the `copy_tile_to_cb` above.

# Expected result and Bug
```C++
    reduce_tile_to_cb<false>(REDUCE_OP, REDUCE_DIM, tt::CB::c_intermed0, tt::CB::c_intermed1, cb_out0, 1);

    // intermed0 * intermed1 = 10 * 0.1 -> 1
    // 1 * TILE_WIDTH -> 32
```
If the input to `c_intermed0` is 10 and the `c_intermed`` is 0.1, then reducing in the W direction should yield a result of 32.
However, the actual result is 16.

I think `reduce_tile` for fp32 CBs is a pattern that is used very frequently. It's important to resolve this bug quickly to ensure compatibility with `preserve_fp32_precision`.

**To Reproduce**
1. Go to https://github.com/tenstorrent/tt-metal/tree/hyungsuk/bug_preserve_fp32_and_reduce_tile
2. Click on run `pytest ./tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_softmax.py`
3. See error
```Python
tt_dev tensor([[15.9375, 15.9375, 15.9375,  ...,  0.0000,  0.0000,  0.0000],
        [15.9375,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [15.9375,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [15.9375,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [15.9375,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [15.9375,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
       dtype=torch.bfloat16)
```

**Expected behavior**

**Screenshots**
If applicable, add screens
![image](https://github.com/user-attachments/assets/96f6b03a-b79d-48c5-8595-32c08e8577a1)
hots to help explain your problem.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)
- ARCH_NAME: wormhole_b0

**Additional context**

**Comment by amahmudTT** [comment] 2024-08-20 23:44
The reduction operation uses instructions in the FPU and not just SFPU. But the flag 

`preserve_fp32_precision=True`. causes the destination format of the unpacker to be Float_32, without the flag it is TF32.

```
constexpr std::int32_t unpack_src_format[32] = {
    5,5,5,255,255,255,255,255,255,255,255,255,255,255,255,255,5,255,255,255,255,255,255,255,0,0,0,0,0,255,255,255,
};
constexpr std::int32_t unpack_dst_format[32] = {
    5,5,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,0,0,0,0,0,255,255,255,
};
```

I think this is the root cause of the issue as of now. 

But I am also curious regarding the way the circular buffer which are declared **32 bit**  are filled with the function 

```
void fill_cb_with_value(uint32_t cb_id, uint32_t value, int32_t num_of_elems = 1024) {
    cb_reserve_back(cb_id, 1);
    volatile tt_l1_ptr std::uint16_t* ptr = (volatile tt_l1_ptr uint16_t*)(get_write_ptr(cb_id));
    for (int j = 0; j < num_of_elems; j++) {
        ptr[j] = uint16_t(value >> 16);
    }
    cb_push_back(cb_id, 1);
}
```

It seems the above function is filling up 16 bit elements, then how is it working ?

**Comment by hschoi4448** [comment] 2024-08-21 02:06
>It seems the above function is filling up 16 bit elements, then how is it working ?

```C++
template <typename T>
FORCE_INLINE void process_data(int cb_id, uint32_t value, int32_t num_of_elems) {
    T* ptr = reinterpret_cast<T*>(get_write_ptr(cb_id));
    for (int j = 0; j < num_of_elems; j++)
    {
        ptr[j] = static_cast<T>(value);
    }
}

FORCE_INLINE void fill_cb_with_value(uint32_t cb_id, uint32_t value, int32_t num_of_elems = 1024) {
    cb_reserve_back(cb_id, 1);
    const DataFormat data_format = get_dataformat(cb_id);
    switch((uint)data_format & 0x1F) {
        case ((uint8_t)DataFormat::Float32):
            process_data<uint32_t>(cb_id, value, num_of_elems);
            break;
        case ((uint8_t)DataFormat::Float16_b):
        default:
            process_data<uint16_t>(cb_id, value, num_of_elems);
            break;
    }
    cb_push_back(cb_id, 1);
}

```


The reason fill_cb_with_value works is that the code above it is actually being called.
https://github.com/tenstorrent/tt-metal/blob/hyungsuk/bug_preserve_fp32_and_reduce_tile/tt_eager/tt_dnn/kernels/dataflow/moreh_common.hpp#L141

**Comment by amahmudTT** [comment] 2024-08-21 20:10
So the preserve_fp32_precision flag is not valid for this OP. We need a mechanism to prevent setting this flag for  ops for which it is not valid. Created an issue https://github.com/tenstorrent/tt-metal/issues/11756. Closing this issue.

**Closed by amahmudTT** 2024-08-21 20:10 UTC
Labels: bug, P0_Showstopper, moreh
