### ISSUE TITLE
tt_lib.tensor.groupnorm with beta and gamma tensors provided breaks with low PCC [Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#3712] opened 2023-11-09 08:49 UTC
**Describe the bug**
**tt_lib.tensor.groupnorm** operation in cases when beta and gamma tensors are provided fails in all combinations of test cases involving BFLOAT8_B type input tensor on Wormhole with low PCC errors.

**To Reproduce**
1. Checkout branch `main`
2. Run unit test `test_groupnorm.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_groupnorm.py`

**Expected behavior**
There are three test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_groupnorm.py` and they all are expected to fail.

- These three test cases are breaking with error like this:
`Max ATOL Delta: 21.86038589477539, Max RTOL Delta: inf, PCC: 0.2943113090075851, PCC check failed`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for tt_lib.tensor.groupnorm and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_groupnorm_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `groupnorm_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by npetrovic-tenstorrent** [comment] 2024-04-04 11:28
PCC is still low in this case

**Comment by davorchap** [comment] 2024-05-19 19:10
> PCC is still low in this case

@yugaoTT is the issue here that beta and gamma are in bfloat8 ?

If we don't support this case, we should assert out

**Comment by yugaoTT** [comment] 2024-05-21 14:14
these are the old version of group norm (composite ops chaining several unary ops together), I think we can assert on not allowing bfp8, since this old GN is not used by any models

**Comment by yugaoTT** [comment] 2024-05-31 16:00
I found the problem is in the test setup, the old GN is very in-efficient which requires gamma beta to be padded to the exact shape as input tensor. I fixed that, will run CI then merge

**Comment by yugaoTT** [comment] 2024-05-31 17:41
merged, I'll close

**Closed by yugaoTT** 2024-05-31 17:41 UTC
Labels: bug, WH, P2_should_have, op_cat: fused
