### ISSUE TITLE
CommonFixture.MatmulLargeBlock hangs on BH with Watcher enabled

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#12666] opened 2024-09-13 18:08 UTC
After https://github.com/tenstorrent/tt-metal/commit/fc8d313510daefc1bb221fb4a6d922799e1a35b7 `CommonFixture.MatmulLargeBlock` hangs when running test config "RM input, RM output" only when it is preceded by "Tilized input, RM output" 

This can be reproduced on main:
```
TT_METAL_WATCHER=5 ./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=CommonFixture.MatmulLargeBlock
```
The hangs manifests as ncrisc FW not getting go signal to launch the ncrisc kernel. i.e. hang is in 
```
ncrisc.cc:

while (*ncrisc_run != RUN_SYNC_MSG_GO);
```

The test passes without Watcher. It also passes with Watcher + DPrint with dprints in the compute kernel. It fails with Watcher + DPrints in ncrisc FW

**Comment by rtawfik01** [comment] 2024-09-16 13:28
@nvelickovicTT fyi, but Ill debug this once I have some time because it is related to my commit.

**Comment by nvelickovicTT** [comment] 2024-10-03 14:54
Update for this issue:

Last commit where this can be consistently reproduced is https://github.com/tenstorrent/tt-metal/commit/8aa197abdc30ff052709bd58cc54df7427dd9053.

With the next commit (https://github.com/tenstorrent/tt-metal/commit/0679c1988385f6ac0a78008f14be57b9298d40bd) it starts only intermittently hanging.

And with current main (https://github.com/tenstorrent/tt-metal/commit/0d5f4889313d3ef8f86c1555fc378ac9ee81454f) I wasn't able to reproduce the hang.

Also the Watcher+DPrint combination didn't have any effect while I tested. Might be card related.

**Comment by abhullar-tt** [comment] 2024-10-04 04:08
> 0d5f488

on the commits where it was hanging were you able to reproduce the hang on different machines?

**Comment by nvelickovicTT** [comment] 2024-10-21 15:20
Tested commit that consistently hangs (https://github.com/tenstorrent/tt-metal/commit/8aa197abdc30ff052709bd58cc54df7427dd9053) with only the fix added in https://github.com/tenstorrent/tt-llk-bh/commit/dc92e255cfd75945ccda2fa72e34e1cc9efe942e. This makes the test consistently pass.
Closing the issue as the fix is already in tt-metal.

FYI @rtawfik01 , thanks for the suggestion.

**Closed by nvelickovicTT** 2024-10-21 15:20 UTC
Labels: LLK, blackhole
