### ISSUE TITLE
hang on SD test

### ISSUE THREAD

**Issue by jvasilje** [tenstorrent/tt-metal#5789] opened 2024-02-28 21:16 UTC
From Aleks Knezevic

I couldn’t collect the perf dump for some reason, I tried on several hosts. I can debug tomorrow evening. If I run the model without collecting the pest passes, but if I prepend ./tt_metal/tools/profiler/profile_this.py it hangs during model creation. 
[@Nitika Shanker](https://tenstorrent.slack.com/team/U01ES9Q6MH6)
 and 
[@Abhinav](https://tenstorrent.slack.com/team/U055MU9S9CJ)
 if you have any idea why this is happening, or have a chance to run it, please take a look, otherwise I’ll  keep at it.
FYI, for me, running the base model took more that 10 minutes, so to get it to actually finish I needed to change the timeout in pytest.ini
The branch I’m working on is aknezevic/simplified_sd and the test to run the model is pytest -svv tests/ttnn/integration_tests/stable_diffusion/test_unet_2d_coition_model.py -k 512 . There are several unit tests in the same folder. I’m working on test_transformer_2d_model.py and 
[@Nitika Shanker](https://tenstorrent.slack.com/team/U01ES9Q6MH6)
 is taking a look at test_resnet_block_2d 
[@Abhinav](https://tenstorrent.slack.com/team/U055MU9S9CJ)
, maybe you want to take a loot at test_upsample or test_downsample?
The re-written model is in models/experimental/functional_stable_diffusion/tt2/ I haven’t had a chance yet to update the unit tests to point to that model, just test_unet_2d_coition_model.py , so you’ll need to update the unit test to pick up the right model (see test_unet_2d_coition_model.py ). Sorry, I was planning on doing this to make things a little smoother for you guys but (not actually) getting this perf trace took much longer than expected. (edited)

**Comment by jvasilje** [comment] 2024-02-28 21:23
update from Akhmed: 

"..it seems to be related to the profiler. And also someone from metal team because it seems that calling FinishQueue after every operation is what's causing the hang"

fyi - @mo-tenstorrent  @DrJessop

**Comment by DrJessop** [comment] 2024-02-28 21:27
Based on this data, maybe I should jump in on this.

Could I please be given step-by-step instructions to reproduce, and I will take a look at what could be going wrong on the command queue side.

Thanks.

**Comment by DrJessop** [comment] 2024-02-28 23:05
I was given the following instructions by @arakhmati 
```bash
git checkout aknezevic/simplified_sd
make build
scripts/build_scripts/build_with_profiler_opt.sh
./tt_metal/tools/profiler/profile_this.py -n unet -c  "pytest -svv tests/ttnn/integration_tests/stable_diffusion/test_unet_2d_condition_model.py -k 512"
```

and I was seeing this error

```bash
E               OSError: CompVis/stable-diffusion-v1-4 does not appear to have a file named model_index.json.
```

Need someone to assist here in order for me to continue debugging. @arakhmati @AleksKnezevic @tt-nshanker

**Comment by AleksKnezevic** [comment] 2024-02-29 03:18
@DrJessop, this is due to a hugging-face outage, as mentioned on slack, please pull to latest, get the needed `unet.pt` and `unet_config.pt` files and re-run.

**Comment by DrJessop** [comment] 2024-02-29 18:41
Looking into this, and I'm seeing that we are reading back event 1606 twice in a row and then hang on writing to a buffer.

**Comment by DrJessop** [comment] 2024-02-29 19:20
More investigation. 1607 is the expected event that tells the host to wrap, since it never gets this event back, it doesn't reset some ptrs.

**Comment by jvasilje** [comment] 2024-03-01 01:14
@DrJessop any updates on this..? :)

**Comment by AleksKnezevic** [comment] 2024-03-02 19:01
@DrJessop, this is a blocker. We have the whole down and mid blocks on device, but can't profile to optimize perf.

**Comment by DrJessop** [comment] 2024-03-04 23:16
I pushed a small fix to `aknezevic/simplified_sd`. I ran with profiler enabled, and it passed for me on an 800MHz N150 card.

**Comment by mo-tenstorrent** [comment] 2024-03-04 23:20
@AleksKnezevic  Can you elaborate a little more on what the hang signature looks like for you? On IRD machines there was Austin weka issue where log generation took a very long time that can look like a hang. Supposedly it is fixed now as they have bumped up the quota.

**Comment by AleksKnezevic** [comment] 2024-03-05 01:05
Straight up hangs, I waited ~20 minutes with no progress. Weka in general can be pretty awful, so I usually run everything on the local hard drive. @mo-tenstorrent , is anything stored outside of the folder where the repo is checked out?

**Comment by AleksKnezevic** [comment] 2024-03-05 12:12
@mtatsumiTT, can you please gather the logs on a wormhole host. Note, you'll need to be running at 800MHz, or it will hand, to set to 800 on IRD you can run: `/home/software/syseng/bin/tt-flash/wh/tt-flash_7.14.B.0_2024-02-09-5c5970967eec7826 --local --force`

**Comment by AleksKnezevic** [comment] 2024-03-05 19:03
Removing P0 label. With Andrew's changes on the latest SD branch I'm able to get a perf dump.

**Comment by jvasilje** [comment] 2024-03-05 19:35
@AleksKnezevic is this still a bug? or is it solved..?

**Comment by AleksKnezevic** [comment] 2024-05-31 14:51
No longer an issue, closing.

**Closed by AleksKnezevic** 2024-05-31 14:51 UTC
Labels: bug, P2_should_have, CNN_bug, Stable Diffusion
