### ISSUE TITLE
[Bug Report] Ttnn::multiply does not broadcast in second dimension

### ISSUE THREAD

**Issue by dmakoviichuk-tt** [tenstorrent/tt-metal#13646] opened 2024-10-09 18:11 UTC
**Describe the bug**
Ttnn::multiply do not broadcast in second dimension. 
Fails silently by throwing near NaN/Inf values**To Reproduce**
```
with ttnn.manage_device(device_id=0) as device:
    x = torch.ones((16, 16, 32, 32), dtype=torch.bfloat16)
    y = torch.ones((16, 1, 32, 32), dtype=torch.bfloat16) * 0.5
    
    x_tt = ttnn.from_torch(x, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)
    y_tt = ttnn.from_torch(y, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)

    x_y_mult_tt = ttnn.multiply(x_tt, y_tt)
    print(ttnn.to_torch(x_y_mult_tt))
```
It will print a garbage.
**Expected behavior**
it should work.

**Additional context**
Currently it requires us to generate broadcasted vectors on cpu.
It is a huge problem for a training performance.
@eyonland  if you don't think you can fix it please let me know I'll find another owner.

**Comment by umadevimcw** [comment] 2024-10-10 11:11
@dmakoviichuk-tt @eyonland https://github.com/tenstorrent/tt-metal/pull/13673

The above PR holds functionality support for broadcasting the second dimension using repeat.  This PR holds the functionality support. We can update this later once broadcast support is updated

**Comment by umadevimcw** [comment] 2024-10-10 11:54
In the code mentioned above, I used two tensors with the following shapes:

- input1: [16, 16, 32, 32]
- input2: [4, 1, 32, 32]

When I apply the repeat operation on input2 with repeat values [12, 1, 32, 32] for the batch dimension, I expected the resulting tensor to have the shape [16, 1, 32, 32]. However, it actually produces a tensor of shape [48, 1, 32, 32], which is 12 multiplied by 4.

Is this behavior expected? Does the repeat operation only work as intended when the tensor shape is [1, 1, 32, 32]?

**Comment by umadevimcw** [comment] 2024-10-26 04:08
PR is merged to main. Hence closing this issue

**Closed by umadevimcw** 2024-10-26 04:08 UTC
Labels: bug, P0_Showstopper, op_cat: eltwise
