### ISSUE TITLE
change dispatcher page free mechanism to track only the last block of pages

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#10668] opened 2024-07-24 14:39 UTC
Currently the dispatcher uses blocks of pages for book keeping.  When NOC has passed a full block, the pages are freed for the dispatcher.  The number of blocks is currently 4 (could change) and an array of blocks tracks the NOC transactions to know when each block can be freed.  There is code present to handle the case where the NOC is backed up and so 2 blocks contain pages to be freed.

This should work on GS/WH where the number of NOC transactions that haven't been sent is limited to 5 (4 in a queue, plus one pending).  However, on BH, this limit is increased to 32.  There is a theoretical stall where dispatcher could be in a wait loop waiting for pages from prefetcher but all of its pages are tied up in blocks that haven't been released.

Also...the bookkeeping overhead of tracking blocks when only the most recent is typically used is likely too high.

A reasonable solution to this is to track only the most recent block.  When the next block is ready to be tracked, stall until the previous block can be freed.  This will reduce book keeping overhead speeding up the common case.  If the NOC is backed up this introduces a stall...however, in that case the dispatcher is already write limited, so stalling to free the prefetcher shoulld be a good thing.

**Comment by tt-aho** [comment] 2024-09-09 22:04
Closing since this is duplicate of #11832

**Closed by tt-aho** 2024-09-09 22:04 UTC
Labels: P1_critical
