### ISSUE TITLE
TTNN RN50 on WH is broken with bad PCC

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#8131] opened 2024-05-03 21:17 UTC
`tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet50.py::test_resnet_50[batch_size=20-act_dtype=DataType.BFLOAT8_B-weight_dtype=DataType.BFLOAT8_B-math_fidelity=MathFidelity.LoFi-device_l1_small_size=24576]`
gives:
PCC = 0.0532300989040635

**Comment by shwetankTT** [comment] 2024-05-07 17:54
https://github.com/tenstorrent/tt-metal/issues/8212
The PCC issue is due to incorrect interleave to sharded conversion.

**Comment by tt-nshanker** [comment] 2024-05-07 18:13
Thanks @shwetankTT do you think there is a commit that broke interleaved to sharded op? Or a commit that changed the model code with a new interleaved to sharded conversion?

**Comment by shwetankTT** [comment] 2024-05-07 18:24
I didn't check that.

**Comment by tt-nshanker** [comment] 2024-05-07 18:27
Here is an old commit in main - `4875899c6748d979ec54a4c6cbae0705beb14902` before the breakage

**Comment by tt-nshanker** [comment] 2024-05-07 18:29
We could also confirm that the old passing commit has the same op configuration as the latest i.e. there was no change in the ops in the model.

**Comment by shwetankTT** [comment] 2024-05-07 19:12
#8212 issue is not reproducible in 4875899c6748d979ec54a4c6cbae0705beb14902 commit.

**Comment by nsmithtt** [comment] 2024-05-08 14:19
@mywoodstock, didn't we already regress this?  I thought we determined it to be commit:

```
commit 2536bf0c11682b5c5362b93f93d8971eb7e026dc
Author: Abhinav Sarje <asarje@tenstorrent.com>
Date:   Fri Apr 19 00:53:16 2024 +0000

    #0: Explicitly use multicore for untilize on WHB0 version
    #0: untilize, sharded output height doesn't need to be multiple of tile height
    #0: dont need separate to mem config
```

**Comment by shwetankTT** [comment] 2024-05-08 14:20
This is one more issue for PCC failure. 58dc4f46f9a51ae3c9f11d0d05a7ac6407a94d7d @tarafdarTT

**Comment by shwetankTT** [comment] 2024-05-08 14:28
> @mywoodstock, didn't we already regress this? I thought we determined it to be commit [2536bf0](https://github.com/tenstorrent/tt-metal/commit/2536bf0c11682b5c5362b93f93d8971eb7e026dc)
> 
> ```
> commit 2536bf0c11682b5c5362b93f93d8971eb7e026dc
> Author: Abhinav Sarje <asarje@tenstorrent.com>
> Date:   Fri Apr 19 00:53:16 2024 +0000
> 
>     #0: Explicitly use multicore for untilize on WHB0 version
>     #0: untilize, sharded output height doesn't need to be multiple of tile height
>     #0: dont need separate to mem config
> ```

@tt-aho has fixed it. https://github.com/tenstorrent/tt-metal/issues/8212. I have yet to look at the changes.

**Comment by tarafdarTT** [comment] 2024-05-08 14:59
so is this issue fixed? @shwetankTT @mywoodstock

**Comment by shwetankTT** [comment] 2024-05-08 15:29
Linked issue https://github.com/tenstorrent/tt-metal/issues/8260

**Comment by shwetankTT** [comment] 2024-05-10 05:11
Waiting for the merge of https://github.com/tenstorrent/tt-metal/pull/8279 PR.

**Comment by davorchap** [comment] 2024-05-23 01:39
@shwetankTT , @tarafdarTT has merged the fixed for https://github.com/tenstorrent/tt-metal/pull/8279
(this was reverted , but it's fixed and merged back in) 
Please re-try RN50 WH

**Comment by tarafdarTT** [comment] 2024-05-23 01:43
Sorry I think I miscommunicated. it's not merged yet. its ready to merge once people approve the PR and @nsmithtt addresses if this fix with his fix addresses the issue in nightly.
This is the PR: https://github.com/tenstorrent/tt-metal/pull/8746

**Comment by nsmithtt** [comment] 2024-05-24 14:05
@tarafdarTT, yes there are currently 3 issues that depend on this fix: #8260, https://github.com/tenstorrent/tt-metal/issues/8462, https://github.com/tenstorrent/tt-metal/issues/8555

**Comment by mywoodstock** [comment] 2024-05-28 18:19
I believe this is resolved and can be closed? @shwetankTT

**Comment by shwetankTT** [comment] 2024-05-28 18:23
Not yet fixed. It was fixed with this branch tarafdarTT/reshard_with_padding_2 but there are some shard related changes which have introduced new bug. I have informed @tarafdarTT regarding this. I will work with him to resolve this.

**Comment by shwetankTT** [comment] 2024-05-31 17:06
Closing as complete.

**Closed by shwetankTT** 2024-05-31 17:06 UTC
Labels: bug, P0_Showstopper, ResNet-50, CNN_bug
