### ISSUE TITLE
Migrate binary remainder_bw, fmod_bw to TTNN

### ISSUE THREAD

**Issue by VirdhatchaniKN** [tenstorrent/tt-metal#10163] opened 2024-07-11 14:56 UTC
Binary backward Tracking issue : #9628 [ Master issue : #9322 ]
Migrate the following binary backward ops to TTNN

- [x] #9712
- [x] #9707 

### What is the problem?
Binary backward remainder and FMOD are Div-dependent ops. 
Remainder uses `floor_div`: `div(input, other, “floor”)`
FMOD uses `trunc_div`:` div(input, other, “trunc”)`

There is an output mismatch in these ops due to precision error in Div. For certain input values, the output of division is incorrect. 
- Eg: Numerator = 450.0, denominator = 15.0
  <img width="587" alt="Screenshot 2024-07-04 at 18 56 57" src="https://github.com/user-attachments/assets/882faf4a-25a3-40dc-9d11-3414874ea84d">
  The expected result is 30.0, but TT result is 29.0 after flooring/truncating.

This problem affects binary remainder and FMOD backward when the denominator is a factor of numerator. This causes substantial change in the output while calculating the gradient of these functions. However, it only causes this error for certain input values i.e. it does not cause the error for all denominators that are factors of numerator. So resolving this issue is a little tricky.

### What have we done so far?
This precision error also affects the output when numerator = denominator for certain input values, we have implemented the following condition to handle this specific mismatch:
```
Tensor result_div = div(input, other, true, "floor");
result_div = where(ttnn::eq(input, other, std::nullopt, output_mem_config), 1.0f, result_div, output_mem_config);
```

### What inputs do we need from TT?

- We need a solution for this Div precision issue (or) 
- A strategy that can handle the output mismatch such that the floored/truncated output is corrected for the input values where the precision error occurs.

### Test Commands:
- Binary Remainder_bw: `pytest tests/ttnn/unit_tests/operations/backward/test_backward_binary_remainder.py`
- Binary FMOD_bw: `pytest tests/ttnn/unit_tests/operations/backward/test_backward_binary_fmod.py`

Refer to this document for more details:
[Precision Error in Div and related Ops.pdf](https://github.com/user-attachments/files/16414982/Precision.Error.in.Div.and.related.Ops.pdf)

**Comment by rtawfik01** [comment] 2024-07-15 18:00
@VirdhatchaniKN @mcw-anasuya can you provide a test with the standalone div function, with a range of inputs for both floor and trunc mode, and plot where the inaccuracies begin to occur?

**Comment by rtawfik01** [comment] 2024-07-17 04:25
@ttmtrajkovic fyi

**Comment by eyonland** [comment] 2024-07-17 15:56
Can I get an update on where we are on this effort?

**Comment by rdjogoTT** [comment] 2024-07-18 21:57
@VirdhatchaniKN @mcw-anasuya 
So it seems that the accuracy of the recip() kernel used for div() implementation can be improved for fp16b data. My branch `rd/recip_fp16b_acc` has the changes for this, and when I run `test_backward_binary_remainder.py`, I see the PCC improve from 0.71... to 0.94... . Is 0.94... PCC high enough? What is the desired PCC target?

Also, when I try testing `test_backward_binary_fmod.py`, I get 0.002... PCC with and without my changes, on the branch `mouliraj/backward`. Can one of you test to see if my changes improve the PCC of this test as well since I am unable to reproduce? Thanks.

**Comment by rdjogoTT** [comment] 2024-07-19 13:41
If >0.94 PCC is desired, it may be necessary to consider fp32 + unpack to dest, as that would be a method of utilizing full precision. Is fp16b a requirement for this op?

**Comment by mcw-anasuya** [comment] 2024-07-22 15:08
Hi @rdjogoTT 
We are using fp16b since it is supported in GS arch. fp32 is not supported in GS and is only supported in wormhole.

**Comment by mcw-anasuya** [comment] 2024-07-29 16:52
@rdjogoTT Hi there. Sorry for the delayed response since we were very busy with the migration task. 
I tried your solution, but it was throwing a build error with recipe. However, I tried your logic while migrating div op and used typecast to give higher precision while using WH_B0. The PCC increased to 0.96 for certain input ranges. However, when I use the same input range (eg: numerator = denominator in range [-100, 100]), it fails with a very low PCC. I'm trying to resolve the error with recip to see if it can increase the precision for this range.

**Comment by mcw-anasuya** [comment] 2024-08-01 13:51
@rdjogoTT @eyonland @VirdhatchaniKN 
This approach increased the PCC to at least 0.95 for **ALL** input intervals I have tested in the range [-1e3, 1e3]. I made some tweaks in the logic for backward remainder and all test cases passed with PCC 0.99 in the range [-1e3, 1e3]. 
I will run some more tests to find out the max input range that produces the right output.

I'll also make similar changes in binary fmod and update it here.

**Comment by mcw-anasuya** [comment] 2024-08-06 12:50
Hi @rdjogoTT @eyonland @VirdhatchaniKN 
I've made some additional changes and both binary remainder and fmod backward are working fine. Since WH_B0 has issues handling inf values, it is to be noted that the test cases might fail if there are zeros in the denominator tensor.

@rdjogoTT request you to push the submodule changes you have suggested to these branches in order to run CI.

**Comment by mcw-anasuya** [comment] 2024-08-09 06:44
@umadevimcw @eyonland @VirdhatchaniKN @rtawfik01 @rdjogoTT 
Moved to On Hold since the fix provided by @rtawfik01 causes Falcon7b models to fail with precision loss. Awaiting @rdjogoTT 's inputs.

**Comment by rdjogoTT** [comment] 2024-08-14 02:17
> @umadevimcw @eyonland @VirdhatchaniKN @rtawfik01 @rdjogoTT Moved to On Hold since the fix provided by @rtawfik01 causes Falcon7b models to fail with precision loss. Awaiting inputs from @rdjogoTT .
@mcw-anasuya issues with any models have been addressed with https://github.com/tenstorrent/tt-metal/pull/11319, the fix is back in main.

**Comment by ttmtrajkovic** [comment] 2024-08-28 14:39
de-assign @rdjogoTT and remove from LLK tracking list

**Comment by mcw-anasuya** [comment] 2024-09-07 11:23
Merged, hence closing.

**Closed by mcw-anasuya** 2024-09-07 11:23 UTC
Labels: op_cat: eltwise, MCW
