### ISSUE TITLE
t3k model falcon7b perf issue inference time

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#10191] opened 2024-07-11 23:31 UTC
**Describe the bug**
Deterministic issue

```
Traceback (most recent call last):
  File "models/perf/merge_perf_results.py", line 27, in <module>
    check_perf_results(fname, expected_cols, check_cols)
  File "/home/ubuntu/actions-runner/_work/tt-metal/tt-metal/models/perf/perf_utils.py", line 86, in check_perf_results
    assert (
AssertionError: Some model(s) Inference Time (sec) are too slow, see above for details on slow models: [('Falcon_decode_num_devices=4_kv_cache_len=1024_seq_len=1_num_layers=32_config=BFLOAT16-L1_SHARDED_async=False_ num_devices=4_kv_cache_len=1024_seq_len=1_num_layers=32_config=BFLOAT16-L1_SHARDED_async=False', 0.0919, 0.09), ('Falcon_decode_num_devices=4_kv_cache_len=128_seq_len=1_num_layers=32_config=BFLOAT16-L1_SHARDED_async=False_ num_devices=4_kv_cache_len=128_seq_len=1_num_layers=32_config=BFLOAT16-L1_SHARDED_async=False', 0.0921, 0.09)]
```
Failing inference time
https://github.com/tenstorrent/tt-metal/actions/runs/9885085612/job/27302610904
https://github.com/tenstorrent/tt-metal/actions/runs/9885083731/job/27302609417

**To Reproduce**
Run Model perf and falcon 7b fails everytime

**Expected behavior**
Passing pipeline

**Comment by skhorasganiTT** [comment] 2024-07-12 12:48
Last passing run before the failures posted: https://github.com/tenstorrent/tt-metal/actions/runs/9856730907 (f5c2ff5)

First observed perf failure: https://github.com/tenstorrent/tt-metal/actions/runs/9883320131 (7ef58ab)

Tried both commits locally for decode-1024-noasync and got 0.08s (less than the target) and didn't observe a noticeable regression. It's possible that the perf diff is due to a minor regression or noise, so may have to adjust the target slightly. However, the latest non-hanging run (https://github.com/tenstorrent/tt-metal/actions/runs/9904963233) passed so perhaps no action is required unless it occurs again.

**Comment by skhorasganiTT** [comment] 2024-07-12 17:27
@ttmchiou I am observing that CI machine `f12cs02` is resulting in lower e2e perf than the other machines in the recent failures. I recall you mentioned this machine has a different configuration than the other ones. I am going to adjust the targets in the meantime, but can all the machines be made to have the same configuration? Otherwise debugging regressions is quite difficult.

**Comment by ttmchiou** [comment] 2024-07-12 17:34
@skhorasganiTT I've set f12cs02 to only run functional t3k tests so that perf benchmarks will only be executed by machines on the same HW configuration. If you see f12cs02 to be running on perf tests, let me know

**Comment by skhorasganiTT** [comment] 2024-07-12 17:39
Okay thank you for letting me know, I will keep an eye.

**Comment by skhorasganiTT** [comment] 2024-07-15 16:13
Closing this as the perf failure has not been observed for the last 3 days (and there haven't been any runs on f12cs02).

**Closed by skhorasganiTT** 2024-07-15 16:14 UTC
Labels: bug, falcon_7B, LLM_bug, ci-bug
