### ISSUE TITLE
Reshape of tensors on device hangs the device

### ISSUE THREAD

**Issue by mtopalovicTT** [tenstorrent/tt-metal#13799] opened 2024-10-15 06:46 UTC
**Describe the bug**
Reshaping of tile aligned tensor on device hangs subsequent reshapes (see example).
When attaching with debugger I can see that reshape after tile aligned reshape is stuck waiting on some read to complete.
There is another reader thread, which processed read completion queue and it's looping all the time waiting for read to complete.

**To Reproduce**
```python
import torch
import ttnn

device_id = 0
device = ttnn.open_device(device_id=device_id)

def reshape(shape, target_shape):
    randt = torch.rand(shape, dtype=torch.float32)

    in_tensor = ttnn.from_torch(
        randt,
        dtype=ttnn.uint32,
        memory_config=ttnn.DRAM_MEMORY_CONFIG,
        device=device,
        layout=ttnn.TILE_LAYOUT,
    )

    try:
        print("Reshaping tensor from {} to {}".format(shape, target_shape))
        in_tensor = ttnn.to_device(in_tensor, device)
        ttnn.reshape(in_tensor, target_shape)
        print("Reshape successful")
    except Exception as e:
        print(e)

# first example
reshape([12], (1, 1, 1, 12))
reshape([32], (1, 1, 1, 32))
reshape([1, 7], (1, 1, 1, 7)) # <-- stuck here

#second example
# reshape([12], (1, 1, 1, 12))
# reshape([5], (1, 1, 1, 5]))
# reshape([32], (1, 1, 1, 32)) 
# reshape([1, 7], (1, 1, 1, 7)) # <-- stuck here

# third example
# reshape([12], (1, 1, 1, 12))
# reshape([32], (1, 1, 1, 32)) 
# reshape([5], (1, 1, 1, 5])) # <-- stuck here
# reshape([1, 7], (1, 1, 1, 7))

# fourth example (gets stuck on first op which tries to read from device after last reshape)
# reshape([12], (1, 1, 1, 12))
# reshape([32], (1, 1, 1, 32))
# reshape([32], (1, 1, 1, 32))

ttnn.close_device(device)
```

**Expected behavior**

**Screenshots**

**Please complete the following environment information:**
- OS: Ubuntu 22
- Version of software: latest main

**Additional context**

**Comment by tt-mpantic** [comment] 2024-10-18 09:07
Hi @ntarafdar, this is follow up of this issue https://github.com/tenstorrent/tt-metal/issues/12866
After we consumed fix produced for issue 12866 we are are encountering hangs.
Any chance you can prioritise this one, since it is follow up on previous fix ?

**Comment by ntarafdar** [comment] 2024-10-29 19:35
Ya the PR that "fixed" this was reverted due to perf regression. That initial fix was with host fallback.

A better fix is here: https://github.com/tenstorrent/tt-metal/pull/14325 , this fixes the underlying issue, untilize and tilize didn't handle uint32. Once this is merged we can close this issue.

**Comment by ntarafdar** [comment] 2024-10-29 20:34
being held up with a weird CI issue, looking into it. working locally but not on CI:
https://github.com/tenstorrent/tt-metal/actions/runs/11536195346/job/32127950820

**Comment by ntarafdar** [comment] 2024-11-06 19:48
fixed with untilize bug

**Closed by ntarafdar** 2024-11-06 19:48 UTC
Labels: bug, P1, forge
