### ISSUE TITLE
New Op: All Gather Matmul

### ISSUE THREAD

**Issue by caixunshiren** [tenstorrent/tt-metal#10460] opened 2024-07-18 20:28 UTC
### Description
We propose overlapping the all gather op and the matmul op by executing partial out product of the matmul whenever a chunk is recieved in during the ring all gather. A ring all gather is shown below (beautiful diagram created by @SeanNijjar ):

<img width="759" alt="image" src="https://github.com/user-attachments/assets/aa23bd2f-07e2-48df-910b-8c83a218e44b">

At each t, matmul can be performed on the recieved chunks on idle cores, which can significantly improve utilization and latency of device. Note that the order does not matter as long as the output accumulates. See below proposed scheme:

<img width="843" alt="image" src="https://github.com/user-attachments/assets/d487a80e-3338-4a0a-8554-ecae37fea3b5">

A pseudo code is shown below:
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/50438cee-20a2-4a1b-b154-7e613dce3d40">

FYI: @cglagovichTT @SeanNijjar

**Comment by cglagovichTT** [comment] 2024-07-19 12:23
Pseudocode looks good. Looks like your diagram shows a somewhat random ordering of timesteps - this might be showing that the op can support whatever arbitrary order the core receives remote data in?

**Comment by SeanNijjar** [comment] 2024-07-19 14:13
Closing this as duplicate of https://github.com/tenstorrent/tt-metal/issues/10415

**Closed by SeanNijjar** 2024-07-19 14:13 UTC
Labels: kernels, LLM_feature, op_cat: ccl
