### ISSUE TITLE
SD model fails from main on Wormhole N300

### ISSUE THREAD

**Issue by vshenoyTT** [tenstorrent/tt-metal#9945] opened 2024-07-04 01:05 UTC
**Describe the bug**
SD demo test fails from the main branch.

**To Reproduce**
1. Checkout to [main](https://github.com/tenstorrent/tt-metal)
2. Run the command: 
`pytest --disable-warnings --input-path="models/demos/wormhole/stable_diffusion/demo/input_data.json" models/demos/wormhole/stable_diffusion/demo/demo.py::test_demo`
3. See the error: `FAILED models/demos/wormhole/stable_diffusion/demo/demo.py::test_demo[image_size0-50-1-device_params0] - RuntimeError: TT_FATAL @ ../tt_eager/tt_dnn/op_library/sharded/sharded_op.cpp:40: this->grid_size.x <= device_grid.x && this->grid_..`

**Expected behavior**
The PyTest passes.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software ([f587cb5](https://github.com/tenstorrent/tt-metal/commit/f587cb5b8cdbaf558078de3127fd526b4a8a680f))
- N300

**Comment by tt-rkim** [comment] 2024-07-11 14:16
Note that this hangs deterministically on N300 on our demo pipeline: https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml

Last known good is https://github.com/tenstorrent/tt-metal/commit/2608a8f069a939f2e90d9e90ff14ad291fe4b108

**Comment by tt-rkim** [comment] 2024-07-11 16:02
Hmm... is this last known good?

Re-running as I'm getting hangs on both cards for a couple commits after: https://github.com/tenstorrent/tt-metal/actions/runs/9705286098

I'm wondering if there's something wrong with loading the cached tensors

**Comment by shwetankTT** [comment] 2024-07-15 17:02
I am still looking into it. I was able to root-cause the issue mentioned here fixed it but there are other layers which are failing as well.

**Comment by mywoodstock** [comment] 2024-07-16 19:05
There seem to be two separate issues:

1. The grid size error. This is fixed by using full 8x8 grid on n300 (The test is currently not supported for 7x8). This issue.
2. Hang (sus due to di/dt).

To use full grid, we need to use:

**Comment by tt-rkim** [comment] 2024-07-16 19:21
I don't understand - this is stated in the run instructions: https://github.com/tenstorrent/tt-metal/tree/main/models/demos/wormhole/stable_diffusion#how-to-run

Did you miss this part? @vshenoyTT

**Comment by mywoodstock** [comment] 2024-07-16 19:28
So this ticket can be closed. Should we open a new one for the hang issue @tt-rkim ?

**Comment by mywoodstock** [comment] 2024-07-16 19:34
yes thats the same it looks like. It says `di/dt` confirmed on it :-/

**Comment by mywoodstock** [comment] 2024-07-16 19:41
anyway, lets track the hang on the original issue. And once @vshenoyTT confirms on the env var setting, we can close this one.

**Comment by tt-rkim** [comment] 2024-07-16 23:29
@dvartaniansTT @mbahnasTT we need a respond on this , thanks

**Comment by tt-rkim** [comment] 2024-07-16 23:30
@dvartaniansTT @mbahnasTT @vshenoyTT 
You will notice a hang on stable diffusion on N300 quite often, though you should observe it pass at some point.

Given time of the release, I think we will have to ship it as is and warn users not to run on N300.

**Comment by dvartaniansTT** [comment] 2024-07-17 00:31
@tt-rkim sounds good. so on v51 we will notify the user that N300 is not functional right?

**Comment by tt-rkim** [comment] 2024-07-17 02:03
We will notify on latest main right tomorrow, and if by v51 it is still not working, it will be in there as well.

**Comment by vshenoyTT** [comment] 2024-07-17 21:58
I do not get the error message anymore (tested on v0.50.0). However, the process hangs like y'all described above.

**Closed** 2024-07-17 23:09 UTC
Labels: bug, P0_Showstopper, CNNs, Stable Diffusion

**Comment by tt-rkim** [comment] 2024-07-18 20:34
We will be closing this in favour of #7560
