### ISSUE TITLE
[Bug Report] Untilizing crashes or hangs with tensor reshaped to non tile aligned shape

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#9853] opened 2024-06-30 03:59 UTC
**Describe the bug**

Untilization (`tensor.to(tt::tt_metal::Layour::ROW_MAJOR)`) crashes if the tesnor is in the TILE layout but not padded. This can happen if  the tensor is reshaped from a padded tensor. Weirdly, the shape of the reshaped tensor is `ttnn.Shape([1, 2, 8, 256])`, indicating it is not padded. Maybe this is the problem?

Found this while implementing operations for GGML, where it need to transfer results between the Metalium backend and the CPU (until I can fully implement all functions needed).

```py
import torch
import ttnn

device = ttnn.open_device(0)

a = torch.rand(1, 1, 2, 2048)

ttnn.enable_program_cache(device)

x = ttnn.from_torch(a, device=device, layout=ttnn.Layout.TILE, dtype=ttnn.DataType.BFLOAT16)
y = x.reshape([1, 2, 8, 256])

b = ttnn.to_torch(y) # Crashes here
```

The equivalent C++ program hangs.

```c++
static tt::tt_metal::Tensor make_random_tensor(tt::tt_metal::Shape s)
{
    static int seed = 42;
     auto b = tt::tt_metal::owned_buffer::create(
        create_random_vector_of_bfloat16_native(
        s[0] * s[1] * s[2] * s[3] * 2
            , 2, seed++, -1));
    tt::tt_metal::Tensor t(OwnedStorage{std::move(b)}, s
        , tt::tt_metal::DataType::BFLOAT16, tt::tt_metal::Layout::ROW_MAJOR);
    return tt::tt_metal::tilize_with_zero_padding(t.to(AutoFormat::GetDefaultDevice()));
}
int main()
{
    auto device = &ttnn::open_device(0);
    AutoFormat::SetDefaultDevice(device);
    ttnn::enable_program_cache(*device); // Program cache HAS to be enabled

    auto a = make_random_tensor(tt::tt_metal::Shape{1, 1, 2, 2048});
    auto b = a.reshape({1, 2, 8, 256});

    auto c = b.cpu().to(tt::tt_metal::Layout::ROW_MAJOR);

    device->close();
}
```

**To Reproduce**
1. Run the above examples
2. See the crash with `corrupted size vs. prev_size` or it hangs

**Expected behavior**

The application should not crash or hang.

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by ayerofieiev-tt** [comment] 2024-07-01 21:29
```
import torch
import ttnn

device = ttnn.open_device(0)

a = torch.rand(1, 1, 2, 2048)

ttnn.enable_program_cache(device)

x = ttnn.from_torch(a, device=device, layout=ttnn.Layout.TILE, dtype=ttnn.DataType.BFLOAT16)
```

Now `x` shape is `[1, 1, 32, 2048]` - that 32 is a padded dimension.
I'd expect `reshape` into `[1, 2, 8, 256]` to throw as illegal in this case.

@arakhmati , wdyt, should we add more checks to reshape?

**Comment by marty1885** [comment] 2024-07-02 05:01
@ayerofieiev-tt is there an efficient way to work around this in TTNN? This reshape is one of the needed operation during my bringup of Gemma 2B on GGML. (I will need to eliminate this reshape for performance in the future. But now I'm focused on getting things running).

**Comment by arakhmati** [comment] 2024-07-02 17:45
@marty1885 this reshape is not possible in tile layout. You would need to write a custom operation for this case

**Comment by marty1885** [comment] 2024-07-03 03:42
I see. If that's the case can we make TTNN throw when a invalid reshape is issued?

**Comment by ayerofieiev-tt** [comment] 2024-07-03 21:23
Yes. We will add a proper check and throw an error. Thank you!

**Comment by jvasilje** [comment] 2024-11-07 02:23
@ntarafdar can you post an update on this P0 bug?

**Comment by ntarafdar** [comment] 2024-11-07 02:37
I think this works now with the reshape generality push. I'll confirm tomorrow morning.

**Comment by ntarafdar** [comment] 2024-11-07 15:56
hey @marty1885 , 
I think the issue is the API, the `reshape` member function on the tensor doesn't have all the checks that the ttnn reshape operation has.

the following is working:

```
@pytest.mark.parametrize(
    "input_shape, output_shape",
    [
        ((1, 1, 2, 2048), (1, 2, 8, 256)),
    ],
)
def test_reshape_hang(input_shape, output_shape, device):
    a = torch.rand(input_shape, dtype=torch.bfloat16)
    torch_result = a.reshape(output_shape)

    ttnn.enable_program_cache(device)
    
    x = ttnn.from_torch(a, device=device, layout=ttnn.Layout.TILE, dtype=ttnn.DataType.BFLOAT16)
    y = ttnn.reshape(x, output_shape) #instead of x.reshape
    
    b = ttnn.to_torch(y) # Crashes here
    assert_with_pcc(torch_result, b, 0.9999)
```

**Comment by ntarafdar** [comment] 2024-11-07 15:58
I think in our ttnn we are using ttnn.reshape so please use that function. In the meantime I will add a lower priority issue to redirect the tensor API to the ttnn api. I think this should fix your issue for now. I am closing this, if you don't think this is sufficient, please feel free to reopen.

**Closed by ntarafdar** 2024-11-07 15:58 UTC
Labels: bug, operations, P0, community
