### ISSUE TITLE
[Bug Report] Failing to compile all Metalium kernels 

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#14238] opened 2024-10-24 16:45 UTC
**Describe the bug**

I upgraded Metalium and now I can't even run the programming examples on WH. All kernels (both TTNN and Metalium examples) fails to compile with the following linker error

```
                  Metal | INFO     | Initializing device 0. Program cache is NOT enabled
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
           BuildKernels | INFO     | brisc link failure -- cmd: cd /home/marty/Documents/tt/tt-metal//built/6176/kernels/cq_dispatch_slave/3194848412544428797/brisc/ && /home/marty/Documents/tt/tt-metal//tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-g++ -mwormhole -march=rv32imw -mtune=rvtt-b1 -mabi=ilp32 -std=c++17 -flto -ffast-math -fno-exceptions -Wl,-z,max-page-size=16 -Wl,-z,common-page-size=16 -nostartfiles -Os -T/home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/kernel_brisc.ld -Wl,--emit-relocs brisck.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/tmu-crt0k.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/noc.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/substitutes.o -Wl,--just-symbols=/home/marty/Documents/tt/tt-metal//built/6176/firmware/brisc/brisc_weakened.elf -o /home/marty/Documents/tt/tt-metal//built/6176/kernels/cq_dispatch_slave/3194848412544428797/brisc/brisc.elf
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.2.0/../../../../riscv32-unknown-elf/bin/ld: /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/tmu-crt0k.o: in function `_start':
(.start+0x0): undefined reference to `kernel_launch()'
collect2: error: ld returned 1 exit status
                 Always | FATAL    | brisc build failed
                 Always | FATAL    | Failed to generate binaries for cq_dispatch_slave TT_THROW @ /home/marty/Documents/tt/tt-metal/tt_metal/jit_build/build.cpp:479: tt::exception
```

**To Reproduce**
1. Compile Metal and examples
2. Run any of the programming examples
3. Observe compilation failure

**Expected behavior**
Kernel compilation should work

**Screenshots**

**Please complete the following environment information:**
- OS: Arch Linux
- Card: WH N300
- Commit: c93572ec5dc422f2170588865d6ae8de9bdef15c

**Additional context**

**Comment by ayerofieiev-tt** [comment] 2024-10-24 16:46
@marty1885 , can you please make sure to update all submodules?

CC @pgkeller

**Comment by marty1885** [comment] 2024-10-24 17:09
NVM... I must have missed something. I did an entire flow of submodule sync, lfs pull and etc... (the flow recommended by TT) (`git submodule update && git submodule foreach 'git lfs fetch --all && git lfs pull' in the docs). A rebuild still results in the same problem.

I had to do a complete re-clone to get it fixed. Should I close the issue or you wanna look into the update procedure?

**Comment by tt-aho** [comment] 2024-10-24 17:23
Does output of `git status` in the original failing cloned repo report anything? We haven't seen any other reports of this, and programming examples are run as part of our regression testing. I will try to see if I can repro on my side but otherwise if it's not reproducible we can probably close the issue.

**Comment by marty1885** [comment] 2024-10-24 17:26
No, `git status` of the failing clone is clean.

**Comment by tt-aho** [comment] 2024-10-24 17:26
I was able to repro, so I'll take a look

**Comment by tt-aho** [comment] 2024-10-24 18:33
I've confirmed it's something stale with our build/cache. Deleting the relevant build folder(s) and rebuilding will also resolve the issue instead of a full reclone. Continuing to look into how to resolve the stale build automatically.

**Comment by marty1885** [comment] 2024-10-25 14:07
@tt-aho What is your workaround? I pulled Metalium again and the problem showed up again. I tried deleting `/built` and `/runtime` but ended with this error.

```
           BuildKernels | INFO     | trisc1 link failure -- cmd: cd /home/marty/Documents/tt/tt-metal//built/6176/firmware/trisc1/ && /home/marty/Documents/tt/tt-metal//tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-g++ -mwormhole -march=rv32imw -mtune=rvtt-b1 -mabi=ilp32 -std=c++17 -flto -ffast-math -fno-exceptions -Wl,-z,max-page-size=16 -Wl,-z,common-page-size=16 -nostartfiles -O3 -T/home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_trisc1.ld trisc.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/tmu-crt0.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/substitutes.o -o /home/marty/Documents/tt/tt-metal//built/6176/firmware/trisc1/trisc1.elf
           BuildKernels | INFO     | trisc0 link failure -- cmd: cd /home/marty/Documents/tt/tt-metal//built/6176/firmware/trisc0/ && /home/marty/Documents/tt/tt-metal//tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-g++ -mwormhole -march=rv32imw -mtune=rvtt-b1 -mabi=ilp32 -std=c++17 -flto -ffast-math -fno-exceptions -Wl,-z,max-page-size=16 -Wl,-z,common-page-size=16 -nostartfiles -O3 -T/home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_trisc0.ld trisc.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/tmu-crt0.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/substitutes.o -o /home/marty/Documents/tt/tt-metal//built/6176/firmware/trisc0/trisc0.elf
           BuildKernels | INFO     | trisc2 link failure -- cmd: cd /home/marty/Documents/tt/tt-metal//built/6176/firmware/trisc2/ && /home/marty/Documents/tt/tt-metal//tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-g++ -mwormhole -march=rv32imw -mtune=rvtt-b1 -mabi=ilp32 -std=c++17 -flto -ffast-math -fno-exceptions -Wl,-z,max-page-size=16 -Wl,-z,common-page-size=16 -nostartfiles -O3 -T/home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_trisc2.ld trisc.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/tmu-crt0.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/substitutes.o -o /home/marty/Documents/tt/tt-metal//built/6176/firmware/trisc2/trisc2.elf
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.2.0/../../../../riscv32-unknown-elf/bin/ld: cannot open linker script file /home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_trisc1.ld: No such file or directory
collect2: error: ld returned 1 exit status
                 Always | FATAL    | trisc1 build failed
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.2.0/../../../../riscv32-unknown-elf/bin/ld: cannot open linker script file /home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_trisc0.ld: No such file or directory
collect2: error: ld returned 1 exit status
                 Always | FATAL    | trisc0 build failed
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.2.0/../../../../riscv32-unknown-elf/bin/ld: cannot open linker script file /home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_trisc2.ld: No such file or directory
collect2: error: ld returned 1 exit status
                 Always | FATAL    | trisc2 build failed
           BuildKernels | INFO     | ncrisc link failure -- cmd: cd /home/marty/Documents/tt/tt-metal//built/6176/firmware/ncrisc/ && /home/marty/Documents/tt/tt-metal//tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-g++ -mwormhole -march=rv32imw -mtune=rvtt-b1 -mabi=ilp32 -std=c++17 -flto -ffast-math -fno-exceptions -Wl,-z,max-page-size=16 -Wl,-z,common-page-size=16 -nostartfiles -Os -T/home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_ncrisc.ld ncrisc.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/tmu-crt0.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/ncrisc-halt.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/substitutes.o -o /home/marty/Documents/tt/tt-metal//built/6176/firmware/ncrisc/ncrisc.elf
           BuildKernels | INFO     | erisc link failure -- cmd: cd /home/marty/Documents/tt/tt-metal//built/6176/firmware/erisc/ && /home/marty/Documents/tt/tt-metal//tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-g++ -mwormhole -march=rv32imw -mtune=rvtt-b1 -mabi=ilp32 -std=c++17 -flto -ffast-math -fno-exceptions -Wl,-z,max-page-size=16 -Wl,-z,common-page-size=16 -nostartfiles -Os -L/home/marty/Documents/tt/tt-metal///tt_metal/hw/toolchain -T/home/marty/Documents/tt/tt-metal//tt_metal/hw/toolchain/erisc-b0-app.ld erisc.o erisc-crt0.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/substitutes.o -o /home/marty/Documents/tt/tt-metal//built/6176/firmware/erisc/erisc.elf
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.2.0/../../../../riscv32-unknown-elf/bin/ld: cannot open linker script file /home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_ncrisc.ld: No such file or directory
collect2: error: ld returned 1 exit status
                 Always | FATAL    | ncrisc build failed
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.2.0/../../../../riscv32-unknown-elf/bin/ld: cannot find /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/substitutes.o: No such file or directory
collect2: error: ld returned 1 exit status
                 Always | FATAL    | erisc build failed
           BuildKernels | INFO     | idle_erisc link failure -- cmd: cd /home/marty/Documents/tt/tt-metal//built/6176/firmware/idle_erisc/ && /home/marty/Documents/tt/tt-metal//tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-g++ -mwormhole -march=rv32imw -mtune=rvtt-b1 -mabi=ilp32 -std=c++17 -flto -ffast-math -fno-exceptions -Wl,-z,max-page-size=16 -Wl,-z,common-page-size=16 -nostartfiles -Os -T/home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_ierisc.ld idle_erisc.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/tmu-crt0.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/noc.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/substitutes.o -o /home/marty/Documents/tt/tt-metal//built/6176/firmware/idle_erisc/idle_erisc.elf
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.2.0/../../../../riscv32-unknown-elf/bin/ld: cannot open linker script file /home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_ierisc.ld: No such file or directory
collect2: error: ld returned 1 exit status
                 Always | FATAL    | idle_erisc build failed
           BuildKernels | INFO     | brisc link failure -- cmd: cd /home/marty/Documents/tt/tt-metal//built/6176/firmware/brisc/ && /home/marty/Documents/tt/tt-metal//tt_metal/third_party/sfpi/compiler/bin/riscv32-unknown-elf-g++ -mwormhole -march=rv32imw -mtune=rvtt-b1 -mabi=ilp32 -std=c++17 -flto -ffast-math -fno-exceptions -Wl,-z,max-page-size=16 -Wl,-z,common-page-size=16 -nostartfiles -Os -T/home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_brisc.ld brisc.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/tdma_xmov.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/tmu-crt0.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/noc.o /home/marty/Documents/tt/tt-metal//runtime/hw/lib/wormhole/substitutes.o -o /home/marty/Documents/tt/tt-metal//built/6176/firmware/brisc/brisc.elf
/home/marty/Documents/tt/tt-metal/tt_metal/third_party/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.2.0/../../../../riscv32-unknown-elf/bin/ld: cannot open linker script file /home/marty/Documents/tt/tt-metal//runtime/hw/toolchain/wormhole/firmware_brisc.ld: No such file or directory
collect2: error: ld returned 1 exit status
                 Always | FATAL    | brisc build failed
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_THROW @ /home/marty/Documents/tt/tt-metal/tt_metal/jit_build/build.cpp:474: tt::exception
info:
brisc build failed
```

**Comment by tt-aho** [comment] 2024-10-25 14:09
The minimum workaround is to delete `runtime`, and then rebuild, ex calling `build_metal.sh` again. This rebuild should be extremely quick.

**Comment by marty1885** [comment] 2024-10-25 14:12
Ah thanks! That works. Any luck on a solution? This error is quite scary to most users.

**Comment by tt-aho** [comment] 2024-10-25 17:05
Yes, we believe it's due to a missing dependency definition in a cmake file, I'm testing a potential fix now.

**Closed** 2024-10-25 18:30 UTC
Labels: bug, community

**Comment by marty1885** [comment] 2024-10-26 00:04
Thank you for the help! ❤️
